### PR TITLE
fix: many bugs related to titles, descriptions, labels not being displayed correctly

### LINKED ISSUE #827: Default checkbox field ignores ui:title and ui:description
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The default checkbox field for boolean forms does not respect the `ui:title` or `ui:description` fields making it difficult to overwrite.

### Steps to Reproduce

1. Ignored UI values
Given a schema of:
```
{
  "title": "Boolean Title",
  "description": "Boolean Description",
  "type": "boolean"
}
```
And a UI Schema of:
```
{
  "ui:title": "Overwrite Boolean Title",
  "ui:description": "Overwite Boolean Description"
}
```
#### Behavior 

The form only displays the title from the description.

#### Expected behavior

It should display the `ui:title` and the `ui:description` as well.

2. Repeated title and description

Given a schema of:
```
{
  "title": "Boolean Title",
  "description": "Boolean Description",
  "type": "boolean"
}
```
And a UI Schema of:
```
{
  "ui:title": "Overwrite Boolean Title",
  "ui:description": "Overwite Boolean Description",
  "ui:widget": "checkbox"
}
```
#### Behavior 

The form only displays the the title, the description, the ui title, the ui description and the title.

#### Expected behavior

It should display only the `ui:title` and the `ui:description`.

### Version

1.0.0

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #827, #2636, #2399, #2134, #2791, #3231,  and #3531 so that titles, descriptions and labels are picked up from uiSchema then schema and are hidden correctly when `label` in uiSchema is false
- Updated `@rjsf/utils` to add `hideLabel` to `WidgetProps` and a new `valueLabel()` helper function
- Updated `@rjsf/core` to fix the bugs as follows:
  - Updated `ArrayField`, `MultiSchemaField`, `StringField` to pass the label as `uiOptions.title || schema.title || name` as well as passing `!displayLabel` as `hideLabel` from the `uiOptions` down to all the widgets
  - Updated `ObjectField` to not pass `title` or `description` when `displayLabel` is false and `ObjectTitleTemplate` to only check `title` and `description`
  - Updated `ArrayFieldDescriptionTemplate` and `ArrayFieldTitleTemplate` to pass `globalUiOptions` into `getUiOptions` to pick up the global `label`
  - Updated `CheckboxWidget` to not show description when `hideLabel` is true
- Updated `@rjsf/antd` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `CheckboxesWidget` and `SelectWidget` to show the `label` using the `TitleFieldTemplate`, except when `hideLabel` is true
- Updated `@rjsf/bootstrap-4` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `RangeWidget` to only pass `label` in the `extraProps` when `displayLabel` is true
- Updated `@rjsf/chakra-ui` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `BaseInputTemplate`, `CheckboxesWidget`, `RadioWidget`, `RangeWidget`, `SelectWidget`, `TextareaWidget` and `UpDownWidget` to hide `label` when `displayLabel` and `label` are falsey
  - Updated test snapshots due to fixed bugs
- Updated `@rjsf/fluent-ui` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `BaseInputTemplate`, `CheckboxesWidget`, `ColorWidget`, `DateWidget`, `RadioWidget`, `RangeWidget`, `SelectWidget` and `UpDownWidget` to hide `label` when `hideLabel` is true and `label` is falsey
  - Updated `FieldTemplate` to hide description when `displayLabel` is false
  - Updated test snapshots due to fixed bugs
- Updated `@rjsf/material-ui` and `@rjsf/mui` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `BaseInputTemplate`, `CheckboxesWidget`, `RadioWidget`, `RangeWidget` and `SelectWidget` to hide `label` when `hideLabel` is true and `label` is falsey
  - Updated test snapshots due to fixed bugs
- Updated `@rjsf/semantic-ui` to fix the bugs as follows:
  - Updated `ObjectTitleTemplate` to only check `title` and `description` since they will be falsey from `ObjectField` when `displayLabel` is false
  - Updated `CheckboxWidget` to render the description using the `DescriptionFieldTemplate`, except when `hideLabel` is true
  - Updated `BaseInputTemplate`, `CheckboxesWidget`, `SelectWidget` and `TextareaWidget` to hide `label` when `hideLabel` is true and `label` is falsey
  - Updated test snapshots due to fixed bugs
- Updated the `widget` documentation for the new `hideLabel` prop
- Updated the `utility-functions` documentation for the new `valueLabel()` function
- Updated the `CHANGELOG.md` file accordingly

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/antd/src/templates/ArrayFieldTemplate/index.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export default function ArrayFieldTemplate<
               {(uiOptions.description || schema.description) && (
                 <Col span={24} style={DESCRIPTION_COL_STYLE}>
                   <ArrayFieldDescriptionTemplate
-                    description={uiOptions.description || schema.description || ''}
+                    description={uiOptions.description || schema.description}
```
Comment (heath-freenome) [inline packages/antd/src/templates/ArrayFieldTemplate/index.tsx:96]: The empty string at the end was not needed

File: packages/antd/src/widgets/CheckboxWidget/index.tsx [hunk 2]
```diff
@@ -34,19 +57,33 @@ export default function CheckboxWidget<
...
-      name={id}
-      onChange={!readonly ? handleChange : undefined}
-      {...extraProps}
-      aria-describedby={ariaDescribedByIds<T>(id)}
-    >
-      {label}
-    </Checkbox>
+    <>
+      {displayLabel && !!description && (
+        <div>
```
Comment (heath-freenome) [inline packages/antd/src/widgets/CheckboxWidget/index.tsx:65]: The antd theme's description is a span, wrapped it in a div so that the description is in a block element

File: packages/bootstrap-4/src/CheckboxWidget/CheckboxWidget.tsx [hunk 3]
```diff
@@ -14,26 +16,55 @@ export default function CheckboxWidget<
...
+          schema={schema}
+          uiSchema={uiSchema}
+          registry={registry}
+        />
+      )}
       <Form.Check
         id={id}
         name={id}
-        label={desc}
+        label={displayLabel && !!label ? label : undefined}
```
Comment (heath-freenome) [inline packages/bootstrap-4/src/CheckboxWidget/CheckboxWidget.tsx:67]: the `!!label` prevents an empty string from rendering a useless label

File: packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 4]
```diff
@@ -21,6 +21,7 @@ export default function BaseInputTemplate<
     type,
     value,
     label,
+    displayLabel = true,
```
Comment (heath-freenome) [inline packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:24]: To prevent a breaking change I made `displayLabel` on `WidgetProps` optional, so I default it to true everywhere

File: packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 5]
```diff
@@ -56,11 +53,11 @@ export default function BaseInputTemplate<
       isReadOnly={readonly}
       isInvalid={rawErrors && rawErrors.length > 0}
     >
-      {displayLabel ? (
+      {displayLabel && !!label && (
```
Comment (heath-freenome) [inline packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:56]: Since label can be an empty string, I use the `!!label` so that it renders `false` everywhere in the `chakra-ui` theme

File: packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 6]
```diff
@@ -56,11 +53,11 @@ export default function BaseInputTemplate<
...
         <FormLabel htmlFor={id} id={`${id}-label`}>
-          {label || schema.title}
```
Comment (heath-freenome) [inline packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:61]: And since we don't render empty labels, we don't need the `|| schema.title` everywhere in the `chakra-ui` theme

File: packages/chakra-ui/test/__snapshots__/Form.test.tsx.snap [hunk 7]
```diff
@@ -5494,7 +5473,7 @@ exports[`single fields title field 1`] = `
                   htmlFor="root_title"
                   id="root_title-label"
                 >
-                  title
+                  Titre 2
```
Comment (heath-freenome) [inline packages/chakra-ui/test/__snapshots__/Form.test.tsx.snap:5476]: Look bug fix!

File: packages/core/src/components/fields/BooleanField.tsx [hunk 8]
```diff
@@ -36,14 +36,18 @@ function BooleanField<T = any, S extends StrictRJSFSchema = RJSFSchema, F extend
     rawErrors,
   } = props;
   const { title } = schema;
-  const { widgets, formContext, translateString } = registry;
-  const { widget = 'checkbox', ...options } = getUiOptions<T, S, F>(uiSchema);
+  const { widgets, formContext, translateString, globalUiOptions } = registry;
+  const {
+    widget = 'checkbox',
+    title: uiTitle,
+    label: displayLabel = true,
```
Comment (heath-freenome) [inline packages/core/src/components/fields/BooleanField.tsx:43]:
```suggestion
     // Unlike the other fields, we don't want to use `getDisplayLabel()` since it always returns false for the boolean type
    label: displayLabel = true,
```

File: packages/core/src/components/fields/ObjectField.tsx [hunk 9]
```diff
@@ -271,8 +271,8 @@ class ObjectField<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends Fo
     const Template = getTemplate<'ObjectFieldTemplate', T, S, F>('ObjectFieldTemplate', registry, uiOptions);
 
     const templateProps = {
-      title,
-      description,
+      title: uiOptions.label === false ? '' : title,
```
Comment (heath-freenome) [inline packages/core/src/components/fields/ObjectField.tsx:274]:
```suggestion
      // getDisplayLabel() always returns false for object types, so just check the `uiOptions.label`
      title: uiOptions.label === false ? '' : title,
```

**Comment by heath-freenome** [comment]
@nickgros I think I want to update the theme tests to verify that `title` and `description`, `ui:title` and `ui:description` and the global `ui:label: false` all work as expected. Feel free to review the code though.

File: packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx [hunk 10]
```diff
@@ -58,13 +74,23 @@ export default function CheckboxWidget<
...
+          schema={schema}
+          uiSchema={uiSchema}
+          registry={registry}
+        />
+      )}
       <Checkbox
         id={id}
         name={id}
-        label={label || schema.title}
+        label={displayLabel ? label || schema.title : undefined}
```
Comment (heath-freenome) [inline packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx:93]: Honestly, at this point if `label` is an empty string then `schema.title` will be `undefined`, so do we really just change it to:
```suggestion
        label={displayLabel ? label || undefined : undefined}
```
And is there better boolean logic for the above condition to eliminate one of the `undefined`s?

File: packages/mui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 11]
```diff
@@ -79,7 +77,7 @@ export default function BaseInputTemplate<
         id={id}
         name={id}
         placeholder={placeholder}
-        label={displayLabel ? label || schema.title : false}
+        label={displayLabel && (label || schema.title)}
```
Comment (heath-freenome) [inline packages/mui/src/BaseInputTemplate/BaseInputTemplate.tsx:80]: Same deal here with `schema.title` being undefined and whether we change this to:
```suggestion
        label={displayLabel && (label || undefined)}
```

File: packages/material-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 12]
```diff
@@ -79,7 +77,7 @@ export default function BaseInputTemplate<
         id={id}
         name={id}
         placeholder={placeholder}
-        label={displayLabel ? label || schema.title : false}
+        label={displayLabel && (label || schema.title)}
```
Comment (heath-freenome) [inline packages/material-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:80]: Same deal here with `schema.title` being undefined and whether we change this to:
```suggestion
        label={displayLabel && (label || undefined)}
```

File: packages/semantic-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 13]
```diff
@@ -64,7 +62,7 @@ export default function BaseInputTemplate<
         name={id}
         placeholder={placeholder}
         {...inputProps}
-        label={displayLabel ? label || schema.title : false}
+        label={displayLabel && (label || schema.title)}
```
Comment (heath-freenome) [inline packages/semantic-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:65]: Same deal here with `schema.title` being undefined and whether we change this to:
```suggestion
        label={displayLabel && (label || undefined)}
```
NOTE: In this case passing undefined for the label has a similar effect as passing false.

File: packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx (hunk 10 above)
Comment (nickgros) [reply packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx:93]: I can't think of a better way than your suggestion. I wonder if there's a case where rendering an empty string label is preferable to no label

Comment (nickgros) [reply packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx:93]: Maybe wrap the prop in a new utility 

```ts
function coerceEmptyStringToUndefined(str) {
  return str === "" ? undefined : str;
}
```

Comment (heath-freenome) [reply packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx:93]: how about?
```suggestion
        label={labelValue(label, displayLabel)}
```

File: packages/bootstrap-4/src/RangeWidget/RangeWidget.tsx [hunk 14]
```diff
@@ -1,12 +1,12 @@
...
 
 export default function RangeWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any>(
   props: WidgetProps<T, S, F>
 ) {
-  const { value, label, displayLabel = true, options, registry } = props;
+  const { value, label, hideLabel, options, registry } = props;
   const BaseInputTemplate = getTemplate<'BaseInputTemplate', T, S, F>('BaseInputTemplate', registry, options);
   return (
-    <BaseInputTemplate {...props} extraProps={displayLabel ? label : undefined}>
+    <BaseInputTemplate {...props} extraProps={{ label: labelValue(label || undefined, hideLabel) }}>
```
Comment (heath-freenome) [inline packages/bootstrap-4/src/RangeWidget/RangeWidget.tsx:9]: There was a bug here around properly passing the `label` prop. Also, passing undefined when label was falsey was better

File: packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 15]
```diff
@@ -53,10 +54,11 @@ export default function BaseInputTemplate<
       isReadOnly={readonly}
       isInvalid={rawErrors && rawErrors.length > 0}
     >
-      {displayLabel && !!label && (
+      {labelValue(
```
Comment (heath-freenome) [inline packages/chakra-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:57]: My making `labelValue()` take a component I saved a little bit of logic in many other places

File: packages/fluent-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 16]
```diff
@@ -90,7 +91,7 @@ export default function BaseInputTemplate<
         id={id}
         name={id}
         placeholder={placeholder}
-        label={displayLabel ? label || schema.title : undefined}
+        label={labelValue(label, hideLabel)}
```
Comment (heath-freenome) [inline packages/fluent-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:94]: So fluent treats empty string and undefined the same so I just dropped `schema.title`

File: packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx [hunk 17]
```diff
@@ -90,7 +91,7 @@ export default function CheckboxWidget<
       <Checkbox
         id={id}
         name={id}
-        label={displayLabel ? label || schema.title : undefined}
+        label={labelValue(label || undefined, hideLabel)}
```
Comment (heath-freenome) [inline packages/fluent-ui/src/CheckboxWidget/CheckboxWidget.tsx:94]: Of course, there is an exception, fluent does treat empty string differently than undefined here, made it more explicit

File: packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 18]
```diff
@@ -1,36 +1,30 @@
...
-import { allowedProps } from '../CheckboxWidget';
 
-const styles_red = {
-  // TODO: get this color from theme.
-  color: 'rgb(164, 38, 44)',
-  fontSize: 12,
-  fontWeight: 'normal' as any,
-  fontFamily: `"Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif`,
-};
+import FluentLabel, { styles_red } from '../FluentLabel/FluentLabel';
```
Comment (heath-freenome) [inline packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:18]: Couldn't help but refactor this :)

File: packages/fluent-ui/src/UpDownWidget/UpDownWidget.tsx [hunk 19]
```diff
@@ -99,13 +102,11 @@ export default function UpDownWidget<
...
   const _onFocus = ({ target: { value } }: FocusEvent<HTMLInputElement>) => onFocus(id, value);
 
-  const requiredSymbol = required ? '*' : '';
-
   const uiProps = _pick((options.props as object) || {}, allowedProps);
 
   return (
     <>
-      {displayLabel && <Label htmlFor={id}>{label + requiredSymbol}</Label>}
+      {labelValue(<FluentLabel label={label || undefined} required={required} id={id} />, hideLabel)}
```
Comment (heath-freenome) [inline packages/fluent-ui/src/UpDownWidget/UpDownWidget.tsx:109]: Made this one consistent with all the others

File: packages/fluent-ui/src/FluentLabel/FluentLabel.tsx [hunk 20]
```diff
@@ -0,0 +1,24 @@
...
+
+interface FluentLabelProps {
+  label?: string;
+  required?: boolean;
+  id?: string;
+}
+
+export default function FluentLabel({ label, required, id }: FluentLabelProps) {
+  return (
+    <Label htmlFor={id}>
```
Comment (heath-freenome) [inline packages/fluent-ui/src/FluentLabel/FluentLabel.tsx:19]: Added in `id` support while I was refactoring

File: packages/semantic-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 21]
```diff
@@ -62,7 +63,7 @@ export default function BaseInputTemplate<
         name={id}
         placeholder={placeholder}
         {...inputProps}
-        label={displayLabel && (label || schema.title)}
+        label={labelValue(label || undefined, hideLabel, false)}
```
Comment (heath-freenome) [inline packages/semantic-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:66]: Semantic-ui is like material-ui around `undefined`

File: CHANGELOG.md [hunk 22]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
 ## @rjsf/antd
 
 - Added the ability to use a tooltip for a description
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
+- Updated `CheckboxesWidget` and `SelectWidget` to show the `label` using the `TitleFieldTemplate`, fixing #2134
```
Comment (heath-freenome) [inline CHANGELOG.md:26]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
- Updated `CheckboxesWidget` and `SelectWidget` to show the `label` using the `TitleFieldTemplate`, fixing  [#2134](https://github.com/rjsf-team/react-jsonschema-form/issues/2134)
```

File: CHANGELOG.md [hunk 23]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+
+## @rjsf/bootstrap-4
+
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:31]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: CHANGELOG.md [hunk 24]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+- Updated `RangeWidget` to fix the label hiding bug using `labelValue()`
+
+## @rjsf/chakra-ui
+
+- Fix: MUI radio widget initializes as uncontrolled when schema has no default value, fixing [#3511](https://github.com/rjsf-team/react-jsonschema-form/issues/3511)
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:39]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: CHANGELOG.md [hunk 25]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
 
 ## @rjsf/core
 
 - Updated `FileWidget` to show a preview of images and a download link for non-images when the `filePreview` options is set to true in the `UiSchema`
+- Updated `ArrayField`, `BooleanField`, `MultiSelectField` and `StringField` to pass `label` (read from `uiSchema.title` || `schema.title` || `name`) and `hideLabel` down to all of the `Widgets` they render, fixing #827, #2636, #2399 and #3531
+- Updated `ObjectField`, `ObjectFieldTemplate`, `ArrayFieldDescriptionTemplate`, `ArrayFieldTitleTemplate` and `CheckboxWidget` to hide the titles and descriptions when `hideLabel` is true using the new `labelValue()` helper (including globally), fixing #3231
```
Comment (heath-freenome) [inline CHANGELOG.md:45]:
```suggestion
- Updated `ArrayField`, `BooleanField`, `MultiSelectField` and `StringField` to pass `label` (read from `uiSchema.title` || `schema.title` || `name`) and `hideLabel` down to all of the `Widgets` they render, fixing [#827](https://github.com/rjsf-team/react-jsonschema-form/issues/827), [#2636](https://github.com/rjsf-team/react-jsonschema-form/issues/2636), [#2399](https://github.com/rjsf-team/react-jsonschema-form/issues/2399) and [#3531](https://github.com/rjsf-team/react-jsonschema-form/issues/3531)
- Updated `ObjectField`, `ObjectFieldTemplate`, `ArrayFieldDescriptionTemplate`, `ArrayFieldTitleTemplate` and `CheckboxWidget` to hide the titles and descriptions when `hideLabel` is true using the new `labelValue()` helper (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
```

File: CHANGELOG.md [hunk 26]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+- Updated `CheckboxWidget` to use the `labelValue()` function for hiding labels
+
+## @rjsf/fluent-ui
+
+- Updated `FieldTemplate` and `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
```
Comment (heath-freenome) [inline CHANGELOG.md:50]:
```suggestion
- Updated `FieldTemplate` and `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
```

File: CHANGELOG.md [hunk 27]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `ColorWidget`, `DateWidget`, `RadioWidget`, `RangeWidget`, `SelectWidget` and `UpDownWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
+  - Also extracted a new `FluentLabel` component out of `CheckboxesWidget`, `ColorWidget`, `RangeWidget` and `UpDownWidget`
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:53]:
```suggestion
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: CHANGELOG.md [hunk 28]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+
+## @rjsf/material-ui
+
+- Fix: MUI radio widget initializes as uncontrolled when schema has no default value, fixing [#3511](https://github.com/rjsf-team/react-jsonschema-form/issues/3511)
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget`, `RangeWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:60]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget`, `RangeWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: CHANGELOG.md [hunk 29]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+
+## @rjsf/mui
+
+- Fix: MUI radio widget initializes as uncontrolled when schema has no default value, fixing [#3511](https://github.com/rjsf-team/react-jsonschema-form/issues/3511)
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget`, `RangeWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:67]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `RadioWidget`, `RangeWidget` and `SelectWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: CHANGELOG.md [hunk 30]
```diff
@@ -21,14 +21,62 @@ should change the heading of the (upcoming) version to include a major version b
...
+
+## @rjsf/semantic-ui
+- 
+- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing #3231
+- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `SelectWidget` and `TextareaWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
+- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing #2791
```
Comment (heath-freenome) [inline CHANGELOG.md:73]:
```suggestion
- Updated `ObjectFieldTemplate` to hide the titles and descriptions when `displayLabel` is true (including globally), fixing [#3231](https://github.com/rjsf-team/react-jsonschema-form/issues/3231)
- Updated `BaseInputTemplate`, `CheckboxesWidget`, `CheckboxWidget`, `SelectWidget` and `TextareaWidget` to hide labels when `hideLabel` is true using the new `labelValue()` helper (including globally)
- Updated `CheckboxWidget` to show the `description` using the `DescriptionFieldTemplate`, fixing [#2791](https://github.com/rjsf-team/react-jsonschema-form/issues/2791)
```

File: packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 31]
```diff
@@ -60,10 +60,11 @@ export default function CheckboxesWidget<
 
   return (
     <>
-      {displayLabel && (
+      {labelValue(
         <FormLabel required={required} htmlFor={id}>
-          {label || schema.title}
-        </FormLabel>
+          {label || undefined}
```
[the remark this answers is not in the document]
Comment (nickgros) [reply packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:65]: Yeah, I feel like trying to capture both cases in a concise way would be difficult. I'm fine with how you did it.

**Review by nickgros — APPROVED** [review]
LGTM! Just a few questions about types

File: packages/utils/src/labelValue.ts [hunk 32]
```diff
@@ -0,0 +1,16 @@
...
+ * as the return value from the function when `hideLabel` is true. Due to the implementation of theme components, it
+ * may be necessary to return something other than `undefined` to cause the theme component to not render a label. Some
+ * themes require may `false` and others may require and empty string.
+ *
+ * @param [label] - The label string or component to render when not hidden
+ * @param [hideLabel] - Flag, if true, will cause the label to be hidden
+ * @param [fallback] - One of 3 values, `undefined` (the default), `false` or an empty string
+ * @returns - `fallback` if `hideLabel` is true, otherwise `label`
+ */
+export function labelValue(label?: string | ReactElement, hideLabel?: boolean, fallback?: ''): undefined | string;
```
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/utils/src/labelValue.ts:13]: Yes, the overload is to remove `boolean` from the return value
