### PR TITLE
Make material-ui and fluent-ui pull TextWidget from the registry; remove registry prop from <div> in TextWidget

### LINKED ISSUE #2512: Customizing @material-ui TextWidget requires me to customize ALL of the TextWidget wrapped widgets
### Prerequisites

- [ x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Unlike the `core` extensions of the `BaseInput` which pull the `BaseInput` component out of the `registry.widgets` object, the ones for `material-ui` instead directly import the `TextWidget` from the source code hierarchy. As a result, because I've created a custom extension of the `TextWidget` I now need to create custom replacements for ALL of the `TextWidget` wrappers (i.e. `EmailWidget`, `PasswordWidget`, etc).

If the `material-ui` implementation were to pull the `TextWidget` from the registry instead of directly importing it, then I would not need to override every subclass.

### Version
`v3.0.2`

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

In all the `TextWidget` wrappers, rather than directly import `TextWidget` from the source hierarchy, instead pull from the `registry.widgets`

- These changes allow all of these `TextWidget` wrappers (like `EmailWidget`, etc...) to immediately use a custom `TextWidget` class
- Added a new `Registry` type in the `core/index.d.ts` file, refactoring it from `FieldProps`, and adding it to `WidgetProps` as well
- Updated all of the `material-ui` and `fluent-ui` widgets to use `TextWidget` from the registry
  - Converted the `material-ui` `PasswordWidget` to simply use `TextWidget` in a manner similar the other `material-ui` wrappers
    - `fluent-ui` simply wraps `TextWidget` and it seemed like doing so here made sense as well
- Updated material-ui `TextWidget` to declare `registry` in the props so it doesn't get collected into the `textFieldProps`
- Needed to updated the snapshots for the `material-ui` tests since `registry` is no longer part of the snapshots
  - The only non-registry change was adding `placeholder=''` to the `PasswordWidget`, since password inputs are allowed to have them in [html 5](https://www.w3schools.com/jsref/prop_password_placeholder.asp) it seems like a small bug fix
- Also needed to update `UpDownWidget.test.tsx` to add a mock `registry`
- Updated `packages/bootstrap-4/test/helpers/createMocks.ts` to add a mock `registry`

fixes #2512 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@epicfaace Here's the PR... let me know what is needed to get it merged

File: packages/material-ui/src/PasswordWidget/PasswordWidget.tsx [hunk 1]
```diff
@@ -1,49 +1,11 @@
...
-      error={rawErrors.length > 0}
-      onFocus={_onFocus}
-      onBlur={_onBlur}
-      onChange={_onChange}
-    />
-  );
+const PasswordWidget = (props: TextWidgetProps) => {
+  const { registry } = props;
+  const { TextWidget } = registry.widgets;
+  return <TextWidget type="password" {...props} />;
```
Comment (epicfaace) [inline packages/material-ui/src/PasswordWidget/PasswordWidget.tsx:8]: Will this render the exact same content as the old PasswordWidget component? Trying to see if this will be a breaking change or not.

Comment (heath-freenome) [reply packages/material-ui/src/PasswordWidget/PasswordWidget.tsx:8]: The snapshot update was to add the registry to the outer div (which seems weird and probably can be removed easily in my PR). The only other thing was adding an empty `placeholder` to the `input`, which honestly might have been a bug with the `PasswordWidget` before.

Comment (heath-freenome) [reply packages/material-ui/src/PasswordWidget/PasswordWidget.tsx:8]: @epicfaace let me know if stripping the `registry` from the outer div (as seen in the snapshots) is considered a breaking change.

Comment (epicfaace) [reply packages/material-ui/src/PasswordWidget/PasswordWidget.tsx:8]: Yeah, I think it should be fine, not considered a breaking change since that doesn't affect how users use the library / any of the look-and-feel at all.

**Review by epicfaace — APPROVED** [review]

**Comment by heath-freenome** [comment]
Yay! Thanks for the approval! I look forward to updating my code to use these changes
