### PR TITLE
fix: prevent duplicate checkbox description rendering across themes 

### LINKED ISSUE #4742: Duplicated description when using ui:widget
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

When using a boolean field with `ui:widget: "checkbox"` specified in the uiSchema, the description text appears duplicated in the rendered form. The description shows up both in its normal location and again below the checkbox input.

### Expected Behavior

The description should only appear once, either in its standard position or in the appropriate location for the checkbox widget, but not duplicated.

### Steps To Reproduce

1. Create a schema with a boolean field
2. Add a uiSchema that specifies `ui:widget: "checkbox"` for that field
3. Add a `ui:description` to the same field in the uiSchema
4. Observe that the description text appears twice

Example: [Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJib29sIjp0cnVlfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IiIsImRlc2NyaXB0aW9uIjoiIiwicmVxdWlyZWQiOltdLCJwcm9wZXJ0aWVzIjp7ImJvb2wiOnsidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0Ijp0cnVlfX19LCJ1aVNjaGVtYSI6eyJib29sIjp7InVpOnRpdGxlIjoiQm9vbGVhbiIsInVpOnJlYWRvbmx5Ijp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6IlRoaXMgaXMgYSBib29sZWFuIiwidWk6d2lkZ2V0IjoiY2hlY2tib3gifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2NvbXBvbmVudFVwZGF0ZVN0cmF0ZWd5IjoiY3VzdG9tRGVlcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJjb25zdEFzRGVmYXVsdHMiOiJhbHdheXMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMiLCJtZXJnZURlZmF1bHRzSW50b0Zvcm1EYXRhIjoidXNlRm9ybURhdGFJZlByZXNlbnQifX0sInZhbGlkYXRvciI6IkFKVjgiLCJzYW1wbGVOYW1lIjoiU2ltcGxlIn0=)

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Suyog241005**
### Reasons for making this change

This PR fixes issue #4742, where checkbox widgets rendered duplicate labels or descriptions across multiple themes (such as AntD, Chakra UI, MUI, and others).
The duplication occurred because both the FieldTemplate and the CheckboxWidget components were responsible for rendering labels and descriptions.

This change ensures that checkbox widgets render their description only once and that FieldTemplate skips redundant rendering for checkbox types.
It improves consistency across themes and avoids confusing duplicate text for users.

Fixes #4742

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by Suyog241005** [comment]
Hi @heath-freenome ,
I’ve opened this PR to fix the duplicated description and label rendering in checkbox widgets across all themes.
I’ve verified the fix in the playground and updated the changelog accordingly.
Please review when you have a chance.
Thanks!

File: packages/core/src/components/widgets/CheckboxWidget.tsx [hunk 1]
```diff
@@ -57,11 +58,13 @@ function CheckboxWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F exte
...
   );
-  const description = options.description ?? schema.description;
 
+  const uiOptions = getUiOptions(uiSchema);
+  const isCheckboxWidget = uiOptions.widget === 'checkbox';
+  const description = isCheckboxWidget ? undefined : (options.description ?? schema.description);
   return (
     <div className={`checkbox ${disabled || readonly ? 'disabled' : ''}`}>
-      {!hideLabel && description && (
+      {!hideLabel && description && !isCheckboxWidget && (
```
Comment (heath-freenome) [inline packages/core/src/components/widgets/CheckboxWidget.tsx]: Since you set `description` to undefined above you don't need this change
```suggestion
      {!hideLabel && description && (
```

File: packages/mantine/src/widgets/CheckboxWidget.tsx [hunk 2]
```diff
@@ -104,7 +100,6 @@ export default function CheckboxWidget<
         onFocus={handleFocus}
         error={rawErrors && rawErrors.length > 0 ? rawErrors.join('\n') : undefined}
         aria-describedby={ariaDescribedByIds(id)}
-        {...themeProps}
```
Comment (heath-freenome) [inline packages/mantine/src/widgets/CheckboxWidget.tsx:107]: How does this fix the issue with `mantine`?

File: packages/mui/src/FieldTemplate/FieldTemplate.tsx [hunk 3]
```diff
@@ -70,7 +73,7 @@ export default function FieldTemplate<
     >
       <FormControl fullWidth={true} error={rawErrors.length ? true : false} required={required}>
         {children}
-        {displayLabel && rawDescription ? (
+        {!isCheckbox && displayLabel && rawDescription ? (
```
Comment (heath-freenome) [inline packages/mui/src/FieldTemplate/FieldTemplate.tsx]: This change keeps things consistent with how the other changes were made
```suggestion
        {displayLabel && !isCheckbox && rawDescription ? (
```

File: packages/primereact/src/FieldTemplate/FieldTemplate.tsx [hunk 4]
```diff
@@ -26,12 +26,13 @@ export default function FieldTemplate<
     return <div style={{ display: 'none' }}>{children}</div>;
   }
 
+  const isCheckbox = uiOptions.widget === 'checkbox';
   return (
     <WrapIfAdditionalTemplate {...props}>
       <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginBottom: '1rem' }}>
-        {displayLabel && <Label id={props.id} text={props.label} required={props.required} />}
+        {displayLabel && !isCheckbox && <Label id={props.id} text={props.label} required={props.required} />}
```
Comment (heath-freenome) [inline packages/primereact/src/FieldTemplate/FieldTemplate.tsx:33]: So, I'm imagining that there were duplicate labels too?

**Comment by heath-freenome** [comment]
@Suyog241005 Your tests are failing... Make sure to run the following commands on your branch:
```
npm install
npm run build
npm run test:update
```

**Comment by Suyog241005** [comment]
Hi @heath-freenome ,
I’ve run the following on my local branch:

npm install
npm run build
npm run test:update

All tests are passing on my end.

image

It’s possible that the CI cache or environment mismatch is causing the failure.
Could you please re-run the CI jobs to confirm?

File: CHANGELOG.md [hunk 5]
```diff
@@ -17,8 +17,43 @@ should change the heading of the (upcoming) version to include a major version b
 -->
 # 6.0.0
```
Comment (heath-freenome) [inline CHANGELOG.md]:
```suggestion
# 6.0.2
```

**Comment by heath-freenome** [comment]
@Suyog241005 you'll need to rebase anyway, which will cause your tests to run again... After the rebase do again what I suggested, since the `package.json` changed recently. You may generate new snapshots.

**Comment by Suyog241005** [comment]
@heath-freenome  I’ve rebased, resolved conflicts, and all required checks have passed. Please review it when you get the chance.

File: CHANGELOG.md (hunk 5 above)
Comment (heath-freenome) [reply CHANGELOG.md]: I need you to move all of these changes in the `CHANGELOG.md` under the `6.0.2` section ABOVE the `6.0.1` section... With only your additions to the sections you have right now. and order the themes alphabetically

**Comment by heath-freenome** [comment]
> @heath-freenome I’ve rebased, resolved conflicts, and all required checks have passed. Please review it when you get the chance.

Can you address the feedback I've left as well. Especially the `CHANGELOG.md`

**Comment by Suyog241005** [comment]
@heath-freenome , I have updated CHANGELOG.md — moved all entries under the 6.0.2 section above 6.0.1 as requested.

File: packages/mantine/src/widgets/CheckboxWidget.tsx (hunk 2 above)
Comment (Suyog241005) [reply packages/mantine/src/widgets/CheckboxWidget.tsx]: In Mantine’s CheckboxWidget, the themeProps object included default label and description fields that were being passed down to the underlying Mantine Checkbox, which already renders them internally. This caused duplicate label/description rendering.

**Comment by heath-freenome** [comment]
@Suyog241005 one last thing, can you update the `formTests.tsx` in the `snapshot-tests` package to add tests with a checkbox having description. You can use the same schema/uiSchema you highlighted in your screen capture. Also, add tests with the same schema, with the uiSchema having `radio` and then `select` widgets. That way we can verify the fix continues to work in the future

**Comment by Suyog241005** [comment]
Hi @heath-freenome , I have added the requested snapshot tests for checkbox with description, radio, and select widgets in formTests.tsx.
Please review when you get a chance and let me know if anything else needs adjustment.

File: packages/snapshot-tests/src/formTests.tsx [hunk 6]
```diff
@@ -355,6 +355,48 @@ export function formTests(Form: ComponentType<FormProps>, customOptions: FormRen
...
+
+    test('checkbox field with description in schema and FieldTemplate', () => {
+      const schema: RJSFSchema = {
+        type: 'boolean',
+        title: 'test',
+        description: 'This is a checkbox description',
+      };
+      const uiSchema: UiSchema = {
+        'ui:widget': 'checkbox',
+        'ui:description': 'This is a field template description',
```
Comment (heath-freenome) [inline packages/snapshot-tests/src/formTests.tsx]: You probably don't need this unless you are testing the UI schema override of the description, which I don't believe you are. Removing this will require an update to the snapshots
```suggestion
```

File: packages/snapshot-tests/src/formTests.tsx [hunk 7]
```diff
@@ -355,6 +355,48 @@ export function formTests(Form: ComponentType<FormProps>, customOptions: FormRen
...
+
+    test('radio widget with description in schema and FieldTemplate', () => {
+      const schema: RJSFSchema = {
+        type: 'boolean',
+        title: 'test',
+        description: 'This is a radio description',
+      };
+      const uiSchema: UiSchema = {
+        'ui:widget': 'radio',
+        'ui:description': 'This is a field template description',
```
Comment (heath-freenome) [inline packages/snapshot-tests/src/formTests.tsx]: You probably don't need this unless you are testing the UI schema override of the description, which I don't believe you are. Removing this will require an update to the snapshots
```suggestion
```

File: packages/snapshot-tests/src/formTests.tsx [hunk 8]
```diff
@@ -355,6 +355,48 @@ export function formTests(Form: ComponentType<FormProps>, customOptions: FormRen
...
+
+    test('select widget with description in schema and FieldTemplate', () => {
+      const schema: RJSFSchema = {
+        type: 'boolean',
+        title: 'test',
+        description: 'This is a select description',
+      };
+      const uiSchema: UiSchema = {
+        'ui:widget': 'select',
+        'ui:description': 'This is a field template description',
```
Comment (heath-freenome) [inline packages/snapshot-tests/src/formTests.tsx]: You probably don't need this unless you are testing the UI schema override of the description, which I don't believe you are. Removing this will require an update to the snapshots
```suggestion
```

**Comment by heath-freenome** [comment]
@Suyog241005 One small set of changes to the tests, a rebase and then I will approve/merge

**Comment by Suyog241005** [comment]
@heath-freenome  I've made the requested test changes, updated all snapshots, and I've also done a git rebase to ensure everything is in sync. The PR is ready for your review.
