### PR TITLE
Bug : Fields inside an array can't be set to empty when default is set.

### LINKED ISSUE #4456: Fields data inside an array can't be set to empty when a default is set.
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.24.1

### Current Behavior

Field data inside an array can't be set to empty when a default value is set and **`mergeDefaultsIntoFormData`** is set to `'useFormDataIfPresent'`. This issue only occurs when the field is directly an item of the array field. In any other cases field data can be set to an empty value.

### Expected Behavior

Fields data inside an array can be set to empty when a default is set.

### Steps To Reproduce

1. Click [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhcnJheVdpdGhEZWZhdWx0cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn0sImRlZmF1bHQiOlsiSGVsbG8gV29ybGQiXX0sIm9iamVjdFdpZHRoRGVmYXVsdHMiOnsicHJvcGVydGllcyI6eyJuZXN0ZWRGaWVsZCI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkhlbGxvIFdvcmxkISJ9fX0sInN0cmluZ0ZpZWxkIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiSGVsbG8gV29ybGQhISJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImFsbE9mIjoic2tpcERlZmF1bHRzIiwiY29uc3RBc0RlZmF1bHRzIjoiYWx3YXlzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIiwibWVyZ2VEZWZhdWx0c0ludG9Gb3JtRGF0YSI6InVzZUZvcm1EYXRhSWZQcmVzZW50In19LCJ2YWxpZGF0b3IiOiJBSlY4In0=) to open the demo 
2. Try to clear the arrayWithDefaults-1 field and you'll notice that it's not possible. 
3. Try to clear nestedField or stringField and you'll notice that it is working properly.

### Environment

```markdown
- OS:macos
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abdalla-rko**
### Reasons for making this change

Fixes #4456 

### Checklist

- [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

File: packages/utils/src/mergeDefaultsWithFormData.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default function mergeDefaultsWithFormData<T = any>(
     const overrideOppositeArray = overrideFormDataWithDefaults ? formData : defaultsArray;
 
     const mapped = overrideArray.map((value, idx) => {
-      if (overrideOppositeArray[idx]) {
+      if (typeof overrideOppositeArray[idx] !== 'undefined') {
```
Comment (heath-freenome) [inline packages/utils/src/mergeDefaultsWithFormData.ts:44]:
```suggestion
     // We want to explicitly make sure that the value is NOT undefined since null, 0 and empty space are valid values
      if (overrideOppositeArray[idx] !== undefined) {
```

**Review by heath-freenome — APPROVED** [review]

File: packages/utils/src/mergeDefaultsWithFormData.ts [hunk 2]
```diff
@@ -41,7 +41,8 @@ export default function mergeDefaultsWithFormData<T = any>(
     const overrideOppositeArray = overrideFormDataWithDefaults ? formData : defaultsArray;
 
     const mapped = overrideArray.map((value, idx) => {
-      if (overrideOppositeArray[idx]) {
+     // We want to explicitly make sure that the value is NOT undefined since null, 0 and empty space are valid values
```
Comment (heath-freenome) [inline packages/utils/src/mergeDefaultsWithFormData.ts:44]:
```suggestion
      // We want to explicitly make sure that the value is NOT undefined since null, 0 and empty space are valid values
```
