### PR TITLE
Fix 4081 and 4684: Implement a new feature and a small bug fix

### LINKED ISSUE #4081: Consider adding omit extra data functionality to schemaUtils
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hello,

Due to the advanced way in which we use RJSF, we need to programmatically omit extra data. We have implemented our own step functionality on top of RJSF, and we need to filter out extra data without submitting the form when switching between steps, as `liveOmit` is hitting our performance requirements.

Temporarily, we have created a custom function that mimics the logic from [here](https://github.com/rjsf-team/react-jsonschema-form/blob/0782878084602c4dd8e7a6e362bc0af003eef98a/packages/core/src/components/Form.tsx#L577) and [here](https://github.com/rjsf-team/react-jsonschema-form/blob/0782878084602c4dd8e7a6e362bc0af003eef98a/packages/core/src/components/Form.tsx#L689):
```
function omitData(schema: RJSFSchema, formData: RJSFSchema) {
  // rjsfValidator and defaultFormStateBehavior are shared consts
  const schemaUtils = createSchemaUtils(rjsfValidator, schema, defaultFormStateBehavior)
  const formInstance = new Form({ schema, validator: rjsfValidator })

  const retrievedSchema = schemaUtils.retrieveSchema(schema, formData)
  const pathSchema = schemaUtils.toPathSchema(retrievedSchema, '', formData)
  const fieldNames = formInstance.getFieldNames(pathSchema, formData)

  return formInstance.getUsedFormData(formData, fieldNames)
}
```

Using new Form in this manner is entirely possible, as neither `getFieldNames` nor `getUsedFormData` access `this`. However, it is clear that this is not the best long-term solution. The extraction could be beneficial for other users and would help to avoid duplicating the same logic if it were centralized. Would `schemaUtils` be an appropriate place for this? A similar function, `getDefaultFormState`, already exists there.

I propose the following:

1. Move [getFieldNames](https://github.com/rjsf-team/react-jsonschema-form/blob/0782878084602c4dd8e7a6e362bc0af003eef98a/packages/core/src/components/Form.tsx#L520) and [getUsedFormData](https://github.com/rjsf-team/react-jsonschema-form/blob/0782878084602c4dd8e7a6e362bc0af003eef98a/packages/core/src/components/Form.tsx#L500) to a separate context, as they are used exclusively by the omit logic.
2. Move the omit logic in both locations to `schemaUtils.omitExtraData` and replace its usage in the `Form`.
3. Update the tests accordingly.

I can work on this if you give me the green light to proceed.

Thanks!

### LINKED ISSUE #4684: Add nested object has full-height and full-width button
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

react-bootstrap

### Version

6.0.0-beta11

### Current Behavior

With 6.0.0-beta11 an d react-bootstrap i have a problem with remove button (and add button) sizes.

I created a schema which contains nested objects. The delete buttons are huge, they seem to fill 100% of the space they are in. I played around in the developer toolbar in safari. when i remove d-grid in one of the parent divs the button is smaller, but it is still mis-aligned.

Mis alignment is another issue, as you can see in the screenshots. But I found another bug report for that (although that was on version 5).

Image

I also tried it with an array of nested objects, that seems to be alright, except for the add button. That one is full width as well.

Image

I played around with some css, the ArrayTemplate and such. I am not a frontend developer however, the more I fiddle with it, the worse it gets. So I removed all my customizations. 

I have no extra stylesheets loaded whatsoever.

With the default theme it seems to be better.

Image

### Expected Behavior

I expect the button to be not full size, but something more reasonable. 

### Steps To Reproduce

I want to create a link to the playground with my examples, but there is not an easy way to share that. 

Just load these examples: 

Object with nested object example
[deployment.json](https://github.com/user-attachments/files/21156232/deployment.json)
[deployment.schema.json](https://github.com/user-attachments/files/21156233/deployment.schema.json)

Array with objects example
[user.json](https://github.com/user-attachments/files/21156381/user.json)
[user.schema.json](https://github.com/user-attachments/files/21156380/user.schema.json)

This is my package.json
[package.json](https://github.com/user-attachments/files/21156256/package.json)

### Environment

```markdown
- OS: MacOS Sequoia
- Node:v23.6.1
- npm: 10.9.2
- Browser: Safari 18.5 / Chrome 138.0.7204.93
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #4081 by refactoring `omitExtraData()` into `schemaUtils`
Fixes #4684 by adding a `maxHeight` to the `@rjsf/react-bootstrap` `WrapIfAdditionalTemplate` for the `RemoveButton` column
- Updated `LICENSE.md` to update copyright date
- In `@rjsf/utils` refactored the `omitExtraData()` function and its helpers from `Form` into a new `schema/omitExtraData.ts`
  - Updated `types.ts` to add the `omitExtraData()` function to `SchemaUtilsType`
  - Updated `createSchemaUtils()` to implement the `omitExtraData()` function
  - Added `omitExtraDataTest.ts` to provide 100% unit test converage, exporting it from the `schema/index.ts`
  - Added the `omitExtraDataTest()` call in the `schema.test.ts`
- In `@rjsf/core`, removed the `omitExtraData()` tests from `Form.test.tsx`
- Updated the `utility-functions.md` file to document the `omitExtraData()` function
- Updated the `CHANGELOG.md` file

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

## Before

Screenshot 2026-01-11 at 2 32 14 PM

## After

Screenshot 2026-01-11 at 2 28 43 PM

### CODE REVIEW

**Comment by x0k** [comment]
For my project, I wrote the [omitExtraData](https://github.com/x0k/svelte-jsonschema-form/blob/ae6d2c5b0379e1e403c9b3680fe49ff2427c5673/packages/form/src/omit-extra-data.ts) function from scratch and generated [tests](https://github.com/x0k/svelte-jsonschema-form/blob/ae6d2c5b0379e1e403c9b3680fe49ff2427c5673/packages/form/src/omit-extra-data.test.ts) for it.
Feel free to use it if you find it useful.

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -766,79 +762,14 @@ export default class Form<
     return { ...mergedErrors, schemaValidationErrors, schemaValidationErrorSchema };
   }
 
-  /** Returns the `formData` with only the elements specified in the `fields` list
-   *
-   * @param formData - The data for the `Form`
-   * @param fields - The fields to keep while filtering
-   */
-  getUsedFormData = (formData: T | undefined, fields: string[]): T | undefined => {
```
Comment (nickgros) [inline packages/core/src/components/Form.tsx:774]: Technically a breaking API change to remove `formInstance.getUsedFormData` and `getFieldNames`. Do you think these are safe to remove?

**Review by nickgros — APPROVED** [review]

File: packages/core/src/components/Form.tsx (hunk 1 above)
Comment (heath-freenome) [reply packages/core/src/components/Form.tsx:774]: Hmmm, I can always forward them to utils I suppose...
