### PR TITLE
fix: Implement precompiled validator support in @rjsf/validator-ajv8

### LINKED ISSUE #3543: Content Security Policy (CSP) reporting unsafe eval usage  inside Chrome Extension V3
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

Same as [https://github.com/rjsf-team/react-jsonschema-form/issues/1121](https://github.com/rjsf-team/react-jsonschema-form/issues/1121)

I completely blocked because I'm developing a Chrome Extension that doesn't allow CSP, any chance to precompile schema?

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #3543 by implementing support for precompiled validators
- In `@rjsf/validator-ajv8` added support for precompiled validators as follows:
  - Added a new `compileSchemaValidators()` API function used to generate the precompiled validators for a schema to an output file
  - Updated the documentation for the `customizeValidator()` API function
  - Added a new `AJV8PrecompiledValidator` implementation of the `ValidatorType` interface
  - Refactored a large piece of the raw validation error processing from the `AJV8Validator` into a new `processRawValidationErrors()` function also used by the `AJV8PrecompiledValidator`
  - Added a new `usePrecompiledValidator()` API function that is similar to `customizeValidator()` but returning a precompiled validator-based `ValidatorType` interface implementation
  - Added some new types to the `types.ts` file in support of precompiled validators
  - Updated the main `index.ts` file to export the new types and API functions
  - Added 100% unit test coverage of the new feature
    - This included implementing a node function to precompile the `superSchema.json` file found in the `test/harness` directory
- Updated the `validation.md` documentation for the new precompiled validator functionality
- Added a new `validator-ajv8.md` documentation file to the `api-reference` directory and the `sidebar.js`
- Updated the `CHANGELOG.md` file accordingly

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/validator-ajv8/src/compileSchemaValidators.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  schema: S,
+  output: string,
+  options: CustomValidatorOptionsType = {}
+) {
+  console.log('parsing the schema');
+  const schemaMaps = schemaParser(schema);
+  const schemas = Object.values(schemaMaps);
+
+  const { additionalMetaSchemas, customFormats, ajvOptionsOverrides = {}, ajvFormatOptions, AjvClass } = options;
+  const compileOptions = { ...ajvOptionsOverrides, code: { source: true, lines: true }, schemas };
```
Comment (heath-freenome) [inline packages/validator-ajv8/src/compileSchemaValidators.ts:29]:
```suggestion
  // Allow users to turn off the `lines: true` feature in their own overrides, but NOT the `source: true`
  const compileOptions = { ...ajvOptionsOverrides, code: { lines: true, ...ajvOptionsOverrides.code, source: true }, schemas };
```

File: packages/validator-ajv8/src/precompiledValidator.ts [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+    }
+    const errors = this.mainValidator.errors || undefined;
+
+    // Clear errors to prevent persistent errors, see #1104
+    this.mainValidator.errors = null;
+
+    return {
+      errors: errors as unknown as Result[],
+      validationError,
+    };
```
Comment (heath-freenome) [inline packages/validator-ajv8/src/precompiledValidator.ts:122]:
```suggestion
    return { errors: errors as unknown as Result[] };
```

File: packages/validator-ajv8/test/precompiledValidator.test.ts [hunk 3]
```diff
@@ -0,0 +1,365 @@
...
+            expect(errors).toHaveLength(1);
+            expect(errors[0].stack).toEqual("must have required property 'pass2'");
+          });
+          it('should return an errorSchema', () => {
+            expect(errorSchema.passwords!.pass2!.__errors).toHaveLength(1);
+            expect(errorSchema.passwords!.pass2!.__errors![0]).toEqual("must have required property 'pass2'");
+          });
+        });
+      });
+      describe('No custom validate function, single additionalProperties value', () => {
```
Comment (heath-freenome) [inline packages/validator-ajv8/test/precompiledValidator.test.ts:188]: Consider adding a positive test as well

File: packages/validator-ajv8/test/precompiledValidator.test.ts [hunk 4]
```diff
@@ -0,0 +1,365 @@
...
+          });
+          it('should return an errorSchema', () => {
+            expect(errorSchema.passwords!.pass2!.__errors).toHaveLength(2);
+            expect(errorSchema.passwords!.pass2!.__errors![0]).toEqual("must have required property 'pass2'");
+            expect(errorSchema.passwords!.pass2!.__errors![1]).toEqual('passwords don`t match.');
+          });
+        });
+      });
+      describe('Data-Url validation', () => {
+        it('Data-Url with name is accepted', () => {
```
Comment (heath-freenome) [inline packages/validator-ajv8/test/precompiledValidator.test.ts:288]: Add negative test

**Comment by nickgros** [comment]
Just leaving a note to cross-reference with #1961 and follow-up later...while this isn't a silver bullet for that issue, I'm curious to see how much better the pre-compiled validator performs when using schemas with high conditional complexity.

File: packages/validator-ajv8/src/precompiledValidator.ts [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+  }
+
+  /** Returns the precompiled validator associated with the given `schema` from the map of precompiled validator
+   * functions.
+   *
+   * @param schema - The schema for which a precompiled validator function is desired
+   * @returns - The precompiled validator function associated with this schema
+   */
+  getValidator(schema: S) {
+    const key = get(schema, ID_KEY, hashForSchema(schema));
```
Comment (nickgros) [inline packages/validator-ajv8/src/precompiledValidator.ts:76]: We shouldn't need to compute the hash if we have an `$id`. This is not a big deal if the hash is not an expensive computation.

File: packages/docs/docs/api-reference/validator-ajv8.md [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+The main reasons for using a precompiled validator is reducing code size, improving validation speed and, most importantly, avoiding dynamic code compilation when prohibited by a browser's Content Security Policy.
+For more information about AJV code compilation see: https://ajv.js.org/standalone.html
+
+#### Parameters
+
+- schema: S - The schema to be compiled into a set of precompiled validators functions
+- output: string - The name of the file into which the precompiled validator functions will be generated
+- [options={}]: CustomValidatorOptionsType - The set of `CustomValidatorOptionsType` information used to alter the AJV validator used for compiling the schema. They are the same options that are passed to the `customizeValidator()` function in order to modify the behavior of the regular AJV-based validator.
+
+### usePrecompiledValidator<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any>()
```
Comment (nickgros) [inline packages/docs/docs/api-reference/validator-ajv8.md:42]: `use...` makes this look like a React hook, so I would suggest a slightly different name, like

```suggestion
### createPrecompiledValidator<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any>()
```

File: packages/validator-ajv8/src/types.ts [hunk 7]
```diff
@@ -21,3 +22,17 @@ export interface CustomValidatorOptionsType {
...
+
+/** Extend ValidateFunction to Omit its two required properties, `schema` and `schemaEnv` that are not produced by the
+ * AJV schema standalone compilation code
+ */
+export interface CompiledValidateFunction<T = any> extends Omit<ValidateFunction<T>, 'schema' | 'schemaEnv'> {
+  /** This is literally copied from the `ValidateFunction` type definition from which it extends because it seems to get
+   * lost as part of the Omit<>.
+   */
+  (this: Ajv | any, data: any, dataCxt?: DataValidationCxt): boolean;
+}
```
Comment (nickgros) [inline packages/validator-ajv8/src/types.ts:34]: Tbh I don't really know how a function definition is supposed to work with `Omit`, but it makes sense to do this, since it also has properties you want to drop.

File: packages/validator-ajv8/src/usePrecompiledValidator.ts [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+ *
+ * NOTE: The `validateFns` parameter is an object obtained by importing from a precompiled validation file created via
+ * the `compileSchemaValidators()` function.
+ *
+ * @param validateFns - The map of the validation functions that are created by the `compileSchemaValidators()` function
+ * @param rootSchema - The root schema that was used with the `compileSchemaValidators()` function
+ * @param [localizer] - If provided, is used to localize a list of Ajv `ErrorObject`s
+ * @returns - The precompiled validator implementation resulting from the set of parameters provided
+ */
+export default function usePrecompiledValidator<
```
Comment (nickgros) [inline packages/validator-ajv8/src/usePrecompiledValidator.ts:17]: As mentioned before, prefer a different name so this doesn't look like a React hook.

File: packages/validator-ajv8/test/harness/compileTestSchema.js [hunk 9]
```diff
@@ -0,0 +1,27 @@
+/**
+ * In order to keep things in sync, it may be necessary to run this after making changes in the schemaParser world in
+ * `@rjsf/utils` OR if an AJV update is installed. To run this, simply do the following, starting in the root directory
+ * of the `@rjsf/validator-ajv8` directory:
+ *
+ * - cd test/harness
+ * - node compileTestSchema.js
+ *
+ * Then add the two updated `superSchema.js` and `superSchemaOptions.js` files to your PR
```
Comment (nickgros) [inline packages/validator-ajv8/test/harness/compileTestSchema.js:9]: Hmm...we'd have no idea if something breaks unless we're disciplined about following these steps. Is it burdensome to just run this file and recompile the validators before we run the tests?

Comment (nickgros) [reply packages/validator-ajv8/test/harness/compileTestSchema.js:9]: And if so, we can .gitignore the compiled files, of course

File: packages/validator-ajv8/test/harness/compileTestSchema.js [hunk 10]
```diff
@@ -0,0 +1,27 @@
...
+ */
+
+const compileSchemaValidators = require('../../dist').compileSchemaValidators;
+const superSchema = require('./superSchema.json');
+
+// NOTE these are the same as the CUSTOM_OPTIONS in `testData.ts`, keep them in sync
```
Comment (nickgros) [inline packages/validator-ajv8/test/harness/compileTestSchema.js:15]: Why can't we just import this from `testData`?

File: packages/validator-ajv8/test/precompiledValidator.test.ts
Comment (nickgros) [inline packages/validator-ajv8/test/precompiledValidator.test.ts:1]: Fantastic set of tests

File: packages/validator-ajv8/test/usePrecompiledValidator.test.ts [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+};
+
+const validateFns = superSchemaFns as ValidatorFunctions;
+const rootSchema = superSchema as RJSFSchema;
+
+describe('usePrecompiledValidator()', () => {
+  describe('passing validatorFns and rootSchema to usePrecompiledValidator', () => {
+    let custom: any;
+    beforeAll(() => {
+      (AJV8PrecompiledValidator as unknown as jest.Mock).mockClear();
```
Comment (nickgros) [inline packages/validator-ajv8/test/usePrecompiledValidator.test.ts:23]: You can probably use `jest.mocked()` instead of this sequence of casts - https://jestjs.io/docs/mock-function-api/#jestmockedsource-options

File: packages/validator-ajv8/test/validator.test.ts [hunk 12]
```diff
@@ -32,10 +25,10 @@ describe('AJV8Validator', () => {
     builder.resetAllErrors();
   });
   describe('default options', () => {
-    // Use the TestValidator to access the `withIdRefPrefix` function
-    let validator: TestValidator;
+    // Use the AJV8Validator to access the `withIdRefPrefix` function
```
Comment (nickgros) [inline packages/validator-ajv8/test/validator.test.ts:28]: Does it make sense to remove this comment (and the other 3 times it appears in this file)? Seems like the refactor made this easy to clean up and we're not even accessing `withIdRefPrefix` in this file
```suggestion
```

File: packages/validator-ajv8/test/harness/compileTestSchema.js (hunk 10 above)
Comment (heath-freenome) [reply packages/validator-ajv8/test/harness/compileTestSchema.js:15]: The TS file is using imports for types which don't work in a CJS world that this file is running in.

File: packages/validator-ajv8/test/validator.test.ts (hunk 12 above)
Comment (heath-freenome) [reply packages/validator-ajv8/test/validator.test.ts:28]: Good catch!

File: packages/validator-ajv8/test/harness/compileTestSchema.js (hunk 10 above)
Comment (nickgros) [reply packages/validator-ajv8/test/harness/compileTestSchema.js:15]: Gotcha, so this is easier than using ts-node or something like that. That's fine.

File: packages/validator-ajv8/test/usePrecompiledValidator.test.ts (hunk 11 above)
Comment (heath-freenome) [reply packages/validator-ajv8/test/usePrecompiledValidator.test.ts:23]: Wow, I just learned something new

File: packages/validator-ajv8/test/harness/compileTestSchema.js (hunk 9 above)
Comment (heath-freenome) [reply packages/validator-ajv8/test/harness/compileTestSchema.js:9]: Hmmm, good idea, let me see how that goes

**Review by nickgros — APPROVED** [review]
Looks great! Excited to see this released!

File: packages/validator-ajv8/test/usePrecompiledValidator.test.ts (hunk 11 above)
Comment (nickgros) [reply packages/validator-ajv8/test/usePrecompiledValidator.test.ts]: I just learned about it recently 🙂
