### PR TITLE
fix: Fixed #3744 and another precompiled schema issue

### LINKED ISSUE #3744: Odd behaviour of anyOf/oneOf <title>
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

We are treating anyOf/oneOf incorrectly right now their subschemas should merge with the schema where they are defined based on selection.

### Expected Behavior

Have a consistent behavior of anyOf/oneOf like we have for allOf.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #3744 as well as an issue associated with anyOf/oneOf in precompiled schema
- In `@rjsf/util`, fixed part of #3744 and the precompiled schema issue as follows:
  - Updated `getClosestMatchingOption()` to resolve refs in the options before computing the correct index, as well as supporting `anyOf` and discriminators in `calculateIndexScore()`
  - Updated `getDefaultFormState()` to merge in the remaining schema into the selected anyOf/oneOf option prior to computing new defaults
  - Updated `retrieveSchema()` to merge in the remaining schema into the anyOf/oneOf options when resolving dependencies
  - Added/updated tests to verify all the fixes
- In `@rjsf/core`, fixed the rest of #3744 by updating `MultiSchemaField` to merge the remaining schema into the selected anyOf/oneOf selected option
  - Also updated `SchemaField` to no longer pass in `baseType` to `MultiSchemaField` since it is no longer used
### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/test/schema/getClosestMatchingOptionTest.ts [hunk 1]
```diff
@@ -167,6 +167,52 @@ export default function getClosestMatchingOptionTest(testValidator: TestValidato
...
+              required: ['ipsum'],
+            },
+          ],
+        },
+      };
+      const formData = { ipsum: { night: 'nicht' } };
+      // Mock to return true for the last of the second one-ofs
+      testValidator.setReturnValues({
+        isValid: [false, false, false, false, false, false, false, true],
+      });
```
Comment (nickgros) [inline packages/utils/test/schema/getClosestMatchingOptionTest.ts:213]: Wondering if in some places it might be more readable/maintainable if we stubbed the implementation to return `isValid` for a specific subschema (in this case the second anyOf) instead of relying on ordering.

File: packages/utils/test/schema/getClosestMatchingOptionTest.ts [hunk 2]
```diff
@@ -167,6 +167,52 @@ export default function getClosestMatchingOptionTest(testValidator: TestValidato
...
+                  ],
+                },
+              },
+              required: ['ipsum'],
+            },
+          ],
+        },
+      };
+      const formData = { ipsum: { night: 'nicht' } };
+      // Mock to return true for the last of the second one-ofs
```
Comment (nickgros) [inline packages/utils/test/schema/getClosestMatchingOptionTest.ts:210]:
```suggestion
      // Mock to return true for the last of the second anyOfs
```

**Review by nickgros — APPROVED** [review]

File: packages/utils/test/schema/getClosestMatchingOptionTest.ts (hunk 1 above)
Comment (heath-freenome) [reply packages/utils/test/schema/getClosestMatchingOptionTest.ts:213]: Most likely... What were you thinking of changing?
