### PR TITLE
Pass oneOf / anyOf subschemas to altSchema optionsList

### LINKED ISSUE #2147: Allow  extra properties on enumOptions
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Enum options, from an anyOf schema populate a label and value, but other properties, like description are not preserved. For situations with checkbox/radio selects, descriptions might be useful for either a tooltip with a custom widget, or for extra description about an option

### Steps to Reproduce

1. Make a schema like

```js
schema: {
  type: 'string',
  anyOf: [
    { title: 'Title1', const: 'value1', description: 'a description 1' }, 
    { title: 'Title2', const: 'value2', description: 'a description 2' },
  ]
}

uiSchema: {
  'ui:widget': 'radio'
}
```

#### Expected behavior

Descriptions should be carried through to the widget

#### Actual behavior

in the widge

```
const { enumOptions } = options
=> [
    { label: 'Title1', value: 'value1' }, 
    { label: 'Title2', value: 'value2' },
  ]
```

this looks to be from 

```
export function optionsList(schema) {
  if (schema.enum) {
    return schema.enum.map((value, i) => {
      const label = (schema.enumNames && schema.enumNames[i]) || String(value);
      return { label, value };
    });
  } else {
    const altSchemas = schema.oneOf || schema.anyOf;
    return altSchemas.map((schema, i) => {
      const value = toConstant(schema);
      const label = schema.title || String(value);
      return { label, value };
    });
  }
}
```

which maps the altSchemas, and only maintains the value and labels, without other properties on th schemas.  I'm not sure what other properties might make sense, but at least description seems possibly warranted here.  Happy to make a PR for that that change, or one that spread the altSchema as well?

### Version 2.4.0

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

### PR DESCRIPTION
**Pull request by mattcosta7**
fix #2147

### Reasons for making this change

To pass an optional description through to the enum options

If this is related to existing tickets, include links to them as well.

### Checklist

* [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by mattcosta7** [comment]
Anything necessary to move this along?

Looks like the checks here are just deployment steps?

**Review by epicfaace — COMMENTED** [review]
Thanks for the PR -- would you be able to add a test to ensure this functionality doesn't regress in the future?

**Comment by mattcosta7** [comment]
@epicfaace tests for optionsList added, let me know if there's anything else!

**Comment by mattcosta7** [comment]
Just a friendly ping to see if there's anything else I can do to move this along? @epicfaace

File: packages/core/test/utils_test.js [hunk 1]
```diff
@@ -3763,4 +3764,68 @@ describe("utils", () => {
...
+        enumSchema.enum.map(opt => ({ label: opt, value: opt }))
+      );
+      expect(optionsList(enumNameSchema)).eql(
+        enumNameSchema.enum.map((opt, index) => {
+          const label = enumNameSchema.enumNames[index] || opt;
+          return { label: label, value: opt };
+        })
+      );
+    });
+    it("shoulld generate options for a oneOf|anyOf schema", () => {
```
Comment (epicfaace) [inline packages/core/test/utils_test.js:3789]:
```suggestion
    it("should generate options for a oneOf|anyOf schema", () => {
```

**Review by epicfaace — COMMENTED** [review]
Looks good. A few questions:
- I see that you suggested passing the entire altSchema instead of just `description` in the issue. I think this makes sense; could you make that change in this PR too?
- Can you also update the documentation to discuss the `enumOptions` property in more detail, along with this change? Currently we have some outdated description in the docs and a reference to v0.35.0 (which can probably be removed): https://github.com/rjsf-team/react-jsonschema-form/blob/bf6c99862afe9b381c9be4027ad97adbeabc1bd5/docs/advanced-customization/custom-widgets-fields.md#L2

File: packages/core/test/utils_test.js (hunk 1 above)
Comment (mattcosta7) [reply packages/core/test/utils_test.js]: fixed this typo

File: packages/core/src/utils.js [hunk 2]
```diff
@@ -573,7 +573,11 @@ export function optionsList(schema) {
     return altSchemas.map((schema, i) => {
       const value = toConstant(schema);
       const label = schema.title || String(value);
-      return { label, value };
+      return {
+        ...schema,
```
Comment (mattcosta7) [inline packages/core/src/utils.js:577]: spread optionsList

File: packages/core/index.d.ts [hunk 3]
```diff
@@ -347,7 +347,10 @@ declare module '@rjsf/core' {
 
         export function allowAdditionalItems(schema: JSONSchema7): boolean;
 
-        export function optionsList(schema: JSONSchema7): { label: string; value: string }[];
+        export function optionsList(schema: JSONSchema7): (Partial<JSONSchema7Definition> & {
+            label: string;
+            value: string;
+        })[];
```
Comment (mattcosta7) [inline packages/core/index.d.ts:353]: added the Partial<JSONSchema7Definition
> here to ensure the types show other properties may be optionally passed here, but label and value are guaranteed

**Comment by mattcosta7** [comment]
@epicfaace updated with the requested changes, thansk!

File: docs/advanced-customization/custom-widgets-fields.md [hunk 4]
```diff
@@ -133,11 +133,10 @@ The following props are passed to custom widget components:
 - `onBlur`: The input blur event handler; call it with the the widget id and value;
 - `onFocus`: The input focus event handler; call it with the the widget id and value;
 - `options`: A map of options passed as a prop to the component (see [Custom widget options](#custom-widget-options)).
+- `options.enumOptions`: For enum fields, this property contains the list of options for the enum as an array of { label, value } objects. If the enum is defined using the oneOf/anyOf syntax, the entire schema object is spread onto the { ...schema.\[anyOf|oneOf\], label, value } object.
```
Comment (epicfaace) [inline docs/advanced-customization/custom-widgets-fields.md:136]:
```suggestion
- `options.enumOptions`: For enum fields, this property contains the list of options for the enum as an array of { label, value } objects. If the enum is defined using the oneOf/anyOf syntax, the entire schema object for each option is spread onto the { ...schema.\[anyOf|oneOf\], label, value } object.
```

File: docs/advanced-customization/custom-widgets-fields.md [hunk 5]
```diff
@@ -133,11 +133,10 @@ The following props are passed to custom widget components:
 - `onBlur`: The input blur event handler; call it with the the widget id and value;
 - `onFocus`: The input focus event handler; call it with the the widget id and value;
 - `options`: A map of options passed as a prop to the component (see [Custom widget options](#custom-widget-options)).
+- `options.enumOptions`: For enum fields, this property contains the list of options for the enum as an array of { label, value } objects. If the enum is defined using the oneOf/anyOf syntax, the entire schema object for each option is spread onto the { ...schema.\[anyOf|oneOf\], label, value } object.
```
Comment (epicfaace) [inline docs/advanced-customization/custom-widgets-fields.md]: We should clarify that the schema is included regardless of whether it's defined using the oneOf/anyOf syntax.

File: packages/core/src/utils.js (hunk 2 above)
Comment (epicfaace) [inline packages/core/src/utils.js:577]: Actually, I was just thinking it might be better to actually explicitly include the schema in a `schema` keyword. I know that `label` and `value` currently aren't reserved keywords in JSON Schema, but this way, we can prevent further conflicts in case it happens in the future, and don't have to worry about `label` and `value` potentially overriding something within the schema. What do you think?

```suggestion
        schema,
```

File: docs/advanced-customization/custom-widgets-fields.md (hunk 5 above)
Comment (mattcosta7) [reply docs/advanced-customization/custom-widgets-fields.md]: When an enum is declared like

```
{ type: string, enum: [one, two, three] }
```

the options list currently doesn't have a schema defined, they are instead just { label, value } objects, where enumNames might override the label.   

only in cases where not using they enum key would the schema be added.  I think those 2 cases are oneOf/anyOf?   are there other times that's valid?

File: packages/core/src/utils.js (hunk 2 above)
Comment (mattcosta7) [reply packages/core/src/utils.js]: agreed here, this makes sense to me, pushed a commit with this change made

File: docs/advanced-customization/custom-widgets-fields.md (hunk 5 above)
Comment (mattcosta7) [reply docs/advanced-customization/custom-widgets-fields.md]: Maybe something along the lines of 

For enum fields defined using the enum property, this contains a list of options as an array of { label, value } objects.  For other enums, such as those defined with an anyOf or oneOf schema, this contains a list of options as an array of { schema, label, value } objects, where the schema is the schema defining each enum option individually

Comment (mattcosta7) [reply docs/advanced-customization/custom-widgets-fields.md]: On the other hand, we could also pass the base schema for the 

```
{ type: string, enum: [one, two, three] }
```

to the options themselves too, so this might generate

```
{
   schema: { type: string, enum: [one, two, three] },
   label: one,
   value: one
} 
```

for these items as well.  This might make sense since the enum options each inherit that schema?

Comment (mattcosta7) [reply docs/advanced-customization/custom-widgets-fields.md]: actually, nevermind that, I think it might cause more complexity than it would aim to solve, 

for instance, a 'description' on the parent schema would then automatically apply to the child enums, when it should not - so probably better to avoid adding the schema, or only copy specific schema properties in that case (ie, just type and _maybe_ format, but no others?)

Comment (epicfaace) [reply docs/advanced-customization/custom-widgets-fields.md]: Yeah, let's just not pass the base schema for simple (non-oneOf/anyOf enums) instead.

**Review by epicfaace — APPROVED** [review]
