### PR TITLE
Use require for every mui component and streamline context usage

### LINKED ISSUE #2748: @rjsf/material-ui breaks tree shaking
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Importing `@rjsf/material-ui` into a project bundled with [esbuild]() causes bundle size to increase a lot.

This seems to be because of https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/Theme5/Mui5Context.tsx#L11, which causes the entire `@mui/icons-material` package to be included in the bundle.

Bundle size with `@rjsf/material-ui` included: 6,9M
Bundle size without `@rjsf/material-ui`: 2,4M

### Steps to Reproduce

1. Include `@rjsf/material-ui` in a project
2. Bundle it using a tree-shaking enabled bundler (like esbuild)
3. Compare bundle sizes before and after `@rjsf/material-ui` inclusion

#### Expected behavior

The icons should be tree-shaken and only icons used by the application should be included in the bundle.

#### Actual behavior

All icons from the `@mui/icons-material` package are included in the bundle.

### Version

```
        "@rjsf/core": "^4.0.1",
        "@rjsf/material-ui": "^4.0.1",
```

### PR DESCRIPTION
**Pull request by rollercodester**
### Reasons for making this change

Material-UI tree-shaking does not work when requiring an entire package. Each MUI component should be required separately to ensure that the entire MUI library is not unnecessarily bundled (i.e. only require what is actually used).

Also abstracted context usage into a custom hook, which is a popular pattern in commercial React dev.

fixes #2748

### CODE REVIEW

File: packages/material-ui/src/Theme/MaterialUIContextProps.ts [hunk 1]
```diff
@@ -1,69 +1,60 @@
...
-  Paper,
-  Radio,
-  RadioGroup,
-  Slider,
-  SvgIcon,
-  TextField,
-  Typography,
-} = mui;
+import { ComponentType } from 'react';
+import type {
```
Comment (rollercodester) [inline packages/material-ui/src/Theme/MaterialUIContextProps.ts:2]: Notice that this is a *type* import, so it will be stripped out by the build (i.e. it won't ever make it into the bundle...it's purely for dev-time type-checking).

File: packages/material-ui/src/Theme5/Mui5ContextProps.ts [hunk 2]
```diff
@@ -1,69 +1,60 @@
...
-  Paper,
-  Radio,
-  RadioGroup,
-  Slider,
-  SvgIcon,
-  TextField,
-  Typography,
-} = mui;
+import { ComponentType } from 'react';
+import type {
```
Comment (rollercodester) [inline packages/material-ui/src/Theme5/Mui5ContextProps.ts:2]: Notice that this is a *type* import, so it will be stripped out by the build (i.e. it won't ever make it into the bundle...it's purely for dev-time type-checking).

File: packages/material-ui/src/MuiComponentContext/useMuiComponent.ts [hunk 3]
```diff
@@ -0,0 +1,16 @@
+import { useContext } from 'react';
+import MaterialUIContextProps from '../Theme/MaterialUIContextProps';
+import Mui5ContextProps from '../Theme5/Mui5ContextProps';
+import MuiComponentContext from './MuiComponentContext';
+
+export function useMuiComponent(): MaterialUIContextProps | Mui5ContextProps {
+  const muiComponents = useContext(MuiComponentContext);
+
+  if (!muiComponents) {
+    throw new Error(
```
Comment (rollercodester) [inline packages/material-ui/src/MuiComponentContext/useMuiComponent.ts:10]: This provides good feedback to the consumers if they don't have one of the MUI version peer deps installed.

File: packages/material-ui/package.json [hunk 4]
```diff
@@ -11,7 +11,8 @@
   "scripts": {
     "start": "tsdx watch",
     "build": "rimraf dist && tsdx build",
-    "test": "tsdx test"
+    "test": "tsdx test",
+    "updateSnapshot": "tsdx test -u"
```
Comment (heath-freenome) [inline packages/material-ui/package.json:15]: You can probably revert both of the `package*.json` files since they really don't affect the rest of this change and the `package-lock.json` change was built using node 16 which we don't yet support.

File: packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx [hunk 5]
```diff
@@ -62,16 +50,16 @@ const ArrayFieldDescription = ({
...
     flex: 1,
     paddingLeft: 6,
     paddingRight: 6,
     fontWeight: 'bold',
-    minWidth: 0
+    minWidth: 0,
   };
   return (
-    <Grid container={true} key={props.key} alignItems="center">
+    <Grid container={true} key={props.key} alignItems='center'>
```
Comment (heath-freenome) [inline packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx:62]: Can you revert **all** of the double-to-single quote changes on the props passed to components? I'm guessing that your IDE auto-fix is on and you have them set to single quotes. It breaks from the patterning in the rest of the library

File: packages/material-ui/src/ErrorList/ErrorList.tsx [hunk 6]
```diff
@@ -1,31 +1,29 @@
...
-          Errors
-        </Typography>
+        <Typography variant='h6'>Errors</Typography>
         <List dense={true}>
           {errors.map((error, i: number) => {
             return (
               <ListItem key={i}>
                 <ListItemIcon>
-                  <ErrorIcon color="error"/>
+                  <ErrorIcon color='error' />
```
Comment (heath-freenome) [inline packages/material-ui/src/ErrorList/ErrorList.tsx:17]: Again, please revert the double-to-single quotes

File: packages/material-ui/src/FieldTemplate/FieldTemplate.tsx [hunk 7]
```diff
@@ -35,14 +35,12 @@ const FieldTemplate = ({
...
-        fullWidth={true}
-        error={rawErrors.length ? true : false}
-        required={required}>
+      schema={schema}
+    >
+      <FormControl fullWidth={true} error={rawErrors.length ? true : false} required={required}>
         {children}
         {displayLabel && rawDescription ? (
-          <Typography variant="caption" color="textSecondary">
+          <Typography variant='caption' color='textSecondary'>
```
Comment (heath-freenome) [inline packages/material-ui/src/FieldTemplate/FieldTemplate.tsx:43]: Again, please revert the double-to-single quotes

File: packages/material-ui/src/Theme/MaterialUIContextProps.ts [hunk 8]
```diff
@@ -1,69 +1,60 @@
...
-  RadioGroup?: RadioGroup;
-  Slider?: Slider;
-  TextField?: TextField;
-  Typography?: Typography;
-  AddIcon?: SvgIcon;
-  ArrowDownwardIcon?: SvgIcon;
-  ArrowUpwardIcon?: SvgIcon;
-  ErrorIcon?: SvgIcon;
-  RemoveIcon?: SvgIcon;
+  Box: ComponentType<BoxProps>;
```
Comment (heath-freenome) [inline packages/material-ui/src/Theme/MaterialUIContextProps.ts:31]: I noticed that typescript was giving me an error for each component when using this approach. Complaining about not having a constructor... It still seems to work, but that's a lot of TS error to potentially clean up if we ever enable full typescript error validation.

File: packages/material-ui/src/TitleField/TitleField.tsx [hunk 9]
```diff
@@ -1,16 +1,16 @@
...
 
 const TitleField = ({ title }: FieldProps) => {
-  const { Box, Divider, Typography } = useContext(MuiComponentContext);
+  const { Box, Divider, Typography } = useMuiComponent();
   return (
     <Box mb={1} mt={1}>
-      <Typography variant="h5">{title}</Typography>
-      <Divider/>
+      <Typography variant='h5'>{title}</Typography>
+      <Divider />
```
Comment (heath-freenome) [inline packages/material-ui/src/TitleField/TitleField.tsx:11]: Please revert the double-to-single quotes in this file too

**Review by heath-freenome — CHANGES_REQUESTED** [review]
@epicfaace this could easily replace my simpler [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/2753) that just uses the `#__PURE__` notation

**Comment by epicfaace** [comment]
> @epicfaace this could easily replace my simpler [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/2753) that just uses the `#__PURE__` notation

Which one should we prefer? Do both PRs have the same end effect? (If so, maybe we should go with the simpler one #2753)

File: packages/material-ui/src/Theme5/Mui5Context.tsx [hunk 10]
```diff
@@ -1,77 +1,92 @@
...
+  RadioGroup = require('@mui/material/RadioGroup').default;
+  Slider = require('@mui/material/Slider').default;
+  TextField = require('@mui/material/TextField').default;
+  Typography = require('@mui/material/Typography').default;
+  // icons
+  AddIcon = require('@mui/icons-material/Add').default;
+  ArrowDownwardIcon = require('@mui/icons-material/ArrowDownward').default;
+  ArrowUpwardIcon = require('@mui/icons-material/ArrowUpward').default;
+  ErrorIcon = require('@mui/icons-material/Error').default;
+  RemoveIcon = require('@mui/icons-material/Remove').default;
```
[the remark this answers is not in the document]
Comment (mdarocha) [reply packages/material-ui/src/Theme5/Mui5Context.tsx:68]: The `@mui/icons-material` and `@mui/material` packages have `"sideEffects": false` set in their `package.json`, which [according to webpack documentation](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free), works like `#__PURE__` on a package-scope level.

Therefore manual `#__PURE__` comments should be unnecessary. The bundled `material-ui.esm.js` file in the current `4.0.1` version of the package has `#__PURE__` comments auto-inserted by webpack.

**Comment by rollercodester** [comment]
> PR

**Comment by rollercodester** [comment]
I will add the PURE hints to my PR and see if that reduces the bundle even further. I'll also get the formatting issues fixed here soon. Sorry about that...yep, it's our prettier config I temporarily copied in as I didn't see one on the repo.

File: packages/material-ui/src/Theme/MaterialUIContextProps.ts (hunk 8 above)
Comment (rollercodester) [reply packages/material-ui/src/Theme/MaterialUIContextProps.ts:31]: Interesting. I'm not seeing those errors/warnings in VS code or during build.

**Comment by rollercodester** [comment]
> I will add the PURE hints to my PR and see if that reduces the bundle even further. I'll also get the formatting issues fixed here soon. Sorry about that...yep, it's our prettier config I temporarily copied in as I didn't see one on the repo.

I just verified that what @mdarocha stated above is correct; after adding the PURE hints, it had no impact on further reducing bundle size.

**Comment by heath-freenome** [comment]
> > I will add the PURE hints to my PR and see if that reduces the bundle even further. I'll also get the formatting issues fixed here soon. Sorry about that...yep, it's our prettier config I temporarily copied in as I didn't see one on the repo.
> 
> I just verified that what @mdarocha stated above is correct; after adding the PURE hints, it had no impact on further reducing bundle size.

Cool... nevermind then :)

File: packages/material-ui/src/Theme/MaterialUIContextProps.ts (hunk 8 above)
Comment (heath-freenome) [reply packages/material-ui/src/Theme/MaterialUIContextProps.ts:31]: I'll pull down your PR and see if I still get them

File: packages/material-ui/package.json [hunk 11]
```diff
@@ -100,4 +100,4 @@
     "url": "git+https://github.com/rjsf-team/react-jsonschema-form.git"
   },
   "license": "Apache-2.0"
-}
+}
```
Comment (heath-freenome) [inline packages/material-ui/package.json:103]: Also revert `package-lock.json` and this one-line diff

File: packages/material-ui/src/FieldTemplate/WrapIfAdditional.tsx [hunk 12]
```diff
@@ -58,7 +57,7 @@ const WrapIfAdditional = ({
             id={`${id}-key`}
             name={`${id}-key`}
             onBlur={!readonly ? handleBlur : undefined}
-            type="text"
+            type='text'
```
Comment (heath-freenome) [inline packages/material-ui/src/FieldTemplate/WrapIfAdditional.tsx:60]: This one too

File: packages/material-ui/src/FieldTemplate/WrapIfAdditional.tsx [hunk 13]
```diff
@@ -67,7 +66,7 @@ const WrapIfAdditional = ({
       </Grid>
       <Grid item={true}>
         <IconButton
-          size="small"
+          size='small'
```
Comment (heath-freenome) [inline packages/material-ui/src/FieldTemplate/WrapIfAdditional.tsx:69]: Another one to revert

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx [hunk 14]
```diff
@@ -1,7 +1,11 @@
-import React, { useContext } from 'react';
+import React from 'react';
 import { WidgetProps, utils } from '@rjsf/core';
 
-import MuiComponentContext from '../MuiComponentContext/MuiComponentContext';
+import { useMuiComponent } from '../MuiComponentContext';
+
+type OnSliderChangeEvtHdlr = ((event: React.ChangeEvent<{}>, value: number | number[]) => void) &
+  React.FormEventHandler<HTMLSpanElement> &
+  ((event: Event, value: number | number[], activeThumb: number) => void);
```
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:8]: @rollercodester was this intentional or some sort of cut/paste error?

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx [hunk 15]
```diff
@@ -36,10 +36,10 @@ const RangeWidget = ({
       </FormLabel>
       <Slider
         disabled={disabled || readonly}
-        onChange={_onChange}
+        onChange={(_onChange as unknown) as OnSliderChangeEvtHdlr}
```
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:39]: This can be reverted, no?

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx (hunk 14 above)
[the remark this answers is not in the document]
Comment (rollercodester) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:8]: tldr; It's a typing issue.

The handler type did not match the prop type on the component and TS flagged this as an error on my end. I noticed quite a few TS errors before the PR (mainly in how the context types were originally devd). I tried to address them as I saw them.

**Comment by heath-freenome** [comment]
> > @epicfaace this could easily replace my simpler [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/2753) that just uses the `#__PURE__` notation
> 
> Which one should we prefer? Do both PRs have the same end effect? (If so, maybe we should go with the simpler one #2753)

I'm leaning towards this one....

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (rollercodester) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:39]: Same as above. TS typing error. If you're not seeing these, then there must be something different between our dev environments. I'm running Typescript v4.2.3. Maybe that's the difference?

File: packages/material-ui/src/Theme/MaterialUIContext.tsx [hunk 16]
```diff
@@ -1,74 +1,90 @@
...
+  RadioGroup = require('@material-ui/core/RadioGroup').default;
+  Slider = require('@material-ui/core/Slider').default;
+  TextField = require('@material-ui/core/TextField').default;
+  Typography = require('@material-ui/core/Typography').default;
+  // icons
+  AddIcon = require('@material-ui/icons/Add').default;
+  ArrowDownwardIcon = require('@material-ui/icons/ArrowDownward').default;
+  ArrowUpwardIcon = require('@material-ui/icons/ArrowUpward').default;
+  ErrorIcon = require('@material-ui/icons/Error').default;
+  RemoveIcon = require('@material-ui/icons/Remove').default;
```
[the remark this answers is not in the document]
Comment (rollercodester) [reply packages/material-ui/src/Theme/MaterialUIContext.tsx:68]: Tried it and it had no impact on bundle size.

File: packages/material-ui/src/Theme5/Mui5Context.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (rollercodester) [reply packages/material-ui/src/Theme5/Mui5Context.tsx:68]: I've confirmed what @mdarocha stated is correct. No impact in bundle size by using the pure hints.

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:39]: Ah... `packages/material-ui` is using `3.5.3`

File: packages/material-ui/package-lock.json [hunk 17]
```diff
@@ -15070,4 +15070,4 @@
       }
     }
   }
-}
+}
```
Comment (heath-freenome) [inline packages/material-ui/package-lock.json:15073]: There is also this little diff which can be resolved

**Comment by heath-freenome** [comment]
Please update the `CHANGELOG.md` file in the `@rjsf/material-ui` section to indicate that:
1. How you are fixing https://github.com/rjsf-team/react-jsonschema-form/issues/2748 
2. Also mention that you added the new hook.

File: CHANGELOG.md [hunk 18]
```diff
@@ -32,6 +32,8 @@ should change the heading of the (upcoming) version to include a major version b
 ## @rjsf/material-ui
 - Remove `console.log()` of the import error in `MaterialUIContext` and `Mui5Context`
 - Export the `MaterialComponentContext` (#2724)
+- Individually require all MUI components to fix bloated bundle size to address [@rjsf/material-ui breaks tree shaking #2748](https://github.com/rjsf-team/react-jsonschema-form/issues/2748)
```
Comment (heath-freenome) [inline CHANGELOG.md:35]: Might I suggest using simply putting (#2748) in place of the long link?

**Review by heath-freenome — APPROVED** [review]

File: CHANGELOG.md [hunk 19]
```diff
@@ -32,6 +32,8 @@ should change the heading of the (upcoming) version to include a major version b
 ## @rjsf/material-ui
 - Remove `console.log()` of the import error in `MaterialUIContext` and `Mui5Context`
 - Export the `MaterialComponentContext` (#2724)
+- Individually require all MUI components to fix bloated bundle size to address (https://github.com/rjsf-team/react-jsonschema-form/issues/2748)
+- Add new `useMuiComponent()` hook to abstract context consumption of MUI components to one place in code
```
Comment (epicfaace) [inline CHANGELOG.md:36]:
```suggestion
- Add new `useMuiComponent()` hook as a shortcut for `useContext(MuiComponentContext)`
```

File: packages/material-ui/src/MuiComponentContext/useMuiComponent.ts [hunk 20]
```diff
@@ -0,0 +1,16 @@
...
+      'Either v4 or v5 of material components and icons must be installed as peer dependencies'
```
Comment (epicfaace) [inline packages/material-ui/src/MuiComponentContext/useMuiComponent.ts:11]:
```suggestion
      'Either v4 or v5 of material-ui components and icons must be installed as dependencies'
```

File: packages/material-ui/src/RangeWidget/RangeWidget.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (epicfaace) [reply packages/material-ui/src/RangeWidget/RangeWidget.tsx:39]: @rollercodester Let's revert this change, but reference it a new issue about upgrading typescript 3 to 4.

The reason why is because I'm not sure defining `OnSliderChangeEvtHdlr` (and casting _onChange as unknown before casting it back) is the cleanest way to do it -- we might be able to change the signature / type of `_onChange` directly, for example, so it can accept the additional parameters of `OnSliderChangeEvtHdlr`. If you can find a way to do that, then I'd also be fine if you included that change in this PR.

File: packages/material-ui/src/SelectWidget/SelectWidget.tsx [hunk 21]
```diff
@@ -53,20 +53,16 @@ const SelectWidget = ({
...
-  const { TextField, MenuItem } = useContext(MuiComponentContext);
+  const { TextField, MenuItem } = useMuiComponent();
   const { enumOptions, enumDisabled } = options;
 
   const emptyValue = multiple ? [] : '';
 
-  const _onChange = ({
-    target: { value },
-  }: React.ChangeEvent<{ name?: string; value: unknown }>) =>
+  const _onChange = ({ target: { value } }: React.ChangeEvent<{ name?: string; value: unknown }>) =>
```
Comment (epicfaace) [inline packages/material-ui/src/SelectWidget/SelectWidget.tsx:61]: Is it possible to revert the whitespace changes? will make git blames easier in the future.

File: packages/material-ui/src/Theme/MaterialUIContext.tsx [hunk 22]
```diff
@@ -83,10 +99,25 @@ if (mui && Object.keys(mui).length && icons && Object.keys(icons).length) {
...
     AddIcon,
     ArrowDownwardIcon,
     ArrowUpwardIcon,
     ErrorIcon,
     RemoveIcon,
   };
 }
+
+export let DefaultChildren = () => {
+  if (MaterialUIContext.Box && MaterialUIContext.Button && MaterialUIContext.AddIcon) {
```
Comment (epicfaace) [inline packages/material-ui/src/Theme/MaterialUIContext.tsx:112]: Should we remove `AddIcon`?

Comment (heath-freenome) [reply packages/material-ui/src/Theme/MaterialUIContext.tsx:112]: I'm guessing it is there to ensure that all of the icons were also loaded

**Comment by heath-freenome** [comment]
@rollercodester Once you make those last few changes we will merge
