### PR TITLE
fix: `ui:title` from `ui:definitions` not applied to `oneOf`/`anyOf` dropdowns beyond first recursion level

### LINKED ISSUE #4986: `ui:title` from `ui:definitions` not applied to `oneOf`/`anyOf` dropdowns beyond first recursion level
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a SSCCE example is tremendously useful to the maintainers.
- [x] I have read the documentation

### What theme are you using?

other

### Version

6.4.1

### Current Behavior

When using `ui:definitions` with `ui:title` on a recursive `oneOf`/`anyOf` schema, dropdown labels show the defined title at the first level but fall back to "Option N" at deeper levels. Other UI settings like `ui:placeholder` work at all depths.

### Expected Behavior

Dropdown labels from `ui:definitions` should appear at all recursion depths.

### Steps To Reproduce

1. Define a recursive schema with `oneOf: [{ type: 'null' }, { $ref: '#/definitions/node' }]`
2. Set `'ui:title': 'Node'` in `ui:definitions` for `#/definitions/node`
3. Add items at depth 2+
4. Dropdown shows "Node" at depth 1 but "Option 2" at depth 2+

### Anything else?

`ui:definitions` was introduced in #4947 and a recursion fix was added in #4967. The recursion fix enabled property-level UI at all depths, but dropdown labels were missed because `MultiSchemaField` reads them from the parent-level `uiSchema.oneOf[i]` before any child field resolves its own definition.

### PR DESCRIPTION
**Pull request by adamrimon**
### Reasons for making this change

Fixes #4986

`ui:definitions` was introduced in #4947 with a two-step approach: `expandUiSchemaDefinitions` ran once at form init to walk the schema tree and pre-merge definitions into the uiSchema (stopping at recursion points to avoid infinite loops), while `resolveUiSchema` ran per-field at render time to handle the recursive cases.

#4967 fixed a gap where parent components resolve `$ref` before passing schemas to children, so by depth 2+ the `$ref` was gone. The fix preserved the original `$ref` as `__rjsf_ref` on resolved schemas, letting `resolveUiSchema` find it at any depth.

With `__rjsf_ref` in place, property-level options like `ui:placeholder` work at any recursion depth because each `SchemaField` resolves its own definitions at runtime. However, `expandUiSchemaDefinitions` was still responsible for populating `uiSchema.oneOf[i]` entries that `MultiSchemaField` reads for dropdown titles, and since it stopped at recursion points, this introduced a bug where those titles were missing beyond the first level.

This PR extends `resolveUiSchema` to walk `oneOf`/`anyOf` branches one level deep to populate dropdown titles at every depth, and removes the now-unnecessary `expandUiSchemaDefinitions`.

I hope this is the last bug in this feature :grimacing:

### Checklist

- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

File: packages/utils/src/resolveUiSchema.ts [hunk 1]
```diff
@@ -1,112 +1,78 @@
...
 
-    try {
-      resolvedSchema = findSchemaDefinition<S>(ref, rootSchema as S);
-    } catch {
-      resolvedSchema = currentSchema;
-    }
+  let result: UiSchema<T, S, F>;
+  if (!definitionUiSchema) {
+    result = localUiSchema || {};
+  } else if (!localUiSchema || Object.keys(localUiSchema).length === 0) {
```
Comment (heath-freenome) [inline packages/utils/src/resolveUiSchema.ts]: Would the `lodash` `isEmpty()` function be a better choice here?

File: packages/utils/src/resolveUiSchema.ts [hunk 2]
```diff
@@ -1,112 +1,78 @@
...
-        result[propName] = expanded;
+  // Walk oneOf/anyOf branches to populate uiSchema[keyword][i] so MultiSchemaField
+  // can read dropdown option titles at the parent level.
+  if (definitions) {
+    let resolvedSchema: S = schema;
+    if (ref && schema[REF_KEY] && !(schema as GenericObjectType)[RJSF_REF_KEY]) {
+      try {
+        resolvedSchema = findSchemaDefinition<S>(ref, registry.rootSchema as S);
+      } catch {
+        return result;
```
Comment (nickgros) [inline packages/utils/src/resolveUiSchema.ts:55]: Maybe should log the thrown error as a warning or error in this `catch`?

File: packages/utils/src/resolveUiSchema.ts [hunk 3]
```diff
@@ -1,112 +1,78 @@
...
       const uiSchemaArray: UiSchema<T, S, F>[] = Array.isArray(currentUiSchemaArray) ? [...currentUiSchemaArray] : [];
 
       let hasExpanded = false;
       for (let i = 0; i < schemaOptions.length; i++) {
-        const optionSchema = schemaOptions[i] as S;
-        const optionUiSchema = (uiSchemaArray[i] || {}) as UiSchema<T, S, F>;
-        const expanded = expandUiSchemaDefinitions(optionSchema, optionUiSchema, registry, new Set(visited));
-        if (Object.keys(expanded).length > 0) {
-          uiSchemaArray[i] = expanded;
+        const optionRef = ((schemaOptions[i] as GenericObjectType)?.[RJSF_REF_KEY] ??
```
Comment (heath-freenome) [inline packages/utils/src/resolveUiSchema.ts]: Consider pulling out `(schemaOptions[i] as GenericObjectType)` as a local variable?

**Comment by heath-freenome** [comment]
@adamrimon  Sorry for the delay on the review, was on vacation. Also you will have to rebase and resolve conflicts.

File: CHANGELOG.md [hunk 4]
```diff
@@ -27,6 +27,15 @@ should change the heading of the (upcoming) version to include a major version b
...
 - Fixed `extraErrors` not displaying when `customErrors` are also present (e.g., with array fields and controlled `formData`), fixing [#4982](https://github.com/rjsf-team/react-jsonschema-form/issues/4982)
+- Removed `expandUiSchemaDefinitions` call at form init, now handled at runtime by `resolveUiSchema`, fixing [#4986](https://github.com/rjsf-team/react-jsonschema-form/issues/4986)
+
+## @rjsf/utils
+
+- Fixed `ui:title` from `ui:definitions` not applied to `oneOf`/`anyOf` dropdowns beyond first recursion level, fixing [#4986](https://github.com/rjsf-team/react-jsonschema-form/issues/4986)
+
+## Dev / docs / playground
+
+- Updated References playground sample to demonstrate `oneOf` with `ui:title` at recursive depth, related to [#4986](https://github.com/rjsf-team/react-jsonschema-form/issues/4986)
```
Comment (heath-freenome) [inline CHANGELOG.md]: Now that I've released 6.4.2 can you move this to 6.5.0?

**Comment by heath-freenome** [comment]
@adamrimon Looking forward to getting this over the line. Is there anything I can do to help? Any questions?

**Review by heath-freenome — APPROVED** [review]
