### PR TITLE
fix #3696 - Playground fixes and light improvements

### LINKED ISSUE #3696: Custom Array and Custom Object samples from playground not working
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

On playground <https://rjsf-team.github.io/react-jsonschema-form/>, when I click Custom Array or Custom Object, the page just blanks. It shows nothing.

### Expected Behavior

I was expecting to see Custom Array and Custom Object working on playground. I suspect it's somehow related to issue #3695, because if we inspect https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/playground/src/samples/customArray.tsx and https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/playground/src/samples/customObject.tsx we realize they are the only samples that the default export cannot be converted to json, meaning it's not a valid "JSONSchema" form anymore.

### Steps To Reproduce

# Custom Array bug
1. Go to https://rjsf-team.github.io/react-jsonschema-form/
2. Click "Custom Array"

# Custom Object bug
1. Go to https://rjsf-team.github.io/react-jsonschema-form/
2. Click "Custom Object"

### Environment

```markdown
- OS: Windows 22H2 (19045.2965)
- Node: 16.20.0
- npm: 8.19.4
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
Fixes #3696 
- Fixed broken playground examples
- Added experimental_defaultFormStateBehavior.emptyObjectFields control to Playground
- Fixed bug where subthemes would not appear in Playground

- [X] **I'm updating documentation**
  - [X] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/playground/src/samples/customObject.tsx [hunk 1]
```diff
@@ -1,29 +1,48 @@
...
+          schema={schema}
+          uiSchema={uiSchema}
+          registry={registry}
+        />
+      )}{' '}
+      {description}
       <div className='row'>
         {properties.map((prop) => (
-          <div className='col-lg-2 col-md-4 col-sm-6 col-xs-12' key={prop.content.key}>
+          <div className='col-lg-1 col-md-2 col-sm-4 col-xs-6' key={prop.content.key}>
```
Comment (nickgros) [inline packages/playground/src/samples/customObject.tsx:32]: Slightly altered this example because the iframe is rarely small enough to show the grid

**Review by heath-freenome — APPROVED** [review]
Just fix up the `CHANGELOG` and you are good to go

**Comment by heath-freenome** [comment]
@nickgros Can you also fix this one little issue I just spotted in the validation docs? Change `ajv6` to `ajv`

Screenshot 2023-05-30 at 10 34 47 AM
