### PR TITLE
Cache schemas by explicit ID in AJV8Validator.isValid

### LINKED ISSUE #3692: Terrible performance with big anyOf field
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.7.0

### Current Behavior

Since upgrade from v2 to v5, we're having a lot of trouble with performance on one of our bigger forms. The whole schema is a single `oneOf` field, with 86 different object options, and about 6000 lines total.

The form is basically unusable when typing, because `validator.isValid()` calls from inside `Form->getDefaultFormState()->getClosestMatchingOption()` and `MuiSchemaField->componentDidUpdate()->getClosestMatchingOption()` are clogging up the main thread completely:

image

I was hoping to solve those problems by using the discriminator property, as hinted [in this comment](https://github.com/rjsf-team/react-jsonschema-form/issues/3517#issuecomment-1536485098), but it isn't making to be making any noticable difference - because `isValid` still gets called, even when using discriminant: 
``` typescript 
if (discriminatorField && has(option, [PROPERTIES_KEY, discriminatorField])) {
  const value = get(formData, discriminatorField);
  const discriminator = get(option, [PROPERTIES_KEY, discriminatorField], {});

  if (validator.isValid(discriminator, value, rootSchema)) {
    return i;
  }
}
``` 

I'm not sure why this is clogging the thread so badly even on strong computers, but it does. Not sure if its a bug, but it may very well be, since `liveValidate` runs completely OK on the form - and I don't see a reason why pre-selecting an option should be so much more demanding than liveValidating the whole form. 

This modification removes my performance problems completely, although it's certainly not a suitable complete solution: https://github.com/michal-kurz/react-jsonschema-form/pull/2/files

Is there a bug with ajv validators? If not, is it appropriate to run this demanding validation in this manner? What do you think should be done about it, if anything? 

### Expected Behavior

_No response_

### Steps To Reproduce

Paste [this schema](https://pastebin.com/J9Btpkn6) into playground  - this is our real schema, with values replaced by hashes (to strip potentially sensitive information)

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by evshi**
### Reasons for making this change

fixes #3692

For allOf/anyOf schemas, subschemas are compiled each time they are encountered if they lack an $id field. This can create poor performance for large lists or recursive refs. Leveraging the ajv cache to cache subschemas that have been encountered before greatly improves performance.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/validator-ajv8/src/validator.ts [hunk 1]
```diff
@@ -137,12 +138,17 @@ export default class AJV8Validator<T = any, S extends StrictRJSFSchema = RJSFSch
...
       if (schemaWithIdRefPrefix[ID_KEY]) {
         compiledValidator = this.ajv.getSchema(schemaWithIdRefPrefix[ID_KEY]);
+      } else {
+        compiledValidator = this.ajv.getSchema(schemaHash);
       }
       if (compiledValidator === undefined) {
-        compiledValidator = this.ajv.compile(schemaWithIdRefPrefix);
+        compiledValidator =
+          this.ajv.addSchema(schemaWithIdRefPrefix, schemaHash).getSchema(schemaHash) ||
+          this.ajv.compile(schemaWithIdRefPrefix);
```
Comment (heath-freenome) [inline packages/validator-ajv8/src/validator.ts:151]: I'm curious about the `||` of the two statements. Why not do this instead?
```suggestion
        const addedSchema = this.ajv.addSchema(schemaWithIdRefPrefix, schemaHash).getSchema(schemaHash);
        compiledValidator = this.ajv.compile(addedSchema);
```

Comment (evshi) [reply packages/validator-ajv8/src/validator.ts:151]: This is recommended by the ajv docs https://ajv.js.org/guide/managing-schemas.html#pre-adding-all-schemas-vs-adding-on-demand.

`compile` will cache by the subschema `$id` property, or by the object hash. It doesn't allow specifically storing and fetching with a specific hash. So the `||` allows us to store and fetch by the hash, and then fallback to the default behavior if necessary.

Comment (heath-freenome) [reply packages/validator-ajv8/src/validator.ts:151]: Can you add the link to the documentation above this line then?

**Comment by evshi** [comment]
@heath-freenome updated, PTAL

**Review by heath-freenome — COMMENTED** [review]
@evshi This looks pretty good! Can you update the `CHANGELOG.md` and add an `5.8.2` section for this change?

**Comment by evshi** [comment]
@heath-freenome updated CHANGELOG and confirmed up to date with main

**Review by nickgros — APPROVED** [review]
