### PR TITLE
Fixes Material-UI inline checkboxes

### LINKED ISSUE #2021: Inline Checkboxes are not appearing inline in material theme
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
The inline checkboxes are not appearing inline in material view, in default view it does.

### Steps to Reproduce
download - 2020-08-28T132841 367
download - 2020-08-28T132906 914

#### Expected behavior
The behavior should be the same across themes.

### Version

Can be reproduced on the hosted version of this site itself
https://rjsf-team.github.io/react-jsonschema-form/

### PR DESCRIPTION
**Pull request by adam-beck**
### Reasons for making this change

Fixes an issue when setting the UI to display checkboxes inline does not honor the configuration. This fix only applies to the material-ui package.

Selection_001

Fixes #2021 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 1]
```diff
@@ -76,13 +76,7 @@ const CheckboxesWidget = ({
               onFocus={_onFocus}
             />
           );
-          return inline ? (
```
Comment (adam-beck) [inline packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:79]: I try not to refactor within unrelated commits but this seemed relevant since the code block removed used the `inline` property. I'm not sure why this was done but this is redundant regardless because both sides of the ternary return the same thing.

**Comment by NiteshOswal** [comment]
Ran into this issue earlier today. Glad there's a fix for it @agustin107 @epicfaace Any ideas when can this be merged?

**Review by epicfaace — APPROVED** [review]

**Comment by fadhilx** [comment]
when will this be merge to latest version?
