### PR TITLE
fix #3700 - Compiling Schema mergeAllOf errors

### LINKED ISSUE #3700: compileSchemaValidators doesn't expand allOf when failing to merge
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.7.3

### Current Behavior

When creating a compiled schema with allOf and it fails to merge, it does not resolve any of the all of schemas to create validators. 

### Expected Behavior

When compiling schema expected to still resolve allOf schemas even if `mergeAllOf` fails.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cwendtxealth**
### Reasons for making this change

fixes #3700 when mergeAllOf fails for compiled schema still return all of the sub schemas to be resolved.

This also fixes issue where `hashForSchema` is not consistent for the same schema but fields are in a different order.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/test/testUtils/testData.ts [hunk 1]
```diff
@@ -795,3 +795,57 @@ export const SCHEMA_WITH_ARRAY_CONDITION: RJSFSchema = {
     },
   },
 };
+
+export const SCHEMA_WITH_ALLOF_CANNOT_MERGE: RJSFSchema = {
```
Comment (cwendtxealth) [inline packages/utils/test/testUtils/testData.ts:799]: this schema is from the playground If Then Else sample

File: packages/utils/src/hashForSchema.ts [hunk 2]
```diff
@@ -17,11 +17,14 @@ function hashString(string: string): string {
...
+ * in consistent order before stringify to prevent different hash ids for the same schema.
  *
  * @param schema - The schema for which the hash is desired
  * @returns - The string obtained from the hash of the stringified schema
  */
 export default function hashForSchema<S extends StrictRJSFSchema = RJSFSchema>(schema: S) {
-  return hashString(JSON.stringify(schema));
+  const allKeys = new Set<string>();
+  JSON.stringify(schema, (key, value) => (allKeys.add(key), value));
+  return hashString(JSON.stringify(schema, Array.from(allKeys).sort()));
```
Comment (heath-freenome) [inline packages/utils/src/hashForSchema.ts:29]: This is an interesting use of `JSON.stringify`

**Review by heath-freenome — COMMENTED** [review]
Can you also update the `CHANGELOG.md` file, putting the change info under the `5.8.0` release

File: packages/utils/src/hashForSchema.ts (hunk 2 above)
Comment (cwendtxealth) [reply packages/utils/src/hashForSchema.ts:29]: I agree, the credit is from this [stackoverflow](https://stackoverflow.com/questions/16167581/sort-object-properties-and-json-stringify/53593328#53593328) answer

Comment (heath-freenome) [reply packages/utils/src/hashForSchema.ts:29]: Would you be willing to add a comment above line 28 referencing this link? I like leaving breadcrumbs to solutions that I acquired so that others can understand and learn

Comment (cwendtxealth) [reply packages/utils/src/hashForSchema.ts:29]: sure!

**Review by heath-freenome — APPROVED** [review]
