### PR TITLE
fix: Update anyOf schema to correctly update items in an array

### LINKED ISSUE #1486: anyOf field incorrectly updating after change
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Since updating to react 16, the anyOf field doesn't correctly update after receiving props. It will override the selected option incorrectly. This can be resolved by migrating to the componentDidUpdate method instead of the componentWillReceiveProps that's currently marked unsafe. componentWillReceiveProps will update state synchronously and componentDidUpdate will update state asynchronously.

### Steps to Reproduce

1. Go to anyOf field in storybook of the latest version of master
2. Add a new entry and keep it selected as option 1 and enter some text in the input field
3. Add another entry and select option 2 and enter some text in the input field
4. Move the option 2 up in the array.
anyOfError

#### Expected behavior

The array should have the two positions switched.

#### Actual behavior

The array only has one position switched correctly, while the other has the wrong selected option even though the state has been changed.

### Version

v.1.8.0

### PR DESCRIPTION
**Pull request by SuriGill**
### Reasons for making this change

componentWillReceiveProps is no longer recommended by React after updating to React 16 as it has some design flaws. Instead, I've updated to a componentDidUpdate that will change after formData changes specifically. I've added a test to demonstrate the bug that was causing an update twice and selectedOption to become out of sync when moving indices in an array using anyOf.

If this is related to existing tickets, include links to them as well.

fixes first issue in #1486 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/components/fields/MultiSchemaField.js [hunk 1]
```diff
@@ -21,17 +22,24 @@ class AnyOfField extends Component {
...
+    ) {
+      const matchingOption = this.getMatchingOption(
+        this.props.formData,
+        this.props.options
+      );
 
-    if (matchingOption === this.state.selectedOption) {
-      return;
-    }
+      if (!prevState || matchingOption === this.state.selectedOption) {
```
Comment (epicfaace) [inline src/components/fields/MultiSchemaField.js]: Why did you add the `!prevState` check @SuriGill ? It seems like the tests already pass without it.
