### PR TITLE
Fix issues with new playground

### LINKED ISSUE #1620: Playground blurs after typing something
With the new playground update, the entire form blurs after typing something.

### PR DESCRIPTION
**Pull request by epicfaace**
Fixes #1620 

- Add options to select subthemes, so the old bootstrap subthemes (such as cerulean, etc.) are back
image

- Fix blurring when typing issue
- Use @rjsf/core instead of react-jsonschema-form package for the playground
- Fix allOf example

### CODE REVIEW

**Comment by epicfaace** [comment]
@davidrenne can you take a look and review?

File: packages/playground/src/samples/allOf.js [hunk 1]
```diff
@@ -5,15 +5,15 @@ module.exports = {
...
+            type: ["string", "boolean"],
+            default: true,
           },
         },
       },
       {
         properties: {
           lorem: {
             type: "boolean",
-            minLength: 5,
```
Comment (Saulzi) [inline packages/playground/src/samples/allOf.js]: @epicfaace 

Like the addition of being able to select the bootstrap theme in the playground :P

with regards to my PR https://github.com/rjsf-team/react-jsonschema-form/pull/1610 and the allof, and my comments regarding merging of schema's

to quote

> To validate against allOf, the given data must be valid against all of the given subschemas.

> Note that it’s quite easy to create schemas that are logical impossibilities with allOf. The following example creates a schema that won’t validate against anything (since something may not be both a string and a number at the same time):

```
{
  "allOf": [
    { "type": "string" },
    { "type": "number" }
  ]
}
"No way"
```

https://json-schema.org/understanding-json-schema/reference/combining.html

here the type to validate against should be both a string and a boolean, this would essentially mean that we could never validate against the lorem field here as the entry could be both but i believe the merge will make it so that it picks the common one.

Comment (epicfaace) [reply packages/playground/src/samples/allOf.js]: Yeah, exactly, so the schema in this file will, once merged, have `"lorem": {"type": "boolean", "default": true}`.

Comment (Saulzi) [reply packages/playground/src/samples/allOf.js]: which I believe to be incorrect behavior
