### PR TITLE
fix labelValue types, update fluent-rc tsconfig

### LINKED ISSUE #3946: Fluent UI 9: Field component only allows string as label
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

5.13.6

### Current Behavior

In `SelectWidget.tsx` there's a Fluent UI 9 `<Field />` component that only allows string or undefined as a label property. `labelValue(label, hideLabel)` provided by RJSF could also return `false` or a React component. A ts-expected-error solves it for now.

This is not an issue on implementation level, only for developers of the `fluentui-rc` package.

### Expected Behavior

The `ts-expected-error` should not be necessary.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: macOS Sonoma
- Node: 18.14.0
- npm: 9.3.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zxbodya**
### Reasons for making this change

Fixes type error for `labelValue` usages where it can not return `false`. Fixes #3946

Also updated tsconfig for `fluentui-rc`, to be the same as for other packages.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/labelValue.ts [hunk 1]
```diff
@@ -10,7 +10,16 @@ import { ReactElement } from 'react';
  * @param [fallback] - One of 3 values, `undefined` (the default), `false` or an empty string
  * @returns - `fallback` if `hideLabel` is true, otherwise `label`
  */
-export function labelValue(label?: string | ReactElement, hideLabel?: boolean, fallback?: ''): undefined | string;
```
Comment (zxbodya) [inline packages/utils/src/labelValue.ts:13]: @heath-freenome the main issue why what we tried during weekly meeting was not working. was missing `default` in export statement

Comment (heath-freenome) [reply packages/utils/src/labelValue.ts:13]: Would just changing it to the following work without the need for the types?
```
export default function labelValue(label?: string, hideLabel?: boolean, fallback?: ''): undefined | string;
```

File: packages/fluentui-rc/src/tsconfig.json [hunk 2]
```diff
@@ -0,0 +1,24 @@
+{
```
Comment (heath-freenome) [inline packages/fluentui-rc/src/tsconfig.json:1]: I don't think this change is needed?

File: packages/fluentui-rc/test/tsconfig.json [hunk 3]
```diff
@@ -0,0 +1,18 @@
+{
```
Comment (heath-freenome) [inline packages/fluentui-rc/test/tsconfig.json:1]: I don't think this change is needed?

File: packages/fluentui-rc/tsconfig.json [hunk 4]
```diff
@@ -1,22 +1,12 @@
 {
   "extends": "../../tsconfig.base.json",
```
Comment (heath-freenome) [inline packages/fluentui-rc/tsconfig.json:2]: I don't think this change is needed?

File: packages/fluentui-rc/src/tsconfig.json (hunk 2 above)
Comment (zxbodya) [reply packages/fluentui-rc/src/tsconfig.json:1]: it is not needed for the fixing types for `labelValue`

just noticed I missed it when rebasing typescript project references branch(this is needed to have correct ts project references for test folder)

File: packages/utils/src/labelValue.ts (hunk 1 above)
Comment (zxbodya) [reply packages/utils/src/labelValue.ts:13]: the generic version is a bit more specific it also fixes cases where `ReactElement` might be not assignable to `string` property (some of removed suppressions are about that case)

it technically would be equivalent to this:

```typescript
export default function labelValue(label?: string, hideLabel?: boolean, fallback?: ''): undefined | string;
export default function labelValue(label?: string, hideLabel?: boolean, fallback?: false): undefined | false | string;
export default function labelValue(label?: ReactElement, hideLabel?: boolean, fallback?: ''): undefined | ReactElement;
export default function labelValue(
  label?: ReactElement,
  hideLabel?: boolean,
  fallback?: false
): undefined | false | ReactElement;
export default function labelValue(
  label?: string | ReactElement,
  hideLabel?: boolean,
  fallback?: false | ''
): undefined | false | string | ReactElement {
  return hideLabel ? fallback : label;
}
```

do not really have preferences, here… generic however is a bit smaller

Comment (heath-freenome) [reply packages/utils/src/labelValue.ts:13]: Let's avoid the generic so that we don't have to update the Documentation.

Comment (zxbodya) [reply packages/utils/src/labelValue.ts:13]: updated

**Comment by heath-freenome** [comment]
@zxbodya can you also update the `CHANGELOG.md` please

**Comment by heath-freenome** [comment]
@zxbodya Any idea why the latest release with your typescript updates are failing the linter?

**Review by heath-freenome — APPROVED** [review]

**Comment by heath-freenome** [comment]
> updated changelog
> 
> > @zxbodya Any idea why the latest release with your typescript updates are failing the linter? https://github.com/rjsf-team/react-jsonschema-form/actions/runs/6831318213/job/18635218081
> 
> looks to be because of `lib-test` folder (typescript output for tests), which depending on how fast typescript runs was linted (and so was not noticed initially)
> 
> added it to `.eslintignore`

Cool, I will merge this and hopefully cut a functional 5.14.1
