### PR TITLE
fix: formData change clear errorMessage

### LINKED ISSUE #4426: The errorMessage will not be cleared after the controlled Form formData changes
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.23.2

### Current Behavior

rjsf-issuse

[Codesandbox](https://codesandbox.io/p/github/JinYuSha0/rjsf-issuse/main)

### Expected Behavior

clear error message after onChange, similar to the case where formData is not used
rjsf-issuse2

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:Windows 22H2
- Node:v22.11.0
- npm:10.8.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JinYuSha0**
### Reasons for making this change

fixes #4426 

If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).

If your PR is non-trivial and you'd like to schedule a synchronous review, please add it to the weekly meeting agenda: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/getChangedFields.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * @param {any} b - The second object, representing the updated data to compare.
+ * @returns {string[]} - An array of field names that have changed.
+ *
+ * @example
+ * const a = { name: 'John', age: 30 };
+ * const b = { name: 'John', age: 31 };
+ * const changedFields = getChangedFields(a, b);
+ * console.log(changedFields); // Output: ['age']
+ */
+export default function getChangedFields(a: any, b: any): string[] {
```
Comment (heath-freenome) [inline packages/utils/src/getChangedFields.ts:21]: For better Typescript compatibility, `unknown` is preferred over `any`
```suggestion
export default function getChangedFields(a: unknown, b: unknown): string[] {
```

File: packages/utils/src/getChangedFields.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+import isEqual from 'lodash/isEqual';
+
+/**
+ * Compares two objects and returns the names of the fields that have changed.
+ * This function iterates over each field of object `a`, using `_.isEqual` to compare the field value
+ * with the corresponding field value in object `b`. If the values are different, the field name will
+ * be included in the returned array.
+ *
+ * @param {any} a - The first object, representing the original data to compare.
+ * @param {any} b - The second object, representing the updated data to compare.
```
Comment (heath-freenome) [inline packages/utils/src/getChangedFields.ts:12]:
```suggestion
 * @param a - The first object, representing the original data to compare.
 * @param b - The second object, representing the updated data to compare.
```

**Review by heath-freenome — CHANGES_REQUESTED** [review]
@JinYuSha0 Please update the `CHANGELOG.md` to add a new `5.24.0` section since you are adding a new feature to `@rjsf/utils`. And make the few suggested changes. Also, provide 100% unit tests for the `getChangedFields()` function.

Also, these unit test, when written, should help you fix the test failures that exist in your PR.

File: packages/utils/src/getChangedFields.ts (hunk 2 above)
Comment (JinYuSha0) [reply packages/utils/src/getChangedFields.ts:12]: ok, I will try to do this

**Comment by heath-freenome** [comment]
@JinYuSha0 I just merged another fix to the method you are changing... Can you first check to see if that fix also fixes the issue you are attempting to fix with this PR? Thanks. If not, then rebase that change into your PR first.

File: packages/utils/src/getChangedFields.ts (hunk 2 above)
Comment (JinYuSha0) [reply packages/utils/src/getChangedFields.ts]:
```
git log --oneline
f5a24b25 (HEAD -> main, origin/main, origin/HEAD) Bug: schema with conditions where switching to then/else subschemas did not reflect the actual validation errors in the onChange event. (#4432)
c2a60d44 Bug: Issue with formData not updating when dependencies change (#4388)
```
rjsf-issuse4

It seems that this problem has not been solved, thank you very much for your attention to this issue. I hope this project will get better and better.

**Comment by JinYuSha0** [comment]
@heath-freenome 

rjsf-issuse4

I pulled the latest commit in the main branch and executed build, it seems that this problem has not been solved, thank you very much for your attention to this issue.

```
git log --oneline
f5a24b25 (HEAD -> main, origin/main, origin/HEAD) Bug: schema with conditions where switching to then/else subschemas did not reflect the actual validation errors in the onChange event. (#4432)
c2a60d44 Bug: Issue with formData not updating when dependencies change (#4388)
```

**Comment by heath-freenome** [comment]
Also, it looks like your changes are breaking a `core` test. Can you investigate and fix?

**Comment by JinYuSha0** [comment]
I fix the breaking `core` test

1. change formData then error should be disappears.
2. when formData is srting, deepEquals again

**Review by heath-freenome — APPROVED** [review]
