### PR TITLE
fix: readonly checkbox for bootstrap-4

### LINKED ISSUE #2259: Unable to pass a boolean input to readOnly (@rjsf/bootstrap-4)
### Prerequisites
* [x]  I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
* [x]  In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
* [x]  Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Cannot pass a boolean input to readOnly with de Bootstrap4 theme but it is possible with MaterialUI theme.

#### Imports

``` typescript
import React from "react";
import { Theme as Bootstrap4Theme } from "@rjsf/bootstrap-4";
import {
  withTheme
} from "@rjsf/core";
```

#### Code

``` typescript
  const JsonSchemaForm = withTheme(Bootstrap4Theme);
  return (
    <div style={{ position: "relative" }}>
      <JsonSchemaForm
	schema={{
 	 "title": "Entité",
	  "type": "object",
	  "properties": {
	    "@id": {
	      "type": "string",
 	     "title":"ID"
  	  },
  	  "nom": {
   	   "type": "string",
 	     "title":"Nom"
  	  },
  	  "prenom": {
  	    "type": "string"
  	  },
  	  "email": {
  	    "type": "string"
  	  },
   	 "age": {
   	   "type": "number"
  	  },
  	  "sdf": {
 	     "type": "boolean"
 	   }
	  },
	  "required": ["@id", "nom", "prenom", "email", "age", "sdf"]
	}}
        uiSchema={ {
          nom: {"ui:readonly": true},
          sdf: {"ui:readonly": true}
        }
        }
      />
      </JsonSchemaForm>
  );
```

#### Expected behavior

Have the input read only as the MaterialUI theme
Screenshot (materialUI theme):
image

#### Actual behavior

Simple boolean input
Screenshot (bootstrap theme)
image

### Version

"@rjsf/bootstrap-4": "^2.4.2"
"@rjsf/core": "^2.3.0"
"@rjsf/material-ui": "^2.3.0"

### PR DESCRIPTION
**Pull request by HarmonicTons**
### Reasons for making this change

fixes #2259 

`"ui:readonly": true` was ignored with the bootstrap-4 theme as `readOnly` is not a valid property of the component Form.Check of react-bootstrap

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### Deploy preview

Once CI finishes, you should be able to view a deploy preview of the playground from this PR at this link: https://deploy-preview-[PR_NUMBER]--rjsf.netlify.app/

#### Checkbox
JSONSchema:
```json
{
  "title": "A choice",
  "type": "boolean"
}
```
UISchema:
```json
{
  "ui:readonly": true
}
```

#### Checkboxes
JSONSchema:
```json
{
  "type": "array",
  "title": "A multiple-choice list",
  "items": {
    "type": "string",
    "enum": ["foo", "bar", "fuzz", "qux"]
  },
  "uniqueItems": true
}
```
UISchema:
```json
{
  "ui:widget": "checkboxes",
  "ui:readonly": true
}
```

### CODE REVIEW

File: packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 1]
```diff
@@ -91,8 +90,7 @@ const CheckboxesWidget = ({
                 onChange={_onChange(option)}
                 onBlur={_onBlur}
                 onFocus={_onFocus}
-                disabled={disabled || itemDisabled || false}
-                readOnly={readonly}
+                disabled={disabled || readonly || itemDisabled || false}
```
Comment (epicfaace) [inline packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx:93]: Let's keep the same order as in core:

https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/widgets/CheckboxesWidget.js#L33

```suggestion
                disabled={disabled || itemDisabled || readonly}
```

File: packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 2]
```diff
@@ -73,8 +73,7 @@ const CheckboxesWidget = ({
...
```
Comment (epicfaace) [inline packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx:76]:
```suggestion
                disabled={disabled || itemDisabled || readonly}
```

**Review by epicfaace — APPROVED** [review]
This is great, thanks!
