### PR TITLE
Change boolean custom tag to bsPrefix.

### LINKED ISSUE #2648: Warning: Received `true` for a non-boolean attribute `custom`
Why custom attr in here?

https://github.com/rjsf-team/react-jsonschema-form/blob/3ec17f1c0ff40401b7a99c5e9891ac2834a1e73f/packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx#L85

my jsonschema : [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb25maWciOnsiREVCVUciOnsiUkVMRUFTRSI6Im4ifX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImNvbmZpZyJdLCJwcm9wZXJ0aWVzIjp7ImNvbmZpZyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9Db25maWdUeXBlIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsImRlZmluaXRpb25zIjp7IkJvb2xlYW4iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsieSIsIm4iXX0sIkRlYnVnT3B0aW9uc1R5cGUiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbIlJFTEVBU0UiXSwicHJvcGVydGllcyI6eyJSRUxFQVNFIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL0Jvb2xlYW4iLCJkZWZhdWx0IjoibiJ9fX0sIkNvbmZpZ1R5cGUiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiREVCVUciOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvRGVidWdPcHRpb25zVHlwZSJ9fX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

it causes error:

```log
react-dom.development.js:67 Warning: Received `true` for a non-boolean attribute `custom`.

If you want to write it to the DOM, pass a string instead: custom="true" or custom={value.toString()}.
    at select
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1641:5
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1704:5
    at SelectWidget2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:681:21)
    at Widget.MergedWidget (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:16576:33)
    at StringField (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:14570:22)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1704:5
    at FieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:362:17)
    at SchemaField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:14476:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1408:23
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:2576:5
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1965:5
    at ObjectFieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:381:32)
    at ObjectField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:13863:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1704:5
    at FieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:362:17)
    at SchemaField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:14476:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1408:23
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:2576:5
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1965:5
    at ObjectFieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:381:32)
    at ObjectField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:13863:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1704:5
    at FieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:362:17)
    at SchemaField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:14476:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1408:23
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:2576:5
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1965:5
    at ObjectFieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:381:32)
    at ObjectField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:13863:5)
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1704:5
    at FieldTemplate2 (http://localhost:3000/node_modules/.vite/@rjsf_bootstrap-4.js?v=cbf5682c:362:17)
    at SchemaField2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:14476:5)
    at form
    at Form2 (http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:17493:5)
    at http://localhost:3000/node_modules/.vite/chunk-HCTMZ6BT.js?v=cbf5682c:17972:23
    at ConfigForm (http://localhost:3000/src/addons/components/ConfigForm/ConfigForm.jsx?t=1641958137322:8:8)
    at div
    at div
    at http://localhost:3000/node_modules/.vite/chunk-XPKOMMPR.js?v=cbf5682c:1965:5
    at div
    at Config (http://localhost:3000/src/pages/classic/Config/Config.jsx?import&t=1641958137240:29:19)
    at Routes (http://localhost:3000/node_modules/.vite/chunk-BOPY2C6Z.js?v=cbf5682c:486:5)
    at Router (http://localhost:3000/node_modules/.vite/chunk-BOPY2C6Z.js?v=cbf5682c:433:15)
    at HashRouter (http://localhost:3000/node_modules/.vite/react-router-dom.js?v=cbf5682c:110:5)
    at App
```

my package.json
```json
{
  "name": "ui",
  "version": "0.0.0",
  "license": "BSD",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@rjsf/bootstrap-4": "^3.2.1",
    "@rjsf/core": "^3.2.1",
    "axios": "^0.24.0",
    "bootstrap": "^5.1.3",
    "buffer": "^6.0.3",
    "file-saver": "^2.0.5",
    "file-selector": "^0.2.4",
    "history": "5",
    "react": "^17.0.2",
    "react-bootstrap": "^2.0.4",
    "react-dom": "^17.0.2",
    "react-router": "^6.2.1",
    "react-router-dom": "6",
    "select2": "^4.1.0-rc.0",
    "stream": "^0.0.2",
    "xml-formatter": "^2.6.0",
    "xml-js": "^1.6.11"
  },
  "devDependencies": {
    "@types/node": "^17.0.8",
    "@vitejs/plugin-react": "^1.0.7",
    "sass": "^1.45.1",
    "vite": "^2.7.2"
  }
}

```

and jsx
```jsx
import React from "react";
import Form from "@rjsf/bootstrap-4";

export class ConfigForm extends React.Component {
    render() {
        const log = (type) => console.log.bind(console, type);

        return <Form
            schema={this.props.schema}
            onChange={log("changed")}
            onSubmit={log("submit")}
            onError={log("errors")}
        />
    }
}
```
if switch to @rjsf/core, this error will not happened

### PR DESCRIPTION
**Pull request by WillowP**
### Reasons for making this change

fixes #2648

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx [hunk 1]
```diff
@@ -82,7 +82,7 @@ const SelectWidget = ({
       </Form.Label>
       <Form.Control
         as="select"
-        custom
+        bsPrefix="custom-select"
```
Comment (WillowP) [inline packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx:85]: When I just removed `custom`, the tests failed because the `className` changed from `custom-select` to `form-control`. The `bsPrefix` prop seems to be the way to approach this, based on the docs at https://react-bootstrap.github.io/forms/form-control/#form-control-props

Comment (heath-freenome) [reply packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx:85]: What problem is this solving? Is there an issue associated with the change?

Comment (WillowP) [reply packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx:85]: Yes, I put it in the description. This fixes #2648

**Review by heath-freenome — APPROVED** [review]
