### PR TITLE
fix: Add generic type support to the fluent-ui theme

### LINKED ISSUE #3072: Fix Typescript generics support in all themes in the beta
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0.beta.2

### Current Behavior

None of the themes are properly supporting the passing through of generics, even core's `getDefaultRegistry()` does not do it properly

### Expected Behavior

Users can add generics on their `Form` and they will be properly spread onto all of the components

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
- Partially fixes #3072

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/fluent-ui/src/UpDownWidget/UpDownWidget.tsx [hunk 1]
```diff
@@ -57,7 +66,7 @@ const UpDownWidget = ({
   options,
   schema,
 }: // autofocus,
-WidgetProps) => {
+WidgetProps<T, S, F>) {
   const _onChange = ({
     target: { value },
   }: React.ChangeEvent<HTMLInputElement>) => onChange(Number(value));
```
Comment (heath-freenome) [inline packages/fluent-ui/src/UpDownWidget/UpDownWidget.tsx:72]: `rangeSpec()` on line 74 below has the `<S>` generic

**Review by heath-freenome — CHANGES_REQUESTED** [review]
Just one missing generic and you are good to go

**Review by heath-freenome — APPROVED** [review]
