### PR TITLE
fix: Fixed 3778 By Resolving all refs in oneOf/AnyOf options

### LINKED ISSUE #3778: anyOf/oneOf error not resolving $ref schema of object properties
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.10

### Current Behavior

The top level $ref of anyOf and oneOf schemas have recently been fixed with this [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3763) but I found that a schemas properties could still have unresolved $refs, including an array.

This error occurs in two different places, when pre compiling schema and normal runtime

For compiling schemas, anyOf and OneOf are resolved in [resolveAnyOrOneOfSchemas](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/schema/retrieveSchema.ts#L336) and will check if the top level schema has a $ref. But the schema below causes compiling to fail because in schema property there is a unresolved $ref
```json
{
  "type": "object",
  "properties": {
    "anyOfRef": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "values": {
              "$ref": "#/definitions/TestRef"
            }
          },
        },
        {
          "type": "boolean",
        }
      ]
    }
  },
  "additionalProperties": false,
  "definitions": {
    "TestRef": {
      "type": "string",
      "enum": ["1", "2"]
    }
  }
}
```

Here is a [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheUFueU9mIjpbXX0sInNjaGVtYSI6eyIkaWQiOiJ0ZXN0IiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYXJyYXlBbnlPZiI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9FcnJvckFueU9mIn19fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJkZWZpbml0aW9ucyI6eyJFcnJvckFueU9mIjp7ImFueU9mIjpbeyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1Rlc3RFbnVtIn19fSx7InR5cGUiOiJib29sZWFuIn1dfSwiVGVzdEVudW0iOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=) of the runtime error happening with anyOf. If you just add a element in the array you can see in the console logging 
```
react_devtools_backend_compact.js:2367 Error encountered compiling schema: Error: can't resolve reference __rjsf_rootSchema#/definitions/TestEnum from id -58dfa712
    at Object.code (index-f5505c26.js:911:62300)
    at w1e (index-f5505c26.js:911:23917)
    at index-f5505c26.js:911:18950
    at O.code (index-f5505c26.js:908:926)
    at O.block (index-f5505c26.js:908:2846)
    at Fte (index-f5505c26.js:911:18940)
    at y1e (index-f5505c26.js:911:17337)
    at ZYt (index-f5505c26.js:911:17095)
    at QYt (index-f5505c26.js:911:16744)
    at S1e.subschema (index-f5505c26.js:911:23436)
```
This is happening in [getClosestMatchingOption](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/schema/getClosestMatchingOption.ts#L148) where it resolves top level schema but none of a schema's properties.

For a possible solution would it make sense to also check the schemas properties if they have any $ref and resolve those as well? I can try creating a PR to fix this issue.

### Expected Behavior

Should resolve all references before checking validator isValid in anyOf/oneOf logic.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cwendtxealth**
### Reasons for making this change

fixes #3778 by going through anyOne/oneOf option schema and resolving any $refs.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/schema/retrieveSchema.ts [hunk 1]
```diff
@@ -192,6 +195,39 @@ export function resolveReference<T = any, S extends StrictRJSFSchema = RJSFSchem
   );
 }
 
+/** Resolves all references within a schema's properties and array items.
+ *
+ * @param schema - The schema for which resolving all references is desired
+ * @param rootSchema - The root schema that will be forwarded to all the APIs
+ * @returns - given schema will all references resolved
+ */
+export function resolveAllReferences<S extends StrictRJSFSchema = RJSFSchema>(schema: S, rootSchema: S): S {
```
Comment (cwendtxealth) [inline packages/utils/src/schema/retrieveSchema.ts:204]: @heath-freenome I was debating making this util specifically for oneOf/anyOf options. This is already assuming that the schema went through `resolveSchema` and has been evaluated with `formData`. Its just getting the defined $ref and updating the schema.

This might not solve the core issue of oneOf/anyOf options not fully being resolved in `resolveSchema` but it does solve the existing issue with minimum impact on the whole resolve workflow.

File: packages/utils/test/schema/sanitizeDataForNewSchemaTest.ts [hunk 2]
```diff
@@ -258,6 +258,37 @@ export default function sanitizeDataForNewSchemaTest(testValidator: TestValidato
         })
       ).toEqual({});
     });
+    it('returns empty formData after resolving schema refs', () => {
```
Comment (heath-freenome) [inline packages/utils/test/schema/sanitizeDataForNewSchemaTest.ts:261]: I'm curious about this test. What prompted you to write it?

**Review by heath-freenome — COMMENTED** [review]
Can you also update the `CHANGELOG.md` file for 5.11.1

File: packages/utils/test/schema/sanitizeDataForNewSchemaTest.ts (hunk 2 above)
Comment (cwendtxealth) [reply packages/utils/test/schema/sanitizeDataForNewSchemaTest.ts:261]: For some reason the two changes to `resolveAnyOrOneOfSchemas` and `getClosestMatchingOption` caused lose of coverage in `sanitizeDataForNewSchema`. Maybe because the refs were being resolved and it not longer needed to in `sanitizeDataForNewSchema`?
