### PR TITLE
fix: Add support for custom styles in a manner similar to classNames

### LINKED ISSUE #1200: Support for styles (in addition to className)
Are there any issues/objections for adding support for `styles` in addition to `className` here https://github.com/mozilla-services/react-jsonschema-form/blob/aebfab9baa94d35176b7197ecf080e2fc1258dcf/src/components/fields/SchemaField.js#L143 ?

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #1200 by reimplementing #1256
- In `@rjsf/utils`, added the new `style` prop onto `FieldTemplateProps`, `WrapIfAdditionalTemplateProps` and `UIOptionsBaseType`
- In `@rjsf/core`, added support for the new `style` prop in `uiSchema` as follows:
  - Updated `SchemaField` to handle the new `style` prop in the `uiSchema` similarly to `classNames`, passing it to the `FieldTemplate` and removing it from being passed down to children.
  - Also, added support for new `style` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper
  - Added or updated tests to verify the `style` prop functionality
- In all the themes, added support for new `style` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper
  - Fluent-ui is a special case since it doesn't currently implement `WrapIfAdditionalTemplate` fully
- Updated the documentation to describe this new `style` prop
  - Also updated the `validation` documentation to describe the `uiSchema` prop that can be passed to the `customValidate()` and `transformError()` functions
- Updated the `CHANGELOG.md` accordingly

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/types.ts [hunk 1]
```diff
@@ -358,6 +358,8 @@ export type FieldTemplateProps<
   id: string;
   /** A string containing the base CSS classes, merged with any custom ones defined in your uiSchema */
   classNames?: string;
+  /** An object containing the styles as defined in the `uiSchema` */
+  styles?: StyleHTMLAttributes<any>;
```
Comment (nickgros) [inline packages/utils/src/types.ts:362]: It seemed like the preference in the original PR comments was `style` rather than `styles`, which would match the React attribute name

**Review by nickgros — CHANGES_REQUESTED** [review]
@heath-freenome WDYT about using `style` to match the React property rather than `styles`? It seemed like @epicfaace also suggested the same in the original issue and PR.

Code changes otherwise LGTM.

File: CHANGELOG.md [hunk 2]
```diff
@@ -19,20 +19,45 @@ should change the heading of the (upcoming) version to include a major version b
 
 ## @rjsf/antd
 - Enable searching in the `SelectWidget` by the label that the user sees rather than by the value
+- Added support for new `styles` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200)
```
Comment (nickgros) [inline CHANGELOG.md:22]:
```suggestion
- Added support for new `style` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200) 
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -19,20 +19,45 @@ should change the heading of the (upcoming) version to include a major version b
...
 - Updated `SelectWidget` to support additional `TextFieldProps` in a manner similar to how `BaseInputTemplate` does
+- Added support for new `style` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200)
 
-## @rjsf/playground
-- Change Vite `preserveSymlinks` to `true`, which provides an alternative fix for [#3228](https://github.com/rjsf-team/react-jsonschema-form/issues/3228) since the prior fix caused [#3215](https://github.com/rjsf-team/react-jsonschema-form/issues/3215).
+## @rjsf/semantic-ui
+- Added support for new `style` prop on `FieldTemplate` and `WrapIfAdditionalTemplate` rendering them on the outermost wrapper, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200)
+
+## @rjsf/utils
+- Updated the `FieldTemplateProps`, `WrapIfAdditionalTemplateProps` and `UIOptionsBaseType` types to add `styles?: StyleHTMLAttributes<any>`, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200)
```
Comment (nickgros) [inline CHANGELOG.md:50]:
```suggestion
- Updated the `FieldTemplateProps`, `WrapIfAdditionalTemplateProps` and `UIOptionsBaseType` types to add `style?: StyleHTMLAttributes<any>`, partially fixing [#1200](https://github.com/rjsf-team/react-jsonschema-form/issues/1200) 
```

**Review by nickgros — APPROVED** [review]
Missed a couple in the changelog, won't block you from merging
