### PR TITLE
Make formData accessible in a custom FieldTemplate

### LINKED ISSUE #1678: Get formData in the custom FieldTemplate
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Is there any way to access the form data inside the Custom FieldTemplate component?
What I want is to remove the **required** mark if formData is available for that field.

### Version

1.8.1(latest)

### PR DESCRIPTION
**Pull request by TimothyBJacobs**
### Reasons for making this change

I have a similar need to access the `formData` for the field about to be rendered in the `FieldTemplate`.

Fixes #1678.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Thanks! Can you update the docs for FieldTemplate to include this additional prop?

**Comment by TimothyBJacobs** [comment]
Sure thing, updated!

**Review by epicfaace — APPROVED** [review]

File: packages/core/index.d.ts [hunk 1]
```diff
@@ -143,7 +143,7 @@ declare module '@rjsf/core' {
 
     export type Field = React.StatelessComponent<FieldProps> | React.ComponentClass<FieldProps>;
 
-    export type FieldTemplateProps = {
+    export type FieldTemplateProps<T = any> = {
```
Comment (epicfaace) [inline packages/core/index.d.ts:146]: What's the difference between doing `<T = any>` and `<T>`? Asking because we have `FormProps<T>` elsewhere in this typings file.

Comment (TimothyBJacobs) [reply packages/core/index.d.ts:146]: I followed the other `FieldTemplateProps` as examples. So for instance `ArrayFieldTemplateProps` and `ObjectFieldTemplateProps`. As I understand it, it defaults the type of `any` so the type doesn't need to be explicitly provided. For example, in the [TS Playground](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAYgSygGwCYBUoFsLIIYhQAKATgPYQDOAPOgHwwC8MA3sDDAGZklYAiBPAC4Y6ANzAAvsGABjMgDtKILkjSYc+QiMQoM2XAWLkq1AMogSCBQHMGzNh268BIYTABEACQQepM+SUVTjV9TSMAeSwEEB1QjUNCUgpKJlZ2Lh5+QRFvX39QSFhddQMtYxSAQQUwWjS8Gvt0pyzXd3ECwOVVPQTy6rA43rKjZKoB80trOzTHTJcczx8-aTlFbpDh8MIBqJih0u2K8ZrZjOdst1zlgqA).
