### PR TITLE
fix: Generic support for Chakra UI

### LINKED ISSUE #3072: Fix Typescript generics support in all themes in the beta
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0.beta.2

### Current Behavior

None of the themes are properly supporting the passing through of generics, even core's `getDefaultRegistry()` does not do it properly

### Expected Behavior

Users can add generics on their `Form` and they will be properly spread onto all of the components

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
- Partially fix #3072
- Extract ChakraIconButton to its own file to abstract away React.memo
- Refactor AltDateWidget to extract DateElement component

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx [hunk 1]
```diff
@@ -16,6 +19,31 @@ const rangeOptions = (start: number, stop: number) => {
   return options;
 };
 
+function DateElement<
```
Comment (nickgros) [inline packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx:22]: This componente was originally created within the AltDateWidget component, so I extracted it to prevent potential performance issues where the component may be excessively re-rendered.

File: packages/chakra-ui/src/IconButton/ChakraIconButton.tsx [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+      aria-label={props.title!}
+      {...otherProps}
+      icon={icon as ChakraIconButtonProps["icon"]}
+    />
+  );
+}
+
+ChakraIconButton.displayName = "ChakraIconButton";
+
+export default React.memo(ChakraIconButton) as typeof ChakraIconButton;
```
Comment (heath-freenome) [inline packages/chakra-ui/src/IconButton/ChakraIconButton.tsx:28]: I'm not sure how the memo will affect the typing

File: packages/chakra-ui/src/IconButton/index.ts [hunk 3]
```diff
@@ -1,2 +1,2 @@
-export { default } from "./IconButton";
+export { default } from "./ChakraIconButton";
```
Comment (heath-freenome) [inline packages/chakra-ui/src/IconButton/index.ts:1]: Does it make sense to `export * from "./ChakraIconButton";` too?

File: packages/chakra-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx [hunk 4]
```diff
@@ -83,6 +91,4 @@ const ObjectFieldTemplate = (props: ObjectFieldTemplateProps) => {
       </Grid>
```
Comment (heath-freenome) [inline packages/chakra-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx:91]: Can you add the `<T, S, F>` to the `canExpand()` function above?

File: packages/chakra-ui/src/RangeWidget/RangeWidget.tsx [hunk 5]
```diff
@@ -7,10 +7,20 @@ import {
   SliderThumb,
   SliderTrack,
 } from "@chakra-ui/react";
-import { rangeSpec, WidgetProps } from "@rjsf/utils";
+import {
+  FormContextType,
+  rangeSpec,
```
Comment (heath-freenome) [inline packages/chakra-ui/src/RangeWidget/RangeWidget.tsx:12]: Make sure to change it to `rangeSpec<S>` below

**Review by heath-freenome — CHANGES_REQUESTED** [review]

**Review by heath-freenome — COMMENTED** [review]
Also, update the main `index.tsx` (maybe rename to `index.ts` since it doesn't need to be a `.tsx`)

```
import Form from "./Form";

export { default as Form, generateForm } from "./Form";
export { default as Templates, generateTemplates } from "./Templates";
export { default as Theme, generateTheme } from "./Theme";
export { default as Widgets, generateWidgets } from "./Widgets";
export { __createChakraFrameProvider } from "./ChakraFrameProvider";

export type { ChakraUiSchema as UiSchema } from "./utils";

export default Form;
```

File: packages/chakra-ui/src/IconButton/index.ts (hunk 3 above)
Comment (nickgros) [reply packages/chakra-ui/src/IconButton/index.ts:1]: The `default` export is the only thing exported from the module, so it makes no difference. Will change it to 

```
export { default as ChakraIconButton } from "./ChakraIconButton";
```

File: packages/chakra-ui/src/IconButton/ChakraIconButton.tsx (hunk 2 above)
Comment (nickgros) [reply packages/chakra-ui/src/IconButton/ChakraIconButton.tsx:28]: We can't use pass generic parameters to `ChakraIconButton` without the cast.

File: packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx (hunk 1 above)
Comment (heath-freenome) [reply packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx:22]: I wonder if we should do this for other themes?

File: packages/chakra-ui/src/IconButton/index.ts [hunk 6]
```diff
@@ -1,2 +1,2 @@
-export { default } from "./IconButton";
+export { default as ChakraIconButton } from "./ChakraIconButton";
```
Comment (heath-freenome) [inline packages/chakra-ui/src/IconButton/index.ts:1]: I think it was ok without the rename

**Review by heath-freenome — APPROVED** [review]
