### PR TITLE
fix(@rjsf/core): prevent extraErrors duplication on array field mutation (#5041)

### LINKED ISSUE #5041: Extra errors duplicated when a sibling array field is mutated
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

react-bootstrap

### Version

6.5.1

### Current Behavior

When extraErrors are set on a field outside an array, any array mutation (add / remove / reorder) causes the sibling field's __errors entries to be concatenated to themselves in errorSchema. Each interaction adds another copy, so the same error renders N+1 times after N clicks.

### Expected Behavior

extraErrors should stay stable across unrelated array mutations. A sibling field's error count should remain at 1 no matter how many times the user adds, removes, or reorders array items.

### Steps To Reproduce

https://codesandbox.io/p/sandbox/optimistic-torvalds-6f6yj6

* In example sandbox, name field starts with an error from extra errors
* Change the array field, add, remove, move an item
* The name error gets duplicated

### Environment

```markdown
- OS: MacOS 26.2 (25C56)
- Node: v20.19.5
- npm: 11.12.1
```

### Anything else?

The following analysis was generated with Opus 4.7. I took a look over it's findings and they look legitimate.

## Root cause

  The bug emerges from a three-step interaction across `SchemaField`, `ArrayField`, and `Form.processPendingChange`.

  ### 1. `SchemaField` coerces undefined `errorSchema` to an empty object

  `packages/core/src/components/fields/SchemaField.tsx` (line 181 in v6.5.1):

  ```js
  const { __errors, ...fieldErrorSchema } = errorSchema || {};
  ```

  When the parent's `errorSchema[childKey]` is `undefined` (the array has no errors of its own), this defaults to `{}` and the rest-spread passes a **truthy empty object** down to the child `ArrayField`.

  ### 2. `ArrayField` treats that empty object as "has errors" and emits a truthy `newErrorSchema`

  `packages/core/src/components/fields/ArrayField.tsx`, `handleAddItem` (and the sibling `handleCopyItem` / `handleRemoveItem` / `handleReorderClick`):

  ```js
  let newErrorSchema;
  if (errorSchema) {                  // {} is truthy → enters branch
    newErrorSchema = {};              // builds an empty re-indexed errorSchema
    for (const idx in errorSchema) { /* no-op on empty object */ }
  }
  onChange(newFormData, path, newErrorSchema);  // emits truthy {} newErrorSchema
  ```

  ### 3. `Form.processPendingChange` re-merges `extraErrors` into state that already contains them

  `packages/core/src/components/Form.tsx`, `processPendingChange` (around line 997 in v6.5.1):

  ```js
  else if (!noValidate && newErrorSchema) {       // {} is truthy → enters
    const mergedErrors = this.mergeErrors(
      { errorSchema: originalErrorSchema, errors },
      extraErrors,
      customErrors,
    );
    state = { formData: newFormData, ...mergedErrors, customErrors };
  }
  ```

  `originalErrorSchema = this.state.errorSchema` already contains the prior `extraErrors` merge applied on mount (and/or via `getDerivedStateFromProps`). `mergeErrors` → `validationDataMerge` → `mergeObjects(..., concatArrays=true)`
  then concatenates the `__errors` arrays for any field present in both the state and `extraErrors`. Identical `__errors` strings accumulate on every array onChange.

  ### Why it's silent without the array interaction

  The `extraErrors` merge is gated on `newErrorSchema` being truthy. With no array interaction, `newErrorSchema` never arrives from a field, and the duplication path is never entered — the error appears exactly once.

  ## Suggested fixes

  Any of the following would resolve the duplication; (c) is the smallest behavior change and the easiest to reason about:

  - **(a)** In `processPendingChange`, base the merge on `state.schemaValidationErrorSchema` (the un-`extraErrors`-merged base) instead of `state.errorSchema`, mirroring the approach used in `getStateFromProps` (around line 240).
  - **(b)** In `mergeErrors` / `validationDataMerge`, pass `'preventDuplicates'` so identical `__errors` strings don't accumulate.
  - **(c)** In `ArrayField.handleAddItem` and its siblings, only build `newErrorSchema` if the incoming `errorSchema` actually has keys (`Object.keys(errorSchema).length > 0`), so the empty-object default from `SchemaField` doesn't
  propagate as a truthy `newErrorSchema` and the buggy merge path is never entered.

### PR DESCRIPTION
**Pull request by JosephDoUrden**
### Reasons for making this change

`processPendingChange()` used `this.state.errorSchema` (which already contains merged `extraErrors`) as the base when re-merging `extraErrors` in the non-live-validate branch. Because `validationDataMerge` concatenates `__errors` arrays, each array mutation triggered an extra merge cycle that appended duplicate copies of any sibling field's `extraErrors`.

The fix uses `schemaValidationErrorSchema` (the un-merged AJV-only base) instead, which is consistent with how `getDerivedStateFromProps` and `getStateFromProps` handle the same merge pattern.

Fixes #5041

### Changes

- In `Form.processPendingChange()`, replaced `originalErrorSchema` with `schemaValidationErrorSchema` as the base passed to `mergeErrors()` in the `else if (!noValidate && newErrorSchema)` branch
- Added regression test: sibling field `extraErrors` must not accumulate after array item is added

### Checklist

- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -996,7 +996,11 @@ export default class Form<
       state = { formData: newFormData, ...liveValidation, customErrors };
     } else if (!noValidate && newErrorSchema) {
       // Merging 'newErrorSchema' into 'errorSchema' to display the custom raised errors.
-      const mergedErrors = this.mergeErrors({ errorSchema: originalErrorSchema, errors }, extraErrors, customErrors);
+      const mergedErrors = this.mergeErrors(
+        { errorSchema: schemaValidationErrorSchema as ErrorSchema<T>, errors },
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx]: I believe you may also want to update line 990 as well?

**Comment by heath-freenome** [comment]
@JosephDoUrden Looks like your tests are failing

**Review by heath-freenome — APPROVED** [review]
