### PR TITLE
fix: xss when rendering schema errors

### LINKED ISSUE #4254: XSS when rendering `uiSchema` validation error message
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

HTML tags inside JSON schema property names are output as HTML when rendered in error messages.

### Expected Behavior

HTML tags are disallowed or escaped when rendering JSON property names in error messages.

### Steps To Reproduce

1. Define a JSON schema

```
{
    "type": "object",
    "properties": {
        "xss<iframe srcdoc={'<script>alert(document.domain)</script>'}>": {
            "type": "string",
            "title": "Comment<a>link</a>"
        }
    },
}
``` 

2. Define a UI schema

```
{
  "xss": {
    "ui:widget": "textarea"
  },
  "ui:order": [
    "test"
  ]
}
```

3. The root schema is included in the error message and rendered as HTML.

### Environment

_No response_

### Anything else?

**Solution:** Pass in `disableParsingRawHTML` to the `<Markdown>` component to prevent HTML from being rendered in the error message. https://github.com/rjsf-team/react-jsonschema-form/blob/7f54d45cafeb50864ffb5002f8f924860cb78942/packages/core/src/components/fields/ObjectField.tsx#L267

[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InhzczxpZnJhbWUgc3JjZG9jPXsnPHNjcmlwdD5hbGVydChkb2N1bWVudC5kb21haW4pPC9zY3JpcHQ+J30+Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNvbW1lbnQ8YT5saW5rPC9hPiJ9fSwidW5ldmFsdWF0ZWRQcm9wZXJ0aWVzIjpmYWxzZX0sInVpU2NoZW1hIjp7InhzcyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJ1aTpvcmRlciI6WyJ0ZXN0Il19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

### PR DESCRIPTION
**Pull request by davidli16**
### Reasons for making this change

When rendering schema validation errors, the `jsonSchema` is rendered as HTML in the `<Markdown>` component. This opens up the potential for an XSS.

fixes #4254 

### Checklist

- [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
- [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
- [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

File: packages/core/src/components/templates/UnsupportedField.tsx [hunk 1]
```diff
@@ -27,7 +27,9 @@ function UnsupportedField<T = any, S extends StrictRJSFSchema = RJSFSchema, F ex
   return (
     <div className='unsupported-field'>
       <p>
-        <Markdown>{translateString(translateEnum, translateParams)}</Markdown>
+        <Markdown options={{ disableParsingRawHTML: true }}>
+          {translateString(translateEnum, translateParams)}
+        </Markdown>
```
Comment (heath-freenome) [inline packages/core/src/components/templates/UnsupportedField.tsx:32]:
```suggestion
        <Markdown options={{ disableParsingRawHTML: true }}>{translateString(translateEnum, translateParams)}</Markdown>
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -16,6 +16,12 @@ should change the heading of the (upcoming) version to include a major version b
 
 -->
 
+# 5.20.0
```
Comment (heath-freenome) [inline CHANGELOG.md:19]:
```suggestion
# 5.19.4
```

**Review by heath-freenome — COMMENTED** [review]
@davidli16 Can you also update the use of `Markdown` in `SchemaField` to be consistent? FYI, we applied some fixes so you likely will need to pull them down first

**Comment by davidli16** [comment]
Done! Thanks for the quick review.

File: packages/core/src/components/fields/SchemaField.tsx [hunk 3]
```diff
@@ -201,8 +201,12 @@ function SchemaFieldRender<T = any, S extends StrictRJSFSchema = RJSFSchema, F e
...
   const description = uiOptions.description || props.schema.description || schema.description || '';
 
-  const richDescription = uiOptions.enableMarkdownInDescription ? <Markdown>{description}</Markdown> : description;
-
+  const richDescription = uiOptions.enableMarkdownInDescription ? (
+    <Markdown options={{ disableParsingRawHTML: true }}>{description}</Markdown>
+  ) : (
+    description
+  );
+
```
Comment (heath-freenome) [inline packages/core/src/components/fields/SchemaField.tsx:209]:
```suggestion

```

**Review by heath-freenome — APPROVED** [review]

File: CHANGELOG.md [hunk 4]
```diff
@@ -18,6 +18,10 @@ should change the heading of the (upcoming) version to include a major version b
 
 # 5.19.4
 
+## @rjsf/core 
+
+- Fix XSS when rendering schema validation errors [#4254](https://github.com/rjsf-team/react-jsonschema-form/issues/2718)
```
Comment (heath-freenome) [inline CHANGELOG.md:23]:
```suggestion
- Fix XSS when rendering schema validation errors [#4254](https://github.com/rjsf-team/react-jsonschema-form/issues/2718)
  - NOTE: This will have potential consequences if you are using the [translateString](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#translatestring) feature and are trying to render HTML. Switching to [Markdown](https://www.markdownguide.org/) will solve your problems.
```
