### PR TITLE
fix 3708 - precompiledValidator resolve rootSchema before comparing s…

### LINKED ISSUE #3708: precompiledValidator validateFormData throwing error schema provided differs from precompiled schema.
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.7

### Current Behavior

[precompiledValidator.validateFormData()](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/validator-ajv8/src/precompiledValidator.ts#L140) throwing error that precompiled schema differs from provided schema even though the two schemas used are the same. This is happening because [Form.validate()](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/Form.tsx#L409) is first resolving the root schema then calling `validateFormData`.

The `precompiledValidator.rawValidation` needs to first resolve the rootSchema then compare the two

### Expected Behavior

Expected the two schemas to be equal and it validate the form. 

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cwendtxealth**
…chema input

### Reasons for making this change

fixes #3708 - precompiledValidator resolve rootSchema before comparing passed schema for validation. `Form.validate` resolves the root schema before calling `precompiledValidator.validateFormData`

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/validator-ajv8/src/precompiledValidator.ts [hunk 1]
```diff
@@ -101,7 +102,8 @@ export default class AJV8PrecompiledValidator<
    * @throws - Error when the schema provided does not match the base schema of the precompiled validator
    */
   rawValidation<Result = any>(schema: S, formData?: T): RawValidationErrorsType<Result> {
-    if (!isEqual(schema, this.rootSchema)) {
+    const resolvedRootSchema = retrieveSchema(this, this.rootSchema, this.rootSchema, formData);
```
Comment (heath-freenome) [inline packages/validator-ajv8/src/precompiledValidator.ts:105]: Odd, I swear I gave feedback on this. Rather than retrieving the root schema every time perhaps do this in the constructor only once?

Comment (cwendtxealth) [reply packages/validator-ajv8/src/precompiledValidator.ts:105]: yeah, I think that will work, updating now

File: packages/validator-ajv8/src/precompiledValidator.ts [hunk 2]
```diff
@@ -101,7 +109,7 @@ export default class AJV8PrecompiledValidator<
    * @throws - Error when the schema provided does not match the base schema of the precompiled validator
    */
   rawValidation<Result = any>(schema: S, formData?: T): RawValidationErrorsType<Result> {
-    if (!isEqual(schema, this.rootSchema)) {
+    if (!isEqual(schema, this.resolvedRootSchema)) {
```
Comment (heath-freenome) [inline packages/validator-ajv8/src/precompiledValidator.ts:112]: Does the `isValid()` call get the `rootSchema` or the `resolvedRootSchema`? If you aren't sure, maybe check both?

Comment (cwendtxealth) [reply packages/validator-ajv8/src/precompiledValidator.ts:112]: looking at the code it seems like `isValid` is called by the `rootSchema` without being resolved. All the components go through `SchemaUtils` which is initialized with the "raw" schema. So I think its fine to leave isValid using the `rootSchema`

**Review by heath-freenome — APPROVED** [review]
