### PR TITLE
Use ui:emptyValue for SelectWidget

### LINKED ISSUE #1041: ui:emptyValue does not work with selects
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

`ui:emptyValue` is ignored for select widgets, requiring messy workarounds to resolve due to the way that the empty value option is injected.

The workaround that works is to specify a non-falsy empty value (e.g. `"0"`) as the default for the form input (required in order to prevent the empty `<option>` from being injected), add your own empty value to the enum / enumNames (e.g. `"0"` as the value, "None" as the name), then reprocess to treat that empty value appropriately in the code dealing with the form (if `"0"` is OK then that's fine, but if you want a falsy default, e.g. an empty string, more work is required).

Obviously this is much more complex than just specifying `ui:emptyValue` with the desired value.

### Steps to Reproduce

1. Specify an enum field
1. Specify it as a select field
1. Give it a `ui:emptyValue` setting
1. Select the empty option - the `ui:emptyValue` is not used

[Simple playground reproduction](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImlkIjp7ImRlc2NyaXB0aW9uIjoiQW4gb3B0aW9uYWwgYWdlbnQgZm9yIHRoaXMgZG9jdW1lbnQuIiwiZW51bSI6WyIxIiwiMiJdLCJlbnVtTmFtZXMiOlsiSmFuZSBBZ2VudCIsIkpvZSBBZ2VudCJdLCJ0aXRsZSI6IkFnZW50IiwidHlwZSI6InN0cmluZyJ9fSwidHlwZSI6Im9iamVjdCJ9LCJ1aVNjaGVtYSI6eyJpZCI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJObyBhZ2VudCIsInVpOndpZGdldCI6InNlbGVjdCJ9fX0=)

#### Expected behavior

The formData value should be the `ui:emptyValue` when the empty option is selected.

#### Actual behavior

There is no formData value for the field when the empty option is selected.

### Version

Current playground version.

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

- This is a reimplementation of https://github.com/rjsf-team/react-jsonschema-form/pull/2251
- Fixes #1041

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/processSelectValue.ts [hunk 1]
```diff
@@ -1,22 +1,28 @@
...
-export default function processSelectValue(schema: RJSFSchema, value?: any) {
+export default function processSelectValue<T = any, F = any>(
+  schema: RJSFSchema,
+  value?: any,
+  options?: UIOptionsType<T, F>
+) {
   const { enum: schemaEnum, type, items } = schema;
   if (value === "") {
-    return undefined;
+    return (options && options.emptyValue) || undefined;
```
Comment (heath-freenome) [inline packages/utils/src/processSelectValue.ts:25]: Switch to a ternary if options.emptyValue is not undefined

**Review by nickgros — APPROVED** [review]
Approved pending change to ternary
