### PR TITLE
Fix 3296 by adjusting buttons location for the array field toolbar

### LINKED ISSUE #3296: Miss aligned array buttons for most themes
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.0.0-beta.13

### Current Behavior

Even in the "Arrays" fiddle provided https://rjsf-team.github.io/react-jsonschema-form/ the buttons do not align with the input fields: 
image

Same goes for our usage: 
image

### Expected Behavior

Buttons should be aligned and their height should match the height of the input field:

image

### Steps To Reproduce

1. Go to your own showcase, but happens everywhere with bootstrap-4

### Environment

```markdown
- OS: Windows
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixed #3296 by updating `ArrayFieldItemTemplateProps` to add `displayLabel` and `hasDescription` and using them in the themes to adjust buttons location
- In `@rjsf/utils`, updated `ArrayFieldItemTemplateProps` to add `displayLabel` and `hasDescription` flags
- In `@rjsf/core`, updated `ArrayField` to compute and pass `displayLabel` and `hasDescription` flags
  - Updated `ArrayFieldItemTemplate` to use `displayLabel` and `hasDescription` to adjust buttons location
  - Also fixed bug where `StringField` was not using the `title` passed to it as found in `mantine` theme
- In `@rjsf/antd`, updated `ArrayFieldItemTemplate` and `ArrayFieldTemplate` to adjust sizes and buttons location using `displayLabel` and `hasDescription`
- In `@rjsf/chakra-ui`, updated snapshots due to `StringField` fix
- In `@rjsf/daisyui`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel` and `hasDescription`
  - Also updated `WrapIfAdditionalTemplate` and `BaseInputTemplate` to make the inputs full width
  - Also updated `FieldTemplate` to render the `description` which was missing in the theme
- In `@rjsf/fluentui-rc`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel`
  - Also updated `WrapIfAdditionalTemplate` to add `flexGrow` to allow the array item fields to grow properly for non-container elements
- In `@rjsf/mantine`, updated `utils.ts` to add `label` to the cleanup fields to filter it from the `uiOptions`
  - Also updated `BaseInputTemplate` to display `description` which was missing in the theme
  - Also updated `ArrayFieldTitleTemplate` to support the `optionalData`
- In `@rjsf/mui`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel` and `hasDescription`
- In `@rjsf/primereact`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel`
- In `@rjsf/react-bootstrap`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel` and `hasDescription`
  - Also, updated `ArrayFieldTemplate` to improve it's responsiveness in relation to the `ArrayFieldItemTemplate` changes
- In `@rjsf/semantic-ui`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel` and `hasDescription`
- In `@rjsf/shadcn`, updated `ArrayFieldItemTemplate` to adjust buttons location using `displayLabel` and `hasDescription`
  - Also updated `ArrayFieldTemplate` to add `justify-end` to the `AddButton` rendering
- Updated all snapshots due to above changes
- Updated `uiSchema.md` in the docs to document the new `enableMarkdownInHelp` flag from previous PR
- Updated the `CHANGELOG.md` accordingly

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

Antd:

https://github.com/user-attachments/assets/5c19039c-5b3b-4ff2-b1cb-3f5fdb5b11dd

Chakra-ui:

https://github.com/user-attachments/assets/450fbbdc-13d0-4c44-9fb4-602d0a79dcb4

core:

https://github.com/user-attachments/assets/aabda0ae-fdf5-457a-a7bf-554bb5631562

daisyui:

https://github.com/user-attachments/assets/f67ee25f-fc03-4429-a289-7924a60c9a11

fluentui:

https://github.com/user-attachments/assets/d1a85a21-6e84-43b2-89b8-1b8e5f0f55aa

mantine:

https://github.com/user-attachments/assets/d5dc7108-1253-4ce6-9e86-dcfe52ddfb44

mui:

https://github.com/user-attachments/assets/fcb6788a-28a7-4b81-a4a4-f736c0b36047

primereact:

https://github.com/user-attachments/assets/5ed4b22d-f33f-48bc-8018-41df920c63c8

react-bootstrap:

https://github.com/user-attachments/assets/0a36d4c9-f246-4fc7-838d-13dadfe79763

semantic-ui:

https://github.com/user-attachments/assets/47af8f3c-abcc-47c5-9a7c-2f6ff1e31dde

shadcn:

Uploading shadcn.mov…

### CODE REVIEW

File: packages/mantine/src/templates/BaseInputTemplate.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ export default function BaseInputTemplate<
   } = props;
 
   const inputProps = getInputProps<T, S, F>(schema, type, options, false);
+  const description = options.description || schema.description;
```
Comment (heath-freenome) [inline packages/mantine/src/templates/BaseInputTemplate.tsx]:
```suggestion
  const description = hideLabel ? undefined : options.description || schema.description;
```

File: packages/daisyui/src/templates/FieldTemplate/FieldTemplate.tsx [hunk 2]
```diff
@@ -77,7 +77,7 @@ export default function FieldTemplate<
       uiSchema={uiSchema}
       registry={registry}
     >
-      <div className={`field-template mb-3 ${classNames || ''}`} {...divProps}>
+      <div className={`field-template mb-3${classNames || ''}`} {...divProps}>
```
Comment (nickgros) [inline packages/daisyui/src/templates/FieldTemplate/FieldTemplate.tsx]: probably still need this space?
```suggestion
      <div className={`field-template mb-3 ${classNames || ''}`} {...divProps}>
```

Comment (heath-freenome) [reply packages/daisyui/src/templates/FieldTemplate/FieldTemplate.tsx]: Yeah, good catch!
