### PR TITLE
fix: Cast the value as an Array in CheckboxesWidget

### LINKED ISSUE #2141: CheckboxesWidget should ensure that the value is an Array
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

`CheckboxesWidget` assumes that the `value` is an Array but does not check the type of the value.
At runtime, the widget will throw an exception when a value is selected or deselected.

### Steps to Reproduce

See the codesandbox example: https://codesandbox.io/s/checkboxeswidget-with-non-array-value-react-jsonschema-form-qi96b?file=/src/App.js

Important parts:

```js
var formData = {
  typeArticle: "Essai"
};
```

#### Expected behavior

The widget should check that the value is an Array. If not, the widget could either create an Array from the value or ignore the value.

#### Actual behavior

Throws an exception when the user is trying to select or deselect a value.
Please note that the value passed as a String will be correctly selected.

In the above example, the value "Essai" is selected (even if the value was `Essai` and not `["Essai"]`):

selected

### Version

`2.4.0`

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #2141 by reimplementing #2142 for all themes but `antd`

When the value passed to the `CheckboxesWidget` was a single value rather than an array, things would break in the control
- Updated the `CheckboxesWidget` in all themes but `antd` (which uses simpler logic) to fix ensure the value used in the helper functions is an array
- Added a test in `ArrayField_test.ts` that verifies the fix
- Updated the snapshot in `bootstrap-4` which showed an issue when the value string contained an element of the enumeration value rather than the whole value
- Refactored the common `selectValue` and `deselectValue` functions used in `CheckboxesWidget` into `@rjsf/utils` and used them in the `CheckboxesWidget`
- Updated the `CHANGELOG.md` accordingly

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 1]
```diff
@@ -17,16 +17,16 @@ const styles_red = {
...
   // As inserting values at predefined index positions doesn't work with empty
   // arrays, we need to reorder the updated selection to match the initial order
-  return updated.sort((a: any, b: any) => all.indexOf(a) > all.indexOf(b));
+  return updated.sort((a, b) => Number(all.indexOf(a) > all.indexOf(b)));
 };
 
-const deselectValue = (value: any, selected: any) => {
+const deselectValue = (value: any, selected: any[]) => {
   return selected.filter((v: any) => v !== value);
 };
```
Comment (nickgros) [inline packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:31]: Used in multiple packages, consider moving to utils

File: packages/semantic-ui/src/CheckboxesWidget/CheckboxesWidget.tsx [hunk 2]
```diff
@@ -12,19 +12,19 @@ import { getSemanticProps } from "../util";
 
 function selectValue<S extends StrictRJSFSchema = RJSFSchema>(
   value: EnumOptionsType<S>["value"],
-  selected: any,
+  selected: any[],
   all: any[]
```
Comment (nickgros) [inline packages/semantic-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:16]: Can we use these more accurate types for the other declarations of this function (or if moving to utils, use these types there)? Same for `deselectValue`.

**Review by nickgros — CHANGES_REQUESTED** [review]

File: packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx (hunk 1 above)
Comment (heath-freenome) [reply packages/fluent-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:31]: Will do!

File: packages/semantic-ui/src/CheckboxesWidget/CheckboxesWidget.tsx (hunk 2 above)
Comment (heath-freenome) [reply packages/semantic-ui/src/CheckboxesWidget/CheckboxesWidget.tsx:16]: Yeah, I'll pull this one into utils

**Review by nickgros — APPROVED** [review]
