### PR TITLE
Fix #2721 and #2724

### LINKED ISSUE #2721: Errors with version 4.0 and material-ui 4
Installing version 4.0 @rjsf/core and @rjsf/material-ui, alongside with my material-ui 4, I get the warning

`npm WARN @rjsf/material-ui@4.0.0 requires a peer of @rjsf/core@^3.0.0 but none is installed. You must install peer dependencies yourself.`

(and indeed, in the package.json of @rjsf/material-ui one finds "@rjsf/core@^3.0.0" , that seems wrong)

Furthermore, if I ignore the install warning , npm start gives compile warnings

```
./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@mui/icons-material' in 'C:\wk\pcnt\trake\trake-ui\node_modules\@rjsf\material-ui\dist'

./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@mui/material' in 'C:\wk\pcnt\trake\trake-ui\node_modules\@rjsf\material-ui\dist'   
```

... and when runnning I get on console

```
Error: Cannot find module '@mui/material'
    at webpackMissingModule (material-ui.esm.js:1256:1)
    at Module../node_modules/@rjsf/material-ui/dist/material-ui.esm.js (material-ui.esm.js:1256:1)
```

Using react 17 and Node 14 with

@material-ui/core: 4.12.3
@material-ui/system: 4.12.1
@material-ui/icons 4.11.2
@rjsf/core: 4.0.0
@rjsf/material-ui: 4.0.0

### LINKED ISSUE #2724: MuiComponentContext not exported
Hi, in order to wrap or override widgets such as `CheckboxWidget` and `CheckboxesWidget` it would be great if this lib exported the following:

`MuiComponentContext`

Which is constructed from these types (which are not exported either):
`MaterialUIContextProps`
`Mui5ContextProps`

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change
Fixes #2724 and (hopefully) #2721

- Updated the `MaterialUIContext` and `Mui5Context` to eliminate the `console.log()` entirely
- Updated the `MaterialUIContextProps` and `Mui5ContextProps` to use `require` to import the libraries to avoid issues with exporting the `MaterialComponentContext`
- Updated the `index.ts` to export the `MaterialComponentContext`

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/material-ui/src/Theme/MaterialUIContextProps.ts [hunk 1]
```diff
@@ -1,4 +1,14 @@
-import {
+/** Use require for loading these libraries in case they are not available in order to perform a useful fallback
+ */
+let mui;
```
Comment (epicfaace) [inline packages/material-ui/src/Theme/MaterialUIContextProps.ts:3]:
```suggestion
let mui = {};
```

File: packages/material-ui/src/Theme5/Mui5ContextProps.ts [hunk 2]
```diff
@@ -1,4 +1,14 @@
-import {
+/** Use require for loading these libraries in case they are not available in order to perform a useful fallback
+ */
+let mui;
```
Comment (epicfaace) [inline packages/material-ui/src/Theme5/Mui5ContextProps.ts:3]:
```suggestion
let mui = {};
```

**Review by epicfaace — APPROVED** [review]

**Comment by epicfaace** [comment]
@heath-freenome do you mind making another PR to update the changelog? forgot about that.

**Comment by szubster** [comment]
Any timeline for release with this fix?

**Comment by gabeaudick** [comment]
+1 on release timeline 😋
