### PR TITLE
Bugfix disable submit button

### LINKED ISSUE #3264: Disabling the form should disable the submit button as well.
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.3

### Current Behavior

When I pass the `disabled` props, all inputs are disabled, but the form can still be submitted by pressing the submit button, which is still enabled. 

### Expected Behavior

The submit button should be disabled. 

### Steps To Reproduce

https://codesandbox.io/s/lucid-dawn-k56bdt?file=/src/App.js (4.2.3)

 

### Environment

```markdown
See sandbox
```

### Anything else?

Similar issues: 

https://github.com/rjsf-team/react-jsonschema-form/issues/854 - suggestion - pass in empty div as children  to remove the submit buttton 

Another option is to pass the `uiSchema` prop in with the `ui:submitButtonOptions.props.disabled` when you are trying to disable the form. 

P.S Fantastic work with this library. This thing is great.

### PR DESCRIPTION
**Pull request by dwjohnston**
### Reasons for making this change
Fixes #3264 
Also fixes an issue with the Playground where the 'Disable whole form' button does not work. 

The disabled button  can be controlled via the `ui:submitButtonProps` properties, or the top level `disabled` property.  The logic I've gone for is a simple OR operator between these values. You could argue that the `ui:submitButtonProps` should always take precedence, even if set to false, but I can't think of a scenario where that makes sense.  

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -811,7 +812,7 @@ export default class Form<
           disabled={disabled}
           readonly={readonly}
         />
-        {children ? children : <SubmitButton uiSchema={uiSchema} registry={registry} />}
+        {children ? children : <SubmitButton uiSchema={uiSchema} registry={registry} disabled={disabled} />}
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:815]: Rather than going through all of this, why not just update the `uiSchema` that gets passed in directly to the `SubmitButton`? Something like:
```
// Add SUBMIT_BTN_OPTIONS_KEY and UI_OPTIONS_KEY to the import for @rjsf/utils
let { [SUBMIT_BTN_OPTIONS_KEY]: submitOptions = {} } = getUiOptions<T, S, F>(uiSchema);
if (disabled) {
  submitOptions = { ...submitOptions, submitButtonProps: { ...submitOptions.submitButtonProps, disable: true } };
}
const submitUiSchema = { [UI_OPTIONS_KEY]: { [SUBMIT_BTN_OPTIONS_KEY]: submitOptions } };
```

Then pass 
```suggestion
        {children ? children : <SubmitButton uiSchema={submitUiSchema} registry={registry} />}
```

It saves a whole bunch of coding and doesn't require updating all of the `SubmitButton` implementations in all themes and changing any types

**Review by heath-freenome — CHANGES_REQUESTED** [review]

**Comment by heath-freenome** [comment]
@dwjohnston Have you had a chance to look over my feedback?

File: packages/core/src/components/Form.tsx (hunk 1 above)
Comment (dwjohnston) [reply packages/core/src/components/Form.tsx:815]: Yes, I did consider this, and I think you're right. 

I was looking at doing something here: https://github.com/rjsf-team/react-jsonschema-form/blob/8ee7d472fa7ef9fdd79113aeff9e012e6bdc6078/packages/core/src/components/Form.tsx#L299

What put me off was around the handling of 'what if the uiSchema exists, what if doesn't, what if nested properties exist....' and then also you've got that state.schemaUtils stuff, which I wasn't sure about. 

But yeah, I think you're right, much nicer than some kind of cascading change. I'll make that change.

Comment (heath-freenome) [reply packages/core/src/components/Form.tsx:815]: Using the `getUiOptions()` function will mitigate lack of a `uiSchema` and the two possibilities of `ui:submitButtonOptions` vs the `"ui:options": { submitButtonOptions }`. SchemaUtils do not deal with the `submitButtonOptions`. Also in the suggestion I gave, it should handle the nested options or not case as well

File: packages/playground/src/app.jsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ const liveSettingsSchema = {
   type: 'object',
   properties: {
     liveValidate: { type: 'boolean', title: 'Live validation' },
-    disable: { type: 'boolean', title: 'Disable whole form' },
+    disabled: { type: 'boolean', title: 'Disable whole form' },
```
Comment (heath-freenome) [inline packages/playground/src/app.jsx:20]: This file was recently converted to typescript and these contents moved into a different file

File: packages/playground/src/app.jsx [hunk 3]
```diff
@@ -480,6 +480,8 @@ class Playground extends Component {
 
     return (
       <div className='container-fluid'>
+
+        {JSON.stringify(liveSettings)}
```
Comment (heath-freenome) [inline packages/playground/src/app.jsx:484]: I'm not sure you meant to leave this in here? It seems odd to render them as a string

File: packages/core/src/components/Form.tsx [hunk 4]
```diff
@@ -296,7 +296,20 @@ export default class Form<
...
+          ...rawUiSchema,
+          'ui:submitButtonOptions': {
+            ...rawUiSchema['ui:submitButtonOptions'],
+            props: {
+              ...rawUiSchema['ui:submitButtonOptions']?.props,
+              disabled: true,
+            },
+          },
+        }
+      : rawUiSchema;
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:312]: There is one problem with this approach. `ui:submitButtonOptions` could also be defined as `ui:options: { submitButtonOptions } `; The approach I suggested of providing a separately constructed `uiSchema` just to the `SubmitButton` handles either situation.

I would revert this whole change since the only use for `submitButtonOptions` really is the `SubmitButton` and move the code down in the the render and pass a one-off set of props just to the `SubmitButton`

File: packages/core/src/components/templates/ButtonTemplates/SubmitButton.tsx [hunk 5]
```diff
@@ -11,6 +11,7 @@ export default function SubmitButton<
   if (norender) {
     return null;
   }
+
```
Comment (heath-freenome) [inline packages/core/src/components/templates/ButtonTemplates/SubmitButton.tsx:14]: I would suggest just reverting this change since it really isn't necessary to fixing the bug

File: packages/core/src/components/Form.tsx [hunk 6]
```diff
@@ -815,6 +829,7 @@ export default class Form<
           disabled={disabled}
           readonly={readonly}
         />
+
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:832]: Something like:
```suggestion
// Add SUBMIT_BTN_OPTIONS_KEY and UI_OPTIONS_KEY to the import for @rjsf/utils
let { [SUBMIT_BTN_OPTIONS_KEY]: submitOptions = {} } = getUiOptions<T, S, F>(uiSchema);
if (disabled) {
  submitOptions = { ...submitOptions, submitButtonProps: { ...submitOptions.submitButtonProps, disable: true } };
}
const submitUiSchema = { [UI_OPTIONS_KEY]: { [SUBMIT_BTN_OPTIONS_KEY]: submitOptions } };
```

Then pass 
```
        {children ? children : <SubmitButton uiSchema={submitUiSchema} registry={registry} />}
```

File: packages/playground/src/components/Playground.tsx [hunk 7]
```diff
@@ -32,7 +32,7 @@ const liveSettingsSchema: RJSFSchema = {
   type: 'object',
   properties: {
     liveValidate: { type: 'boolean', title: 'Live validation' },
-    disable: { type: 'boolean', title: 'Disable whole form' },
+    disabled: { type: 'boolean', title: 'Disable whole form' },
```
Comment (heath-freenome) [inline packages/playground/src/components/Playground.tsx:35]: This got fixed in another PR

File: CHANGELOG.md [hunk 8]
```diff
@@ -60,7 +61,7 @@ should change the heading of the (upcoming) version to include a major version b
 
 - Converted the `playground` to use Typescript, including some refactoring of code to make that job easier
 - Updated the `custom-templates` documentation to add `errorSchema` to the props for `ObjectFieldTemplate`
-
+- Fixes bug where the 'Disable whole form' button did not work.
```
Comment (heath-freenome) [inline CHANGELOG.md:64]: You can also revert this as it got fixed in another PR

File: packages/core/src/components/Form.tsx [hunk 9]
```diff
@@ -350,6 +352,7 @@ export default class Form<
       props.idPrefix,
       props.idSeparator
     );
+
     const nextState: FormState<T, S, F> = {
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:356]: Let's just restore this back to what it was
```suggestion
    );
    const nextState: FormState<T, S, F> = {
```

File: CHANGELOG.md [hunk 10]
```diff
@@ -50,6 +50,7 @@ should change the heading of the (upcoming) version to include a major version b
 - Updated `FileWidget` to pass false for `required` once a value has been specified, fixing [#3504](https://github.com/rjsf-team/react-jsonschema-form/issues/3504)
 - Updated `ObjectField` to pass the `errorSchema` to the `ObjectFieldTemplate` to allow custom templates access to the errors
 - Centralized snapshot tests from each theme into `core`, adding snapshots tests for `core` as well
+- Updated `Form` to include the top `disabled` property in the `ui:submitButtonOptions` so the submit button will be disabled when the whole form is disabled. Fixes [#3264](https://github.com/rjsf-team/react-jsonschema-form/issues/3264).
```
Comment (heath-freenome) [inline CHANGELOG.md:53]: Can you move this to be under the 5.5.1 section now?

**Review by heath-freenome — APPROVED** [review]
