### PR TITLE
Rewrite mergeSchemas to fix schema dependencies merging

### LINKED ISSUE #998: Schema Dependencies Merged Incorrectly
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When merging schema with dependencies, enums are appended instead of replaced.

### Steps to Reproduce

1. Visit [this playground example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlMSI6IkZPTyJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidHlwZTEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVHlwZSAxIiwiZW51bSI6WyJGT08iLCJCQVIiLCJCQVoiXX0sInR5cGUyIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlR5cGUgMiIsImVudW0iOlsiR1JFRU4iLCJCTFVFIiwiUkVEIl19fSwiZGVwZW5kZW5jaWVzIjp7InR5cGUxIjp7InByb3BlcnRpZXMiOnsidHlwZTEiOnsiZW51bSI6WyJGT08iXX0sInR5cGUyIjp7ImVudW0iOlsiR1JFRU4iXX19fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19)
2. Select "FOO" for Type 1
3. Notice form presents errors `enum should NOT have duplicate items`

image

#### Expected behavior

The form should have no errors as I expect the list of valid enums to be _replaced_ with `["FOO"]`. Not that `"FOO"` will be appended to list of enums. This appears to be occurring in [`mergeSchemas util`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L473)

#### Actual behavior

merged schema should consist only of a single enum. This is the behavior I see when validating the schema on https://www.jsonschemavalidator.net/.

output:
image

But the schema created by react-jsonschema-form contains 4 enums, with two being duplicate: `["FOO", "BAR", "BAZ", "FOO"]`

### Version
1.0.4

### PR DESCRIPTION
**Pull request by epicfaace**
### Reasons for making this change

Fixes #998. This makes sure that when dependencies are merged with the main schema, only arrays under the key `required` are merged. Other arrays are overwritten.

With this PR, `mergeSchemas` uses lodash's `union` operator to merge required arrays, so that the arrays do not have duplicate values when merged.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: test/utils_test.js [hunk 1]
```diff
@@ -1058,6 +1059,94 @@ describe("utils", () => {
     });
   });
 
+  describe("mergeSchemas()", () => {
+    it("should't mutate the provided objects", () => {
```
Comment (epicfaace) [inline test/utils_test.js]:
```suggestion
    it("shouldn't mutate the provided objects", () => {
```

File: src/utils.js [hunk 2]
```diff
@@ -760,8 +760,28 @@ function withExactlyOneSubschema(
...
+// values under the "required" keyword.
+export function mergeSchemas(obj1, obj2) {
+  var acc = Object.assign({}, obj1); // Prevent mutation of source object.
+  return Object.keys(obj2).reduce((acc, key) => {
+    const left = obj1 ? obj1[key] : {},
+      right = obj2[key];
+    if (obj1 && obj1.hasOwnProperty(key) && isObject(right)) {
+      acc[key] = mergeSchemas(left, right);
+    } else if (
+      key === "required" &&
```
Comment (edi9999) [inline src/utils.js]: Can you add some kind of check for the parent property ?

I mean techically speaking, only `properties.required` field should be overwritten, not all fields with `required` (I know it is most unlikely, so if you think this test is enough that would be ok for me)

**Comment by travisdahl** [comment]
pulled it down and tested in our project, fixes our problem 👍

**Comment by tsunamiq** [comment]
it's looking good! Appreciate all the work on this; you guys are a life saver! 

@epicfaace do you have an idea of when you'll have time to merge the pr? Just curious to know so I can work on scheduling on my side. Again, appreciate all the help with this issue!

File: src/utils.js (hunk 2 above)
Comment (epicfaace) [reply src/utils.js]: I've added a check to make sure that `obj1` or `obj2` are objects. Not sure if that's the right logic, though, feedback welcome!

**Comment by epicfaace** [comment]
@edi9999 this PR should be ready for review now. I made a few changes:
- add an integration test
- make sure it uses lodash's `union` operator to merge `required` arrays, so that the arrays do not have duplicate values when merged
- merge the `required` attribute only if one of the schemas is an object type

File: src/utils.js (hunk 2 above)
Comment (edi9999) [reply src/utils.js]: I've tried with this on your PR, and it still works : 

```
obj1 && obj2 && getSchemaType(obj1) === "object" &&
        getSchemaType(obj2) === "object"
```

I think this is more correct to check for both the schematypes of both objects.

**Comment by edi9999** [comment]
The integration test looks good to me !

File: src/utils.js (hunk 2 above)
Comment (edi9999) [reply src/utils.js]: you've written `getSchematype(obj1) === "object" || getSchemaType(obj2) === "object"`.

Is the `or` on purpose ? 

To me it seems that it should be an `and` (`&&`), that way only two objects schemas of type object which have a required property will be merged that way ?

Comment (epicfaace) [reply src/utils.js]: I was thinking about the case in which you want to merge, say, `{properties: {...}, required: ["a"]}` and `{title: "a"}`. In this case, the second schema is not unambiguously an object, although the first schema is. It would still be nice to merge the two schemas together, though. This would only work if we use `||` instead of `&&`.

Comment (edi9999) [reply src/utils.js]: Ok
