### PR TITLE
Bug: schema with conditions where switching to then/else subschemas did not reflect the actual validation errors in the onChange event.

### LINKED ISSUE #4249: Live validation / onChange errors issue
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

when schema contains if/then/else and a user's changes activates then/else subschemas, the live validation works but errors in the onChange event are not reflect the real ones

### Expected Behavior

errors in the onChange event should always reflect the form state

### Steps To Reproduce

Thus, open the repo https://github.com/AlimovSV/rjsf-onchange-issue and click checkbox, you will see error message in the UI but console.log in the onChange event handler displays empty array:

Next uncheck the checkbox you will see that form becomes valid but console log displays errors from the previous form state:

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abdalla-rko**
### Reasons for making this change

Fixes #4249 

#### Additional improvement
The `ajv.compile` method is costly in terms of performance when it has to recompile on `onChange` or on `props` change. To improve this we now provide the same `retrievedSchema` (by reference) unless it changes in which case we provide a new `retrievedSchema`. This ensures that AJV retrieves the schema from the cache unless the retrievedSchema content changes then it will recompile. 

I've run the test with a very large schema(link attached) the compile used to take 640ms and now it takes 40ms. You can see the performance improvement if you load the link in the attached file in the main branch and compare it to this feature branch. You'll notice by typing in any field that it is massively slow on the main branch.
[rjsf-playground-link (2).txt](https://github.com/user-attachments/files/18255709/rjsf-playground-link.2.txt)

### Checklist

- [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -703,6 +708,19 @@ export default class Form<
     this.setState(state as FormState<T, S, F>, () => onChange && onChange({ ...this.state, ...state }, id));
   };
 
+  /**
+   * Returns if the retrievedSchema has changed the new retrievedSchema,
+   * Else the old retrievedSchema to persist  reference.
+   * -  This ensures that AJV retrieves the schema from the cache when it has not changed,
+   *    avoiding the performance cost of recompiling the schema.
+   * @param retrievedSchema The new retrieved schema.
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:716]:
```suggestion
   * If the retrievedSchema has changed the new retrievedSchema is returned.
   * Otherwise, the old retrievedSchema is returned to persist the reference.
   * -  This ensures that AJV retrieves the schema from the cache when it has not changed,
   *    avoiding the performance cost of recompiling the schema.
   *
   * @param retrievedSchema The new retrieved schema.
```

File: packages/core/src/components/Form.tsx [hunk 2]
```diff
@@ -703,6 +708,19 @@ export default class Form<
...
+   * @returns The new retrieved schema if it has changed, else the old retrieved schema.
+   */
+  private updateRetrievedSchema = (retrievedSchema: S) => {
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:719]:
```suggestion
  private updateRetrievedSchema(retrievedSchema: S) {
```

**Review by heath-freenome — APPROVED** [review]
