### PR TITLE
Fix: #3922 by adding a condition to the spread operator.

### LINKED ISSUE #3922: Possible bug with anyOf/oneOf when the selected schema changes from type:string to type:object
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.1.0

### Current Behavior

Given an **anyOf** or a **oneOf** composition schema with two options. First an object with one property of type string and second just a string value. When option 2 has a value (example `"adsads"`) and the dropdown is changed to the option 1. The value is set to  this: 
```json
{
  "0": "a",
  "1": "d",
  "2": "s",
  "3": "a",
  "4": "d",
  "5": "s"
}
```
It continues to keep those added properties after a value is give to option 1 string property:
```json
{
  "0": "a",
  "1": "d",
  "2": "s",
  "3": "a",
  "4": "d",
  "5": "s",
  "foo": "werwer"
}
```
Even if the `"additionalProperties": false` is set the an error will not be presented.

image

The scenario will work as expected if option 2 has another type of value, I tested [number](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6NCwic2NoZW1hIjp7ImFueU9mIjpbeyJ0aXRsZSI6Ik9wdGlvbiAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0aXRsZSI6Ik9wdGlvbiAyIiwidHlwZSI6Im51bWJlciJ9XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19) and [boolean](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6dHJ1ZSwic2NoZW1hIjp7ImFueU9mIjpbeyJ0aXRsZSI6Ik9wdGlvbiAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0aXRsZSI6Ik9wdGlvbiAyIiwidHlwZSI6ImJvb2xlYW4ifV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==).

### Expected Behavior

After switching to the Option 1, the value should be and empty object `{}`.

### Steps To Reproduce

1. Open the [setup](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImFkc2FkcyIsInNjaGVtYSI6eyJhbnlPZiI6W3sidGl0bGUiOiJPcHRpb24gMSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZvbyI6eyJ0eXBlIjoic3RyaW5nIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LHsidGl0bGUiOiJPcHRpb24gMiIsInR5cGUiOiJzdHJpbmcifV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)
2. Select Option 1
3. Type a value for "foo"

### Environment

```markdown
- OS: Fedora 38 (Workstation Edition)
- Node: v18.16.0
- npm: v9.5.1
```

### Anything else?

I narrow it down to the result of the function `schemaUtils.sanitizeDataForNewSchema(newOption, oldOption, formData)` in line 122 of the MultiSchemaField.tsx file. 

https://github.com/rjsf-team/react-jsonschema-form/blob/42e138c5d6785e84aa4500c83bf70af8c001236c/packages/core/src/components/fields/MultiSchemaField.tsx#L122

After that function is executed, `newFormData` takes that value and later on is used to update the field value in line 128. I'll update later if I'm able to find out more about this issue.

### PR DESCRIPTION
**Pull request by lindolo25**
### Reasons for making this change

fixes #3922 by adding a condition to the spread operator when creating the newFormData in sanitizeDataForNewSchema()

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/schema/sanitizeDataForNewSchema.ts [hunk 1]
```diff
@@ -137,7 +137,7 @@ export default function sanitizeDataForNewSchema<
     });
 
     newFormData = {
-      ...data,
+      ...(typeof data == 'string' || Array.isArray(data) ? {} : data),
```
Comment (heath-freenome) [inline packages/utils/src/schema/sanitizeDataForNewSchema.ts:140]: Why not spread the array?

Comment (heath-freenome) [inline packages/utils/src/schema/sanitizeDataForNewSchema.ts:140]: This would also work I believe...
```suggestion
      ...(typeof data == 'string' || Array.isArray(data) ? undefined : data),
```

Comment (heath-freenome) [reply packages/utils/src/schema/sanitizeDataForNewSchema.ts:140]: Also, can you update the `CHANGELOG.md`

Comment (lindolo25) [reply packages/utils/src/schema/sanitizeDataForNewSchema.ts:140]: Hi @heath-freenome , Thanks for the feedback! Yes your suggestion will work as well, I'll add it to the PR. Also I haven't check the tests for this file, I'll add specific cases for this scenario if needed, that's why I kept the PR as a draft.

**Comment by lindolo25** [comment]
Hi @heath-freenome, thanks again for the recommendation. I updated tests and the changelog. this PR is ready for review.

File: CHANGELOG.md [hunk 2]
```diff
@@ -15,6 +15,13 @@ it according to semantic versioning. For example, if your PR adds a breaking cha
 should change the heading of the (upcoming) version to include a major version bump.
 
 -->
+# 5.14.1
```
Comment (heath-freenome) [inline CHANGELOG.md:18]: We just released 5.14.1 so bumping this
```suggestion
# 5.14.2
```

Comment (lindolo25) [reply CHANGELOG.md:24]: Hi @heath-freenome , I just committed the requested change.

**Review by heath-freenome — APPROVED** [review]
