### PR TITLE
Fix #4197 in various themes by showing empty option in SelectWidget when appropriate

### LINKED ISSUE #4197: Empty item in selectbox for enum is not visible
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.x

### Current Behavior

Although the enum property in the model is nullable and not required, empty value for selection is missing.

Nowadays there is no easy way for user to deselect already selected value. We use 'blank space' as an empty item and it's barely visible and also it's not a perfect engineering solution.

It's working for other than Material-UI 
eg: working combobox: 
In  [RJSF demo](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImN0b1RlYW0iOnsidWk6ZW1wdHlWYWx1ZSI6IiIsIm51bGxhYmxlIjp0cnVlLCJhbGxvd0VtcHR5VmFsdWUiOnRydWUsImVudW0iOlsic2hhcmVkIiwiZWdhIiwiaW5mcmEiLCJoaXBwbyIsImNicyIsInRscCIsInRpcyIsInRpIl19LCJhcmVhIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJudWxsYWJsZSI6dHJ1ZSwidHlwZSI6InN0cmluZyIsImVudW0iOlsibHVmdCIsImJyb3dzZXIiLCJidXNpbmVzcy1pbnRlbGxpZ2VuY2UiLCJidXJnZXIiLCJkYXRhLWdvdmVybmFuY2UiLCJzZWN1cml0eSIsImNzaXMiLCJjdG8iLCJpZGVudGl0eSIsImVkZ2UtZGMiLCJqdW1wc2hvdCIsImNjbGVhbmVyIiwiY3VzdG9tZXItZGF0YS1wbGF0Zm9ybSIsImV4cGVyaW1lbnRhdGlvbi1wbGF0Zm9ybSIsInNtYiIsIm90aGVyIl19LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJ1aTplbXB0eVZhbHVlIGNhdXNlcyB0aGlzIGZpZWxkIHRvIGFsd2F5cyBiZSB2YWxpZCBkZXNwaXRlIGJlaW5nIHJlcXVpcmVkIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0ZXh0ICoqYm9sZCoqIG9yICppdGFsaWMqLiBUYWtlIGEgbG9vayBhdCBvdGhlciBvcHRpb25zIFtoZXJlXShodHRwczovL21hcmtkb3duLXRvLWpzeC5xdWFudGl6b3IuZGV2LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

For default theme, you can see an empty available item
image

Not not for the MaterialUI:
image
[RJSF DEMO - bug](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImN0b1RlYW0iOnsidWk6ZW1wdHlWYWx1ZSI6IiIsIm51bGxhYmxlIjp0cnVlLCJhbGxvd0VtcHR5VmFsdWUiOnRydWUsImVudW0iOlsic2hhcmVkIiwiZWdhIiwiaW5mcmEiLCJoaXBwbyIsImNicyIsInRscCIsInRpcyIsInRpIl19LCJhcmVhIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJudWxsYWJsZSI6dHJ1ZSwidHlwZSI6InN0cmluZyIsImVudW0iOlsibHVmdCIsImJyb3dzZXIiLCJidXNpbmVzcy1pbnRlbGxpZ2VuY2UiLCJidXJnZXIiLCJkYXRhLWdvdmVybmFuY2UiLCJzZWN1cml0eSIsImNzaXMiLCJjdG8iLCJpZGVudGl0eSIsImVkZ2UtZGMiLCJqdW1wc2hvdCIsImNjbGVhbmVyIiwiY3VzdG9tZXItZGF0YS1wbGF0Zm9ybSIsImV4cGVyaW1lbnRhdGlvbi1wbGF0Zm9ybSIsInNtYiIsIm90aGVyIl19LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJ1aTplbXB0eVZhbHVlIGNhdXNlcyB0aGlzIGZpZWxkIHRvIGFsd2F5cyBiZSB2YWxpZCBkZXNwaXRlIGJlaW5nIHJlcXVpcmVkIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0ZXh0ICoqYm9sZCoqIG9yICppdGFsaWMqLiBUYWtlIGEgbG9vayBhdCBvdGhlciBvcHRpb25zIFtoZXJlXShodHRwczovL21hcmtkb3duLXRvLWpzeC5xdWFudGl6b3IuZGV2LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoibWF0ZXJpYWwtdWktNSIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

### Expected Behavior

Empty item should available also for MaterialUI

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
Fix #4197 for antd, chakra-ui, fluentui-rc, material-ui, mui, semantic-ui

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/fluentui-rc/src/SelectWidget/SelectWidget.tsx [hunk 1]
```diff
@@ -81,6 +83,7 @@ function SelectWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F extend
         selectedOptions={selectedIndexesAsArray}
         aria-describedby={ariaDescribedByIds<T>(id)}
       >
+        {!multiple && schema.default === undefined && <Option value=''>{placeholder || ''}</Option>}
```
Comment (heath-freenome) [inline packages/fluentui-rc/src/SelectWidget/SelectWidget.tsx:86]: What happens if you remove the `| ''` and `placeholder` is undefined? I think it might be ok that way, or does `undefined` get output?

File: packages/antd/src/widgets/SelectWidget/index.tsx [hunk 2]
```diff
@@ -65,6 +68,23 @@ export default function SelectWidget<
   const extraProps = {
     name: id,
   };
+
+  const selectOptions: DefaultOptionType[] | undefined = useMemo(() => {
+    if (Array.isArray(enumOptions)) {
+      if (!multiple && schema.default === undefined) {
+        enumOptions.unshift({ value: '', label: placeholder || '' });
+      }
```
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/antd/src/widgets/SelectWidget/index.tsx:76]: Maybe it would be better to do something like this so you don't push into an object you don't own?:
```
const options = [...enumOptions];
if (!multiple && schema.default === undefined) {
  options.unshift({ value: '', label: placeholder || '' });
}
return options.map(({ value: optionValue, label: optionLabel }, index) => ({
...
```

File: packages/chakra-ui/src/SelectWidget/SelectWidget.tsx [hunk 3]
```diff
@@ -61,17 +62,23 @@ export default function SelectWidget<T = any, S extends StrictRJSFSchema = RJSFS
     onFocus(id, enumOptionsValueForIndex<S>(value, enumOptions, emptyValue));
 
   const _valueLabelMap: any = {};
-  const displayEnumOptions: OptionsOrGroups<any, any> = Array.isArray(enumOptions)
-    ? enumOptions.map((option: EnumOptionsType<S>, index: number) => {
+  const displayEnumOptions: OptionsOrGroups<any, any> = useMemo(() => {
+    if (Array.isArray(enumOptions)) {
+      if (!multiple && schema.default === undefined) {
+        enumOptions.unshift({ value: '', label: placeholder || '' });
+      }
```
Comment (heath-freenome) [inline packages/chakra-ui/src/SelectWidget/SelectWidget.tsx:69]: Same comment as above where you shallow copy the `enumOptions` before pushing.

File: packages/antd/src/widgets/SelectWidget/index.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (heath-freenome) [reply packages/antd/src/widgets/SelectWidget/index.tsx:76]: Or you can do what `semantic-ui` does or change their implementation to match this one?

File: packages/fluentui-rc/src/SelectWidget/SelectWidget.tsx (hunk 1 above)
Comment (nickgros) [reply packages/fluentui-rc/src/SelectWidget/SelectWidget.tsx:86]: I actually get a TypeScript error. I think the library requires that either the `text` or `children` prop is non-null

```
src/SelectWidget/SelectWidget.tsx:86:56 - error TS2322: Type '{ children: string | undefined; value: string; }' is not assignable to type 'IntrinsicAttributes & (OptionProps & RefAttributes<HTMLDivElement>)'.
  Property 'text' is missing in type '{ children: string | undefined; value: string; }' but required in type '{ text: string; children?: ReactNode; }'.

86         {!multiple && schema.default === undefined && <Option value=''>{placeholder}</Option>}
                                                          ~~~~~~

  ../../node_modules/@fluentui/react-combobox/dist/index.d.ts:301:5
    301     text: string;
            ~~~~
    'text' is declared here.
```

Comment (nickgros) [reply packages/fluentui-rc/src/SelectWidget/SelectWidget.tsx:86]: I can remove similar code from the MUI SelectWidget

File: packages/antd/test/__snapshots__/Form.test.tsx.snap [hunk 4]
```diff
@@ -3354,9 +3354,9 @@ exports[`single fields select field single choice formData 1`] = `
                   </span>
                   <span
                     className="ant-select-selection-item"
-                    title="bar"
+                    title="foo"
                   >
-                    bar
+                    foo
```
Comment (nickgros) [inline packages/antd/test/__snapshots__/Form.test.tsx.snap:3359]: This is a regression

**Comment by heath-freenome** [comment]
> @heath-freenome WDYT about moving this change to the `optionsList` util function so all themes are provided a placeholder entry when appropriate? This has a huge downstream effect on all of our tests (and maybe users selecting enums programmatically?) where the enum option index values would now be offset if a placeholder option is present. For example this would be the rendered HTML for a simple enum with `['foo', 'bar']`
> 
> old
> 
> ```
> <select>
> 	<option value="">placeholder</option>
> 	<option value="0">foo</option>
> 	<option value="1">bar</option>
> </select>
> ```
> 
> new
> 
> ```
> <select>
> 	<option value="0">placeholder</option>
> 	<option value="1">foo</option>
> 	<option value="2">bar</option>
> </select>
> ```

Hey Nick, That could be considered a breaking change. While it kind of make sense, it requires that we have access to placeholder in the fields (I'm not sure we do) in a way that would work properly. Maybe we can use the `labelValue()` function?

**Comment by Vity01** [comment]
Any progress on this?

File: packages/antd/src/widgets/SelectWidget/index.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (nickgros) [reply packages/antd/src/widgets/SelectWidget/index.tsx]: Doing this (& wrapping in a `useMemo`) seems to take care of it. I needed to flip-flop the order of `map` and `unshift` compared to your example because we do not want the placeholder option value to be the enum option index.

**Comment by nickgros** [comment]
Another reason to not update the `optionsList` utility is because it also affects radio groups. This best to be left to the `SelectWidget` implementations. Future PRs may improve the theme-specific behavior by e.g. rendering 'clear' buttons instead of a blank placeholder option.

File: CHANGELOG.md [hunk 5]
```diff
@@ -18,10 +18,34 @@ should change the heading of the (upcoming) version to include a major version b
 
 # 5.19.2
```
Comment (heath-freenome) [inline CHANGELOG.md:19]: I've released 5.19.2 so you'll have to bump this

File: CHANGELOG.md [hunk 6]
```diff
@@ -92,6 +116,7 @@ should change the heading of the (upcoming) version to include a major version b
 - Fix case where NumberField would not properly reset the field when using programmatic form reset (#4202)[https://github.com/rjsf-team/react-jsonschema-form/issues/4202]
 - Updated widgets to handle undefined `target` in `onFocus` and `onBlur` handlers
 - Fix field disable or readonly property can't cover globalOptions corresponding property (#4212)[https://github.com/rjsf-team/react-jsonschema-form/pull/4212]
+- Added support for `default` values in `additionalProperties` in [#4199](https://github.com/rjsf-team/react-jsonschema-form/issues/4199), fixing [#3195](https://github.com/rjsf-team/react-jsonschema-form/issues/3915)
```
Comment (heath-freenome) [inline CHANGELOG.md:119]: Where did this come from?

**Review by heath-freenome — APPROVED** [review]
Just some tweaks to the CHANGELOG.md

File: CHANGELOG.md (hunk 6 above)
Comment (nickgros) [reply CHANGELOG.md:119]: I think when I picked this up, we decided I would add this missing changelog message, assuming this would be a faster change to implement. I didn't realize it was missing until I revisited this.

File: CHANGELOG.md (hunk 5 above)
Comment (nickgros) [inline CHANGELOG.md:19]:
```suggestion
# 5.19.3
```

**Comment by Vity01** [comment]
Excellent, thank you @nickgros

**Comment by mahendra790** [comment]
@nickgros Is there any way to opt out of this feature? because to remove this I need to add `default: ""` which makes it a valid field and required validation is not applied.

**Comment by nickgros** [comment]
@mahendra790 Sorry, I'm not understanding what you expect to happen, especially because this behavior was how the `core` theme worked originally.

Could you set the `default` value in the schema to be equal to the the first option in your list of options?

**Comment by XavierLeTohic** [comment]
The updated RJSF Antd theme now displays placeholders as selectable options (differing from Antd's default behavior), and without an opt-out mechanism in uiSchema, it requires a custom Select widget implementation for cases where we need the original behavior. 😕
