### PR TITLE
Fix potential XSS in the preview button of FileWidget

### LINKED ISSUE #4057: Validate dataURL to prevent XSS attacks
Hi, I've found a Cross-Site Scripting (XSS) vulnerability in `@rjsf/core`

**Vulnerability Details:**
- **Severity**: High/Critical
- **Description**: There's a risk of malicious script execution when the value of the FileWidget is controlled by an adversary.

**Steps to Reproduce:**
```
import React from "react";
import ReactDOM from "react-dom/client";
import { getDefaultRegistry } from "@rjsf/core";

const schema = {
  title: "Files",
  type: "object",
  properties: {
    file: {
      type: "string",
      format: "data-url",
      title: "Single file",
    },
  },
};

function App() {
  const FileWidget = getDefaultRegistry().widgets.FileWidget;

  return (
    <FileWidget
      value={["javascript:alert(1)"]}
      registry={getDefaultRegistry()}
      options={{ id: 1, filePreview: true }}
      id="1"
      schema={schema}
      onChange={() => {}}
      onFocus={() => {}}
    />
  );
}

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);

```
In this case, when a user clicks the preview button, the malicious script `alert(1)` will be executed. Note that the specified `format: "data-url"` does not successfully sanitize the value.

**Suggested Fix or Mitigation:**
The root cause is due to: https://github.com/rjsf-team/react-jsonschema-form/blob/f31bef19c1420aec74384fc4f4152bed579f0902/packages/core/src/components/widgets/FileWidget.tsx#L79
where a malicious dataURL may be passed to the `<a />`, causing an XSS attack. 

It is best practice for a package to ensure security. Even though the dataURL has been validated elsewhere, there's still a risk of malicious dataURL being passed to `<a />` as shown in the example. Please consider patching this issue by validating the dataURL to prevent the XSS attack. Thanks!

### PR DESCRIPTION
**Pull request by yuki-js**
### Reasons for making this change

fixes #4057

The value prop in FileWidget parses the data URL inappropriately, which also permits the use of `javascript:` schema. 
When the `javascript:` schema is set, and `ui:filePreview` is `true`, and when the user clicks `Preview` button, the JavaScript code is evaluated, and then allows XSS attack.

I fixed it by: 
- parsing the data URL correctly
- throwing `Error` when the URL is invalid
- restricting image types from any image to JPEG, PNG, GIF

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/widgets/FileWidget.tsx [hunk 1]
```diff
@@ -69,10 +69,15 @@ function FileInfoPreview<T = any, S extends StrictRJSFSchema = RJSFSchema, F ext
     return null;
   }
 
-  if (type.indexOf('image') !== -1) {
+  // If type is JPEG, PNG, or GIF, then show image preview.
+  // Originally, any type of image was supported, but this was changed into a whitelist
+  // since SVGs are also images, which is generally considered a security risk.
+  if (['image/jpeg', 'image/png', 'image/gif'].includes(type)) {
```
Comment (heath-freenome) [inline packages/core/src/components/widgets/FileWidget.tsx:75]: Animated GIFs are also a security risk... Maybe we only show the first two

File: packages/utils/src/dataURItoBlob.ts [hunk 2]
```diff
@@ -4,39 +4,36 @@
...
+  // check if the dataURI is base64
+  if (splitted.length !== 2) {
+    throw new Error('File is invalid: dataURI must be base64');
+  }
+  const [media, base64] = splitted;
+  const [mime, ...mediaparams] = media.split(';');
+  const type = mime || '';
+  const name = decodeURI(
+    mediaparams.map((param) => param.split('=')).find(([key]) => key === 'name')?.[1] || 'unknown'
+  );
```
Comment (heath-freenome) [inline packages/utils/src/dataURItoBlob.ts:23]: Can you add documentation around what this is doing

File: packages/utils/src/dataURItoBlob.ts [hunk 3]
```diff
@@ -4,39 +4,36 @@
...
-      array.push(binary.charCodeAt(i));
+      array[i] = binary.charCodeAt(i);
     }
     // Create the blob object
     const blob = new window.Blob([new Uint8Array(array)], { type });
 
     return { blob, name };
   } catch (error) {
-    return { blob: { size: 0, type: (error as Error).message }, name: dataURI };
+    throw new Error('File is invalid: failed to decode base64');
```
Comment (heath-freenome) [inline packages/utils/src/dataURItoBlob.ts:37]: Why not just treat all of the errors to return a blob like these?

**Comment by heath-freenome** [comment]
@yuki-js your build in `@rjsf/utils` is failing.

File: packages/utils/src/dataURItoBlob.ts (hunk 3 above)
Comment (yuki-js) [reply packages/utils/src/dataURItoBlob.ts]: The original code treated the invalid file as zero-sized file. Of course, the invalid file is different from the zero-sized valid file. Invalid files should have been taken care of by the callee, but it is not.
This behavior also allowed `javascript:` schema.

**Comment by yuki-js** [comment]
@heath-freenome Thank you for your review. 
This failure is the same as the one we faced previously. Could you rerun it?
https://github.com/rjsf-team/react-jsonschema-form/actions/runs/7474848380/attempts/3

**Review by heath-freenome — COMMENTED** [review]
Sorry, I forgot to submit these comments over the weekend

File: packages/core/src/components/widgets/FileWidget.tsx [hunk 4]
```diff
@@ -121,17 +126,26 @@ function FilesInfo<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends F
...
+        ...acc,
+        {
+          dataURL,
+          name: name,
+          size: blob.size,
+          type: blob.type,
+        },
+      ];
+    } catch (e) {
+      // Invalid dataURI, so just ignore it.
```
[the remark this answers is not in the document]
Comment (yuki-js) [reply packages/core/src/components/widgets/FileWidget.tsx:145]: **Possibility of Exception:** When the ordinary user uploads files in ordinary way, the exception should never happen, since the data URL is always returned, and Base64 encoding/decoding always be successful. Therefore the data should not disappear in an unintuitive way.

**Error notification:** If the caller injects the malformed string into `formData`, validator rejects it with `.files.0 must match format "data-url"`, but it would be an issue on the side of the caller.


Although I could also change it by adding error flag in `FileInfoType`, I decided not to notify the explicit error for this reason.

**Review by heath-freenome — APPROVED** [review]
