### PR TITLE
Fix 4623 by properly handling chakra-ui's onChange for single select

### LINKED ISSUE #4623: The Alternatives example in the playground doesn't work for chakra-ui
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

6.0.0-beta.7

### Current Behavior

I ran into an issue where I couldn't get an array with enum to work when using the chakra-ui theme. Turns out the same issue can be found in the playground. In the Alternatives example, if you add a color under Color palette, the form will not pass validation when submitting.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixed #4623 by having the single select version return the element in the returned array
- Updated chakra-ui's `SelectWidget` to return a single value from the array

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/chakra-ui/src/SelectWidget/SelectWidget.tsx [hunk 1]
```diff
@@ -43,19 +43,12 @@ export default function SelectWidget<T = any, S extends StrictRJSFSchema = RJSFS
   const { enumOptions, enumDisabled, emptyValue } = options;
 
   const _onMultiChange = ({ value }: SelectValueChangeDetails) => {
-    return onChange(
-      enumOptionsValueForIndex<S>(
-        value.map((item) => {
-          return item;
-        }),
```
Comment (heath-freenome) [inline packages/chakra-ui/src/SelectWidget/SelectWidget.tsx:50]: This seemed unnecessary since it basically returned the same thing as `value`

**Review by nickgros — APPROVED** [review]
