### PR TITLE
fix: Prevent duplicate extraErrors when not live validating

### LINKED ISSUE #3169: ExtraErrors are merged into errorSchema again and again
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x Beta.10

### Current Behavior

The passed extraErrors are rendered multiple times when typing into an input field.

### Expected Behavior

The `extraErrors` should only be displayed once.

### Steps To Reproduce

See example: https://codesandbox.io/s/vigilant-violet-8txkdr

Given the following Form config:

```jsx
import validator from "@rjsf/validator-ajv6";
import Form from "@rjsf/core";

const schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "email": {
            "type": "string",
            "format": "email"
        },
        "password": {
            "type": "string"
        },
        "passwordConfirmation": {
            "type": "string"
        }
    },
    "required": [
        "email",
        "password",
        "passwordConfirmation"
    ],
    "additionalProperties": false
}
...
<Form
   validator={validator}
   extraErrors={{email: {__errors: ["test"]}}}
   schema={schema}
   onSubmit={handleSubmit}
>
```

When typing something into the password field, the extra errors are appended in the UI again and again.

image

### Environment

```markdown
- OS: MaxOS
- Node: 16.7
- npm: 8.15
```

### Anything else?

_No response_

### LINKED ISSUE #3282: Localization docs broken
See https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#some-examples

image

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixed #3169 by merging `extraErrors` in while preventing duplicates
- Updated `@rjsf/utils` to make the `mergeObjects()` function support a `preventDuplicates` mode when concatenating arrays
  - Updated the tests to verify this new feature
- Updated `@rjsf/core` to use the `preventDuplicates` mode when merging `extraErrors` when not live validating
- Updated `validation.md` to remove extraneous leading space to fix #3282
- Updated `utility-functions.md` to document the new mode
- Updated `index.md` to provide the proper `core.cjs.production.min.js` package name for `unpkg.com` fixing #3262
- Updated the `CHANGELOG.md` accordingly

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/mergeObjects.ts [hunk 1]
```diff
@@ -5,21 +5,31 @@ import { GenericObjectType } from "./types";
...
     const left = obj1 ? obj1[key] : {},
       right = obj2[key];
     if (obj1 && key in obj1 && isObject(right)) {
       acc[key] = mergeObjects(left, right, concatArrays);
     } else if (concatArrays && Array.isArray(left) && Array.isArray(right)) {
-      acc[key] = left.concat(right);
+      let toMerge = right;
+      if (concatArrays === "preventDuplicates") {
+        toMerge = right.reduce((result, value) => {
+          if (!left.includes(value)) {
```
Comment (nickgros) [inline packages/utils/src/mergeObjects.ts:26]: This should work just fine for `ErrorSchema`s because it's an Object of objects or string arrays, but I'm concerned someone may try to use this and expect this to deduplicate with deep equality. What do you think? Either way, please update the @param doc for "preventDuplicates" to indicate the behavior.

Comment (heath-freenome) [reply packages/utils/src/mergeObjects.ts:27]: done
