### PR TITLE
fix: deal with null objects in errors in Form.filterErrorsBasedOnSchema()

### LINKED ISSUE #4306: TypeError: Cannot read properties of null (reading '__errors') in Form.filterUndefinedErrors
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.20.0

### Current Behavior

We noticed the following error:
```
TypeError: Cannot read properties of null (reading '__errors')
    at  (../node_modules/@rjsf/core/src/components/Form.tsx:611:79)
    at iteratee (../node_modules/lodash/_createBaseFor.js:17:10)
    at baseFor (../node_modules/lodash/_baseForOwn.js:13:19)
    at eachFunc (../node_modules/lodash/_createBaseEach.js:17:13)
    at func (../node_modules/lodash/forEach.js:38:9)
    at errors (../node_modules/@rjsf/core/src/components/Form.tsx:608:15)
    at filterUndefinedErrors (../node_modules/@rjsf/core/src/components/Form.tsx:612:10)
    at iteratee (../node_modules/lodash/_createBaseFor.js:17:10)
    at baseFor (../node_modules/lodash/_baseForOwn.js:13:19)
    at eachFunc (../node_modules/lodash/_createBaseEach.js:17:13)
```

### Expected Behavior

No error

### Steps To Reproduce

So far I've been unable to reproduce this issue.

But based on the stacktrace I could pinpoint it to this location:
https://github.com/rjsf-team/react-jsonschema-form/commit/4d3094c54cb70ff96a5d6a8b49114d7a9814d972#diff-704dadefdc8b52ac02d6712540e5734214e9699c66d1d673ded1c57e96df9303R611

Looks like this was newly introduced with version 5.20.0

### Environment

```markdown
- OS: Mac OS X 10.15.7
- Node: v20.11.1
- npm: 10.8.2
```

### Anything else?

Proposed solution:
- it might mitigate the issue to replace the check for `undefined` in [line 609 of Form.tsx](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/Form.tsx#L609) with a lodash `isNil` call instead

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #4306 by using `lodash.isNil()` instead of comparing to `undefined`
- Updated `Form.filterErrorsBasedOnSchema()` to use lodash `isNil()` to check if the key is either null or undefined
- Updated the `CHANGELOG.md` accordingly

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by nickgros — APPROVED** [review]

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -606,7 +607,7 @@ export default class Form<
     // Removing undefined and empty errors.
     const filterUndefinedErrors = (errors: any): ErrorSchema<T> => {
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:608]:
```suggestion
    // Removing undefined, null and empty errors.
    const filterNilOrEmptyErrors = (errors: any): ErrorSchema<T> => {
```

**Review by nickgros — APPROVED** [review]
