### PR TITLE
Fix #4962

### LINKED ISSUE #4962: Programmatic validation ignores `extraErrors`
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

shadcn

### Version

6.x

### Current Behavior

The `ErrorList` is not displayed; calling `validateForm` cleares the form state.

### Expected Behavior

The `ErrorList` is displayed and includes the `extraErrors` values.

### Steps To Reproduce

1. Provide valid `formData`, set `showErrorList`, and provide nonempty `extraErrors`.
2. Call `validateForm`.

### Environment

N/A

### Anything else?

**Suspected cause:**
An `extraErrorsBlockSubmit` check at https://github.com/heath-freenome/react-jsonschema-form/blob/0782d68834af63bab0255f5bc701b06846f6f6c3/packages/core/src/components/Form.tsx#L1215

**Request to maintainers:**
To reduce the risk of future regressions, refactor programmatic validation method so it reuses the same validation logic and/or errors-merging logic used by other methods.

### PR DESCRIPTION
**Pull request by nickgros**
Fixed `validateForm()` clearing `extraErrors` from state when schema validation passes

### Reasons for making this change

Fixes #4962

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -1256,17 +1256,14 @@ export default class Form<
...
-    const schemaValidationErrors = errors;
-    const schemaValidationErrorSchema = errorSchema;
-    const hasError = errors.length > 0 || (extraErrors && extraErrorsBlockSubmit);
+    const schemaValidationErrors = schemaValidation.errors;
+    const schemaValidationErrorSchema = schemaValidation.errorSchema;
+    // Always merge extraErrors so they remain visible in state regardless of extraErrorsBlockSubmit.
+    const { errors, errorSchema } = this.mergeErrors(schemaValidation, extraErrors);
+    // hasError gates submission: schema errors always block; extraErrors only block when
+    // extraErrorsBlockSubmit is set (non-breaking default: extraErrors are informational only).
+    const hasError = schemaValidationErrors.length > 0 || (!!extraErrors && !!extraErrorsBlockSubmit);
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx]:
```suggestion
    const hasError = schemaValidation.errors.length > 0 || (extraErrors && extraErrorsBlockSubmit);
```

File: packages/core/src/components/Form.tsx [hunk 2]
```diff
@@ -1256,17 +1256,14 @@ export default class Form<
...
     const schemaValidation = this.validate(formData);
-    let errors = schemaValidation.errors;
-    let errorSchema = schemaValidation.errorSchema;
-    const schemaValidationErrors = errors;
-    const schemaValidationErrorSchema = errorSchema;
-    const hasError = errors.length > 0 || (extraErrors && extraErrorsBlockSubmit);
+    const schemaValidationErrors = schemaValidation.errors;
+    const schemaValidationErrorSchema = schemaValidation.errorSchema;
+    // Always merge extraErrors so they remain visible in state regardless of extraErrorsBlockSubmit.
+    const { errors, errorSchema } = this.mergeErrors(schemaValidation, extraErrors);
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx]:
```suggestion
    const { errors, errorSchema } = extraErrors ? this.mergeErrors(schemaValidation, extraErrors) : schemaValidation;
```

File: packages/core/src/components/Form.tsx [hunk 3]
```diff
@@ -1256,17 +1256,14 @@ export default class Form<
...
     const { errors: prevErrors } = this.state;
     const schemaValidation = this.validate(formData);
-    let errors = schemaValidation.errors;
-    let errorSchema = schemaValidation.errorSchema;
-    const schemaValidationErrors = errors;
-    const schemaValidationErrorSchema = errorSchema;
-    const hasError = errors.length > 0 || (extraErrors && extraErrorsBlockSubmit);
+    const schemaValidationErrors = schemaValidation.errors;
+    const schemaValidationErrorSchema = schemaValidation.errorSchema;
+    // Always merge extraErrors so they remain visible in state regardless of extraErrorsBlockSubmit.
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx]:
```suggestion
    // Merge extraErrors if they exist so they remain visible in state regardless of extraErrorsBlockSubmit.
```

File: packages/core/src/components/Form.tsx [hunk 4]
```diff
@@ -1289,6 +1286,14 @@ export default class Form<
           }
         },
       );
+    } else if (errors.length > 0) {
+      // Non-blocking extraErrors are present — update display state without triggering onError.
+      this.setState({
+        errors,
+        errorSchema,
+        schemaValidationErrors,
+        schemaValidationErrorSchema,
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx]: Either we get them from `schemaValidation` or we just omit them since only extra errors were added

File: packages/core/test/Form.test.tsx [hunk 5]
```diff
@@ -4877,6 +4877,154 @@ describe('validateForm()', () => {
...
+    act(() => {
+      result = formRef.current!.validateForm();
+    });
+
+    // Should return true (non-blocking)
+    expect(result).toBe(true);
+    // extraErrors should remain visible in state
+    expect(formRef.current!.state.errors).toHaveLength(1);
+    expect(formRef.current!.state.errors[0].message).toBe('async error for foo');
+    expect(formRef.current!.state.errorSchema).toMatchObject({ foo: { __errors: ['async error for foo'] } });
```
Comment (heath-freenome) [inline packages/core/test/Form.test.tsx]:
```suggestion
    expect(formRef.current!.state.errorSchema).toMatchObject(extraErrors);
```
