### PR TITLE
Fix: #3924 by preventing an undefined schema for fixed array items

### LINKED ISSUE #1794: Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended
Hi!

I have an old bug [see here](https://github.com/rjsf-team/react-jsonschema-form/issues/1436) but i'm with the last version.

I know that the warning is not raised in production but normally this bug was fixed in the 2.0 version, isn't it ?

I'm only reusing one Form component and only change data and uischema for each schema I have in my multistep form.

### Description

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Form

### Version
react: 16.13.1
@rjsf/core: 2.0.1

Cheers,
Yu.

### LINKED ISSUE #3924: Cannot use 'in' operator to search for '$ref' in undefined in fixed arrays
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.13.2

### Current Behavior

If I use fixed Array and provide extended data in formData props I get exception: "Cannot use 'in' operator to search for '$ref' in undefined"

For example:

**JSONSchema:**
```json
{
  "type": "object",
  "properties": {
    "scoreEntries": {
      "type": "array",
      "items": [
        {
          "properties": {
            "scorePercent": {
              "type": "number"
            }
          }
        }
      ]
    }
  }
}
```
**formData:**
```json
{
  "scoreEntries": [
    {
      "scorePercent": 10032
    },
    {
      "scorePercent": 10032
    }
  ]
}
```

And if I remove last item from formData array, then this work good

### Expected Behavior

When passing additional data in formData, ignore it and proxy it to the submit

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 20.5.0
- npm: 9.8.1
```

### Anything else?

[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzY29yZUVudHJpZXMiOlt7InNjb3JlUGVyY2VudCI6MTAwMzJ9LHsic2NvcmVQZXJjZW50IjoxMDAzMn1dfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InNjb3JlRW50cmllcyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6W3sicHJvcGVydGllcyI6eyJzY29yZVBlcmNlbnQiOnsidHlwZSI6Im51bWJlciJ9fX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOnRydWV9LCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlfX0=)

### LINKED ISSUE #3927: Schema changes are not reflecting in the form
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.13.2

### Current Behavior

The JSON or UI schema changes are not reflecting in playground form. Any change made for example in `title` or in the property name doesn't show up.

### Expected Behavior

Changes in schemas should immediately reflect in the form.

### Steps To Reproduce

1. Go to the [playground](https://rjsf-team.github.io/react-jsonschema-form/)
2. Try making any changes in the JSON or UI schema. For example change the `title` or the widget of a property
3. There is no change in the form

### Environment

```markdown
- OS: macOS 13.5.1
- Node: 18.15.0
- npm: 9.5.0
```

### Anything else?

The schema changes reflect when there is any change in the form data.

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #3924 by defaulting to an empty object for the `itemSchema` when undefined
Fixes #3927 by fixing `getSnapshotBeforeUpdate()` added for the fix #1794
- In `@rjsf/core` updated `ArrayField`'s `renderFixedArray()` to default the `itemSchema` to an empty object if it is falsy
  - Updated the tests for `ArrayField` to verify the fix
  - Updated the `getSnapshotBeforeUpdate()` to diff the old and new props and to set the `shouldUpdate` prop if the old and new state differs
- Updated `CHANGELOG.md` accordingly
  - Also added entry for the fix for #3919

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -281,35 +281,45 @@ export default class Form<
...
+   * @returns Either an object containing the next state and a flag indicating that an update should occur, or an object
+   *        with a flag indicating that an update is not necessary.
    */
   getSnapshotBeforeUpdate(
-    prevProps: FormProps<T, S, F>
+    prevProps: FormProps<T, S, F>,
+    prevState: FormState<T, S, F>
   ): { nextState: FormState<T, S, F>; shouldUpdate: true } | { shouldUpdate: false } {
-    if (!deepEquals(this.props.formData, prevProps.formData)) {
+    if (!deepEquals(this.props, prevProps)) {
```
Comment (nickgros) [inline packages/core/src/components/Form.tsx:305]: Thanks for finding and fixing this

**Review by nickgros — APPROVED** [review]
