### PR TITLE
Packages/utils/schema

### LINKED ISSUE #2693: Decouple schema validation from core
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

`ajv@6` has served this project well. The `6.*` line (and indeed the `7.*` line #2542) have reached end-of-life, and if new serious issues were discovered, may not be fixed. With the success of the decoupled, but co-maintained, themes it is perhaps time to consider co-developing multiple schema validators that meet different needs.

While client-side validation is an important part of the rjsf experience, and should be encouraged with a sensible default, picking a validator carries a number of trade-offs:

- overall size
- time to first load
- time to subsequent load
- time to validate
- arbitrary code execution
- JSON Schema drafts supported (the current `ajv@8` drops `draft4`)

For example, 
- `ajv@>7` makes pre-compiled [standalone validators](https://ajv.js.org/standalone.html) possible, which can be tree-shaken to avoid bringing the compiler
- rjsf can be used to _draw_ a form, with a given theme, and another technique entirely is used to validate it client-side

### Proposal

- [ ] move most of the logic in `validate.js` to a `AJV6Validator` class
  - [ ] define a new `ValidationError` to which an `AjvError` can be converted 
  - [ ] move these to a new package, `@rjsf/validator-ajv6`
    - [ ] refactor the boilerplate of this class and errors to a `NoOpValidator`
      - [ ] move the base to a new `@rjsf/validator-base` package, as a dependency of `@rjsf/core`
- [ ] add a new package `@rjsf/validator-ajv8` to track features
- [ ] add a `validateFormData` to the form props, somewhat like #1286, and, depending on when it lands:
  - ... in `@rjsf/core 3.*` 
    - use `AJV6Validator.validateFormData` default
  - ... in `@rjsf/core 4.*`
    - if available from a `peerDependency` on `@rjsf/validator-ajv8`
      - use a `AJV8Validator.validateFormData`
    - otherwise, 
      - fall back to `NoOpValidator`
      - `console.warn`

Once the existing behavior and test suite have been

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Partially fixes #2693 by finishing the migration of the utils functions to their own package.

This second pass migrates all of the utils functions that do require schema resolution into the new `@rjsf/utils` package.
- As part of this migration, some new types were added `src/types.ts`
- All of the migrated `utils/schema` functions in this PR have been converted to typescript with 100% unit testing
- Added full documentation for the converted functions

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/constants.ts [hunk 1]
```diff
@@ -1,9 +1,12 @@
...
 export const ALL_OF_NAME = 'allOf';
+export const ANY_OF_NAME = 'anyOf';
 export const CONST_NAME = 'const';
+export const DEFAULT_NAME = 'default';
 export const DEPENDENCIES_NAME = 'dependencies';
 export const ITEMS_NAME = 'items';
+export const ONE_OF_NAME = 'oneOf';
 export const PROPERTIES_NAME = 'properties';
 export const SUBMIT_BTN_OPTIONS_NAME = 'submitButtonOptions';
 export const REF_NAME = '$ref';
```
Comment (heath-freenome) [inline packages/utils/src/constants.ts:12]: Whoops, I meant to change the suffix on these to `KEY`... will do that in a commit soon

File: packages/utils/test/testUtils/getTestValidator.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+import { ValidationData, ValidatorType } from '../../src';
+
+export interface TestValidatorParams {
+  isValid?: boolean[];
+  data?: ValidationData[];
+}
+
+export interface TestValidatorType extends ValidatorType {
+  // eslint-disable-next-line no-unused-vars
+  setReturnValues(params?: TestValidatorParams): void;
```
Comment (nickgros) [inline packages/utils/test/testUtils/getTestValidator.ts:12]: Feeling conflicted about this because mocking the validator seems like the correct thing to do, but I think using an actual validator gives us much more confidence in our test suite.

**Review by nickgros — COMMENTED** [review]
I like the SchemaUtils abstraction, and really appreciate the new comments on utils functions. This is a lot of code to look at. What I've looked at looks good, but it's not 100% clear to me what's been moved vs what's changed.

**Comment by heath-freenome** [comment]
> I like the SchemaUtils abstraction, and really appreciate the new comments on utils functions. This is a lot of code to look at. What I've looked at looks good, but it's not 100% clear to me what's been moved vs what's changed.

So far its pretty much 90% move w/ conversion to Typescript. 8% of the remaining 10% of the changes that were made are related to things needing to be different due to Typescript. And those changes have been proven out by the 100% test coverage. The remaining 2% of the changes are simply JS optimizations that have no impact on the code.

File: packages/utils/test/testUtils/getTestValidator.ts (hunk 2 above)
Comment (heath-freenome) [reply packages/utils/test/testUtils/getTestValidator.ts:12]: I know the feeling, but the point of abstracting the utils and validator was to break a circular dependency between the two features. One thing we can consider doing in another pass after I complete the ajv v6 package is to figure out a way to run all the schema utils tests in the ajv 6 validator world using the actual validator. rather than the mock... I would effectively make the `setReturnValues()` function in ajv v6 to be a no-op.

**Comment by heath-freenome** [comment]
@epicfaace @nickgros anymore feedback on this?

File: packages/utils/src/types.ts [hunk 3]
```diff
@@ -276,19 +283,32 @@ export type UiSchema<T = any, F = any> = GenericObjectType & {
...
+  getDefaultFormState(schema: RJSFSchema, formData?: T, includeUndefinedValues?: boolean): T | T[] | undefined;
+  getDisplayLabel<F = any>(schema: RJSFSchema, uiSchema: UiSchema<T, F>): boolean;
+  getMatchingOption(formData: T, options: RJSFSchema[]): number;
+  isFilesArray<F = any>(schema: RJSFSchema, uiSchema: UiSchema<T, F>): boolean;
+  isMultiSelect(schema: RJSFSchema): boolean;
+  isSelect(schema: RJSFSchema): boolean;
+  retrieveSchema(schema: RJSFSchema, formData: T): RJSFSchema;
+  stubExistingAdditionalProperties(schema: RJSFSchema, formData: T): RJSFSchema;
+  toIdSchema(schema: RJSFSchema, id?: string, formData?: T, idPrefix?: string, idSeparator?: string): IdSchema;
+  toPathSchema(schema: RJSFSchema, name?: string, formData?: T): PathSchema;
```
Comment (heath-freenome) [inline packages/utils/src/types.ts:313]: Add generic to `IdSchema` and `PathSchema` return values
