### PR TITLE
antd - smaller bundle, fix classNames, date time issues

### LINKED ISSUE #1880: Antd Theme date-time has problems.
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The antd theme has some minor problems.
When I use the date component. Selecting the value will cause an error. The form crashed directly

### Steps to Reproduce

1. Open the playground. https://rjsf-team.github.io/react-jsonschema-form/
2. select antd theme and  Data & time
3. select a time.

#### Expected behavior

I hope the value like 2020-06-13T04:39:00.000Z

#### Actual behavior

The form crashed directly

### Tips

Antd used the moment.js . So this value is moment object.You need to use it to convert values
image

### LINKED ISSUE #1889: antd doesn't support uiSchema's classNames
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

It's very straightforward. This uiSchema:
```
const uiSchema = {
  name: {
    classNames: "custom-class-name"
  }
}
```

won't affect my antd form where there's a `name` string property.

This is the documentation about this feature: https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#classnames

I've looked at other issues, and couldn't find anyone complaining about this. I've seen the same problem being reported for material-ui, but I think that they don't share the same source (regarding this problem)...

@delyanr, I've seen you have some work on this project, and, first, congrats! If you just point out to me what would be necessary to fix the problem, I'm willing to make a PR. I've tried understanding it, but there's so much going on that I don't know what can be changed.

### PR DESCRIPTION
**Pull request by delyanr**
### Reasons for making this change

Addresses #1875 - The way less/styles work in ant-design means it will never be a small bundle. I managed to shave off 400Kb by using manual imports instead of relying on babel-plugin-import. Excluding the source-maps, the bundle stands at ~1Mb.

Fixes #1889 - There was a minor typo in the `WrapIfAdditional` component which prevented `classNames`. Tests were also affected.

Fixes #1880 - I don't have much time to check whether we can allow the users of `@rjsf/antd` to select which date library they use (e.g. moment or dayjs). Since dayjs is super small, I'm forcing its use here. Also deprecated the use of the antd-dayjs-webpack-plugin.

Finally, it would be great if there are a couple of volunteers who can add some additional tests. :)

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by delyanr** [comment]
@epicfaace This might have a conflict with #1867 as I fixed some issues in the playground CI already.

File: packages/antd/src/components/DatePicker/index.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
```
Comment (epicfaace) [inline packages/antd/src/components/DatePicker/index.js:1]: This does seem to be a better solution than using the day-js-webpack-plugin.

Was day-js-webpack-plugin causing #1880? If so, why?

File: packages/playground/webpack.config.dev.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ module.exports = {
       },
       {
         test: /\.less$/,
-        include: /node_modules\/antd/,
+        include: /node_modules[\\/]antd/,
```
[the remark this answers is not in the document]
Comment (delyanr) [reply packages/playground/webpack.config.dev.js:65]: This ensures webpack matches both `/` and `\` as path separators, and reduces issues between Unix and Windows.

File: packages/antd/src/components/DatePicker/index.js (hunk 1 above)
Comment (delyanr) [reply packages/antd/src/components/DatePicker/index.js:1]: The `day-js-webpack-plugin` was not working as intended for some reason, meaning that the `DatePicker` component was still trying to access the default `moment` library instead of `dayjs` for date/time operations.

**Comment by MacroBet** [comment]
Could you please version this?
