### PR TITLE
Fixes for #3228 (playground dev crash), #3213 (Ajv8 additionalProperties validation)

### LINKED ISSUE #3228: @rjsf/playground: Vite dev server broken
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta12

### Current Behavior

`global is not defined`

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
Fixes #3228, #3213

Playground
- Playground `localValidator` should use @rjsf/validator-ajv8
- Upgrade Vite and @vitejs/plugin-react to latest

@rjsf/validator-ajv8
- Alias `ajv` to `ajv8` because in the playground, Vite erroneously imports Ajv 6
- Report any schema error thrown by Ajv
- Disable Ajv's strict mode by default
- Add RJSF-specific additional properties keywords to Ajv to prevent errors from being reported in strict mode.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/validator-ajv8/src/createAjvInstance.ts [hunk 1]
```diff
@@ -35,7 +35,8 @@ export default function createAjvInstance(
   AjvClass: typeof Ajv = Ajv
 ) {
   const ajv = new AjvClass({ ...AJV_CONFIG, ...ajvOptionsOverrides });
-  if (typeof ajvFormatOptions !== "boolean") {
+  if (ajvFormatOptions && typeof ajvFormatOptions !== "boolean") {
+    console.log(ajvFormatOptions);
```
Comment (nickgros) [inline packages/validator-ajv8/src/createAjvInstance.ts:39]:
```suggestion
```

File: packages/validator-ajv8/src/createAjvInstance.ts [hunk 2]
```diff
@@ -35,7 +35,7 @@ export default function createAjvInstance(
   AjvClass: typeof Ajv = Ajv
 ) {
   const ajv = new AjvClass({ ...AJV_CONFIG, ...ajvOptionsOverrides });
-  if (typeof ajvFormatOptions !== "boolean") {
+  if (ajvFormatOptions && typeof ajvFormatOptions !== "boolean") {
     addFormats(ajv, ajvFormatOptions);
   }
```
Comment (nickgros) [inline packages/validator-ajv8/src/createAjvInstance.ts:40]: `null` and `undefined` passed this check

File: packages/validator-ajv8/package.json [hunk 3]
```diff
@@ -27,13 +27,13 @@
     ]
   },
   "dependencies": {
-    "ajv": "^8.11.0",
+    "ajv8": "npm:ajv@^8.11.0",
```
Comment (nickgros) [inline packages/validator-ajv8/package.json:30]: Part of the reason the dev server was crashing was because Vite was resolving `'ajv'` to Ajv 6 in `'@rjsf/validator-ajv8'`.

Will this affect anything for users?

Comment (heath-freenome) [reply packages/validator-ajv8/package.json:30]: Maybe switch things in the `ajv6` validator instead?

File: packages/validator-ajv8/package.json [hunk 4]
```diff
@@ -27,13 +27,13 @@
...
     "ajv-formats": "^2.1.1",
     "lodash": "^4.17.15",
     "lodash-es": "^4.17.15"
   },
   "peerDependencies": {
-    "@rjsf/utils": "^5.0.0-beta.1"
+    "@rjsf/utils": "^5.0.0-beta.12"
```
Comment (heath-freenome) [inline packages/validator-ajv8/package.json:36]: I think you can revert this one since the `^` will get it to `.12`

**Review by heath-freenome — APPROVED** [review]
Just consider making the ajv6 validator the one using the alias since it is more likely to be deleted in the future

File: packages/validator-ajv8/package.json (hunk 3 above)
Comment (nickgros) [reply packages/validator-ajv8/package.json:30]: The fix doesn't work if I just change it for ajv6, not sure why.
