### PR TITLE
Fix issues with validating schemas with "$id"s in @rjsf/validator-ajv8

### LINKED ISSUE #2821: If/then/else not working if schema contains an id or $id attribute
Prerequisites
 Link to the playground demonstrating the issue: [Playgroung Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWVsZC0xIjp7fX0sInNjaGVtYSI6eyIkaWQiOiJtb2lyaGdvYWllcmdvaWpnOTg0OGY1NHFkZjU0ZWFyZyIsInRpdGxlIjoidGVzdCBkYXRlIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZmllbGQtMSI6eyJ0aXRsZSI6IkNvbnRyYWN0IFR5cGUgYW5kIERhdGVzIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZHVyYXRpb25UeXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkNESSIsIkNERCJdLCJtYXhMZW5ndGgiOjMwfSwiYmVnaW4iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiYmVnaW4iLCJmb3JtYXQiOiJkYXRlIiwiZGVzY3JpcHRpb24iOiJGb3JtYXQgREQvTU0vWVlZWSIsIm1heExlbmd0aCI6MTB9fSwiaWYiOnsicHJvcGVydGllcyI6eyJkdXJhdGlvblR5cGUiOnsiZW51bSI6WyJDREQiXX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImVuZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJlbmQiLCJmb3JtYXQiOiJkYXRlIiwiZGVzY3JpcHRpb24iOiJGb3JtYXQgREQvTU0vWVlZWSIsIm1heExlbmd0aCI6MTAsImFmdGVyIjoiYmVnaW4ifSwiZHVyYXRpb25ZWVlZIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJEdXJhdGlvbllZWVkiLCJtaW5pbXVtIjowLCJlbmREYXRlRnJvbUR1cmF0aW9uIjpbImJlZ2luIiwiZW5kIiwiZHVyYXRpb25ZWVlZIiwiZHVyYXRpb25NTSIsImR1cmF0aW9uREQiXX0sImR1cmF0aW9uTU0iOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkR1cmF0aW9uTU0iLCJtYXhpbXVtIjoxMSwibWluaW11bSI6MCwiZW5kRGF0ZUZyb21EdXJhdGlvbiI6WyJiZWdpbiIsImVuZCIsImR1cmF0aW9uWVlZWSIsImR1cmF0aW9uTU0iLCJkdXJhdGlvbkREIl19LCJkdXJhdGlvbkREIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJEdXJhdGlvbkREIiwibWF4aW11bSI6MzAsIm1pbmltdW0iOjAsImVuZERhdGVGcm9tRHVyYXRpb24iOlsiYmVnaW4iLCJlbmQiLCJkdXJhdGlvbllZWVkiLCJkdXJhdGlvbk1NIiwiZHVyYXRpb25ERCJdfX19LCJ2ZXJzaW9uIjoxLCJmaWVsZElkIjoibHNfY29udHJhY3RfdHlwZV9kYXRlcyJ9LCJmaWVsZDIiOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

Description
When using if then else in a schema that is containing a $id or id attribute, the if the else is not working as expected

Steps to Reproduce
Follow link to playground
Change the duration type field to CDD 

Expected behavior
The fields end and durationYYYY durationMM DurationDD should be present

Actual behavior
The fields end and durationYYYY durationMM DurationDD are not displayed

Versions
4.1.0 & 4.1.1

### LINKED ISSUE #3212: "allOf" doesn't work with $parameters set in JSON
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

Playground version applies as well

### Current Behavior

I'm using "allOf" to declare some dependencies on a checkbox field.
This works absolutely fine with my test script.
But when I try it with my production script it doesn't.
My production script uses two variables, $id and $schema, needed for the website to render properly.
You can see the behavior in this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSJdLCJUYWlsIjp7IlRhaWwgbmFtZSI6IkxvbmcifSwiQnVyIjoiYnJvd24iLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQifSwic2NoZW1hIjp7IiRpZCI6IkFtc3RlcmRhbVVNQy0wMSIsIiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSIsImRlZmluaXRpb25zIjp7InN0cmluZ05vcm1hbCI6eyJ0eXBlIjoic3RyaW5nIiwibWF4TGVuZ3RoIjoyNTV9LCJzdHJpbmdOb3JtYWxOdWxsYWJsZSI6eyJ0eXBlIjpbInN0cmluZyIsIm51bGwiXSwibWF4TGVuZ3RoIjoyNTV9LCJzdHJpbmdMb25nIjp7InR5cGUiOiJzdHJpbmciLCJtYXhMZW5ndGgiOjI3MDB9LCJvcHRpb25zX0xhbmd1YWdlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkVuZ2xpc2giLCJEdXRjaCIsIk90aGVyIl19LCJvcHRpb25zX0RhdGF0eXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImkgQmlvbG9naWNhbCBzYW1wbGVzIiwiaWkgR2VuZXRpYyAvIG9taWNzIGRhdGEiLCJpaWkgSW1hZ2luZyBkYXRhIiwiaXYgUXVhbGl0YXRpdmUgZGF0YSBhbmQgcXVhbnRpdGF0aXZlIHF1ZXN0aW9ubmFpcmVzIiwidiBQaHlzaW9sb2dpY2FsIGRhdGEiLCJ2aSBTeW50aGV0aWMgZGF0YSJdfSwib3B0aW9uc19zdWJqZWN0X3R5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiSHVtYW4iLCJBbmltYWwiXX0sIm9wdGlvbnNfbGFiX2RhdGEiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiWWVzIiwiTm8iXX0sIm9wdGlvbnNfc2FtcGxlX3R5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiRE5BIiwiUk5BIiwiU2VydW0iLCJQbGFzbWEiLCJVcmluZSIsIkZhZWNlcyJdfSwib3B0aW9uc19vbWljc19kYXRhdHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJHZW5vbWljcyIsIk1ldGFib2xvbWljcyIsIlByb3Rlb21pY3MiLCJUcmFuc2NyaXB0b21pY3MiLCJSTkFTZXEiXX0sIm9wdGlvbnNfcHJpbWFyeV9kYXRhIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIlllcyIsIk5vIl19LCJvcHRpb25zX3NlY29uZGFyeV9kYXRhIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIlllcyIsIk5vIl19LCJvcHRpb25zX2ltYWdpbmdfdHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJEaWFnbm9zdGljIGltYWdpbmciLCJJbnRlcnZlbnRpb25hbCByYWRpb2xvZ3kiXX0sIm9wdGlvbnNfaW1hZ2luZ19tb2RhbGl0eSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJYLVJheSIsIkVDSE8iLCJDVCIsIkNUQSIsIk1SSSIsImZNUkkiLCJQRVQiLCJQRVQtQ1QiLCJQRVQtTVJJIiwiU1BFQ1QiLCJDQkNUIiwiRmx1b3Jvc2NvcHkiXX0sIm9wdGlvbnNfcGh5c2lvbG9naWNhbF9kYXRhX3R5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiUGh5c2ljYWwgZGF0YSIsIkJpb2NoZW1pY2FsIGRhdGEiLCJNYWNoaW5lIHJlYWRhYmxlIGJpb3NpZ25hbHMiXX0sIm9wdGlvbnNfcGh5c2lvbG9naWNhbF9kYXRhX2NvbGxlY3Rpb24iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiU2VsZi1tZWFzdXJlZCIsIk1lYXN1cmVkIGJ5IGhlYWx0aCBjYXJlIHByb3ZpZGVyIiwiTWVhc3VyZWQgYnkgc29tZW9uZSBlbHNlIl19fSwicmVxdWlyZWQiOlsiSWRlbnRpZmllciIsIkNyZWF0b3IiLCJjcmVhdG9yX2lkIiwiY3JlYXRvcl9hZmZpbGlhdGlvbiIsImxpY2VuY2UiLCJUaXRsZSIsInRvcGljIiwieWVhcl9jcmVhdGVkIiwieWVhcl91cGRhdGVkIiwieWVhcl9wdWJsaXNoZWQiLCJQdWJsaXNoZXIiLCJjb250cmlidXRvciIsImNvbnRhY3QiXSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiRmlyc3QgbmFtZSIsInVuaXF1ZUl0ZW1zIjp0cnVlLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJBIiwiQiIsIkMiLCJEIl19fSwiSWRlbnRpZmllciI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IldoYXQgaXMgdGhlIFBlcnNpc3RlbnQgSWRlbnRpZmllciBvZiB0aGUgZGF0YSBzZXQ/In0sIkNyZWF0b3IiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJXaG8gaXMgdGhlIGNyZWF0b3Igb2YgdGhlIGRhdGEgc2V0PyJ9LCJjcmVhdG9yX2lkIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiV2hhdCBpcyB0aGUgdW5pcXVlIGlkZW50aWZpZXIgb2YgdGhlIGNyZWF0b3Igb2YgdGhlIGRhdGEgc2V0PyJ9LCJjcmVhdG9yX2FmZmlsaWF0aW9uIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiV2hhdCBpcyB0aGUgYWZmaWxpYXRpb24gb2YgdGhlIGNyZWF0b3Igb2YgdGhlIGRhdGEgc2V0PyJ9LCJsaWNlbmNlIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiV2hhdCBpcyB0aGUgbGljZW5jZSB0aGF0IGlzIGFwcGxpZWQgdG8gdGhlIGRhdGEgc2V0PyJ9LCJUaXRsZSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IldoYXQgaXMgdGhlIHRpdGxlIG9mIHRoZSBkYXRhIHNldD8ifSwidG9waWMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJXaGF0IGlzIHRoZSB0b3BpYyBvZiB0aGUgcmVzZWFyY2ggcmVsYXRlZCB0byB0aGlzIGRhdGEgc2V0PyJ9LCJ5ZWFyX2NyZWF0ZWQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJJbiB3aGljaCB5ZWFyIHdhcyB0aGUgZGF0YSBzZXQgY3JlYXRlZCBhbmQvb3IgY29sbGVjdGVkPyJ9LCJ5ZWFyX3VwZGF0ZWQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJJbiB3aGljaCB5ZWFyIHdhcyB0aGUgZGF0YSBzZXQgdXBkYXRlZCBmb3IgdGhlIGxhc3QgdGltZT8ifSwieWVhcl9wdWJsaXNoZWQiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IldoYXQgaXMgdGhlIHllYXIgdGhlIGRhdGFzZXQgd2FzIHB1Ymxpc2hlZC9pc3N1ZWQ/In0sInZlcnNpb24iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJXaGF0IGlzIHRoZSB2ZXJzaW9uIG51bWJlciBvZiB0aGUgc3RvcmVkIGRhdGEgc2V0PyJ9LCJGb3JtYXQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJXaGF0IGlzIHRoZSBmb3JtYXQgb2YgdGhlIHN0b3JlZCBkYXRhIHNldD8ifSwic2l6ZSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IldoYXQgaXMgdGhlIHNpemUgb2YgdGhlIHN0b3JlZCBkYXRhIHNldD8ifSwiTGFuZ3VhZ2UiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uc19MYW5ndWFnZSIsInRpdGxlIjoiV2hpY2ggbGFuZ3VhZ2UgaXMgdXNlZCBpbiB0aGUgZGF0YSBzZXQ/In0sImZ1bmRlciI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IldobyBpcyB0aGUgZnVuZGVyIG9mIHRoZSByZXNlYXJjaCByZWxhdGVkIHRvIHRoaXMgZGF0YSBzZXQ/In0sIlB1Ymxpc2hlciI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IldobyBpcyB0aGUgcHVibGlzaGVyIG9mIHRoaXMgZGF0YSBzZXQ/In0sImNvbnRyaWJ1dG9yIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiV2hvIGlzIChhcmUpIHRoZSBjb250cmlidXRvcihzKSB0byB0aGlzIGRhdGEgc2V0PyAifSwiY29udGFjdCI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IkNvbnRhY3QgZGV0YWlscyJ9LCJEYXRhdHlwZSI6eyJlbnVtIjpbImkgQmlvbG9naWNhbCBzYW1wbGVzIiwiaWkgR2VuZXRpYyAvIG9taWNzIGRhdGEiLCJpaWkgSW1hZ2luZyBkYXRhIiwiaXYgUXVhbGl0YXRpdmUgZGF0YSBhbmQgcXVhbnRpdGF0aXZlIHF1ZXN0aW9ubmFpcmVzIiwidiBQaHlzaW9sb2dpY2FsIGRhdGEiLCJ2aSBTeW50aGV0aWMgZGF0YSJdfSwic3ViamVjdF90eXBlIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL29wdGlvbnNfc3ViamVjdF90eXBlIiwidGl0bGUiOiJXaGF0IGlzIHRoZSBzdWJqZWN0IHR5cGUgaW4gdGhlIGRhdGEgc2V0PyJ9LCJzdWJqZWN0X2Ftb3VudCI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiTnVtYmVyIG9mIHN1YmplY3RzIGluY2x1ZGVkIGluIHRoZSBkYXRhIHNldCJ9LCJzdWJqZWN0X2hlYWx0aCI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IlN1YmplY3QgaGVhbHRoIGNvbmRpdGlvbiJ9LCJsYWJfZGF0YSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb25zX2xhYl9kYXRhIiwidGl0bGUiOiJMYWJvcmF0b3J5IGRhdGEgcHJlc2VudD8ifSwicHJpbWFyeV9kYXRhIjp7ImVudW0iOlsiWWVzIiwiTm8iXX0sInNlY29uZGFyeV9kYXRhIjp7ImVudW0iOlsiWWVzIiwiTm8iXX0sImltYWdpbmdfZGVzY3JpcHRpb24iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJQcm92aWRlIGEgc2hvcnQgZGVzY3JpcHRpb24gb2YgdGhlIGltYWdpbmcgc3R1ZHksIGUuZy4sIE1SSSBrbmVlIn0sImltYWdpbmdfc3RvcmFnZV9zeXN0ZW0iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJXaGF0IGlzIHRoZSBzeXN0ZW0gd2hlcmUgdGhlIGltYWdpbmcgZGF0YSBhcmUgc3RvcmVkPyJ9LCJ2aWRlb19pbnRlcnZpZXdfbmFtZV9kZXNjcmlwdGlvbiI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IkZvciB2aWRlbyBpbnRlcnZpZXdzIHBsZWFzZSBwcm92aWRlIHByb3RvY29sIG5hbWUgb3IgYnJpZWYgZGVzY3JpcHRpb24ifSwicGh5c2lvbG9naWNhbF9kYXRhX2NvbGxlY3Rpb24iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uc19waHlzaW9sb2dpY2FsX2RhdGFfY29sbGVjdGlvbiIsInRpdGxlIjoiRGF0YSBjb2xsZWN0aW9uIG1ldGhvZCJ9fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJUYWlsIjp7InByb3BlcnRpZXMiOnsiVGFpbCBuYW1lIjp7ImRlZmF1bHQiOiJMb25nIiwiZW51bSI6WyJMb25nIiwiU2hvcnQiLCJOb25lIl0sInRpdGxlIjoiVGFpbCBsZW5ndGgiLCJ0eXBlIjoic3RyaW5nIn19fX0sImFsbE9mIjpbeyJpZiI6eyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7IkZ1ciI6eyJkZWZhdWx0IjoiYnJvd24iLCJlbnVtIjpbImJsYWNrIiwiYnJvd24iXSwidGl0bGUiOiJGdXIiLCJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJGdXIiXX19LHsiaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJDIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJCdXIiOnsiZGVmYXVsdCI6ImJyb3duIiwiZW51bSI6WyJibGFjayIsImJyb3duIl0sInRpdGxlIjoiQnVyIiwidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiRnVyIl19fV0sInJlcXVpcmVkIjpbIlRhaWwiXX19LHsiaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJCIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJUYWlsIjp7InByb3BlcnRpZXMiOnsiVGFpbCBuYW1lIjp7ImRlZmF1bHQiOiJMb25nIiwiZW51bSI6WyJMb25nIiwiU2hvcnQiLCJOb25lIl0sInRpdGxlIjoiQmFpbCBsZW5ndGgiLCJ0eXBlIjoic3RyaW5nIn19fX0sImFsbE9mIjpbeyJpZiI6eyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkEifX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7IkZ1ciI6eyJkZWZhdWx0IjoiYnJvd24iLCJlbnVtIjpbImJsYWNrIiwiYnJvd24iXSwidGl0bGUiOiJBdXIiLCJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJGdXIiXX19LHsiaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJDIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJCdXIiOnsiZGVmYXVsdCI6ImJyb3duIiwiZW51bSI6WyJibGFjayIsImJyb3duIl0sInRpdGxlIjoiQ3VyIiwidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiRnVyIl19fV0sInJlcXVpcmVkIjpbIlRhaWwiXX19XX0sIkRhdGF0eXBlIjp7Im9uZU9mIjpbeyJ0aXRsZSI6IkRhdGF0eXBlIiwicHJvcGVydGllcyI6eyJEYXRhdHlwZSI6eyJlbnVtIjpbImkgQmlvbG9naWNhbCBzYW1wbGVzIl19LCJkZXBlbmRlbnRfb2JqZWN0XzEiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiRGF0YXR5cGUgY2hpbGQocmVuKSIsInByb3BlcnRpZXMiOnsic2FtcGxlX3R5cGUiOnsidHlwZSI6InN0cmluZyIsIiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiV2hhdCB0eXBlIG9mIGJpb2xvZ2ljYWwgc2FtcGxlcyBhcmUgYXZhaWxhYmxlPyJ9LCJzdG9yYWdlX3RlbXAiOnsidHlwZSI6InN0cmluZyIsIiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiU3RvcmFnZSB0ZW1wZXJhdHVyZSJ9fX19fSx7InRpdGxlIjoiRGF0YXR5cGUiLCJwcm9wZXJ0aWVzIjp7IkRhdGF0eXBlIjp7ImVudW0iOlsiaWkgR2VuZXRpYyAvIG9taWNzIGRhdGEiXX0sImRlcGVuZGVudF9vYmplY3RfMiI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJEYXRhdHlwZSBjaGlsZChyZW4pIiwicHJvcGVydGllcyI6eyJvbWljc19kYXRhdHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJUeXBlIG9mIG1lYXN1cmVkIGdlbmV0aWMgb3Igb21pY3MgZGF0YSJ9fX19fSx7InRpdGxlIjoiRGF0YXR5cGUiLCJwcm9wZXJ0aWVzIjp7IkRhdGF0eXBlIjp7ImVudW0iOlsiaWlpIEltYWdpbmcgZGF0YSJdfSwiZGVwZW5kZW50X29iamVjdF8zIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkRhdGF0eXBlIGNoaWxkKHJlbikiLCJwcm9wZXJ0aWVzIjp7ImltYWdpbmdfdHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJUeXBlIG9mIGltYWdpbmcifSwiaW1hZ2luZ19tb2RhbGl0eSI6eyJ0eXBlIjoic3RyaW5nIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJJbWFnaW5nIG1vZGFsaXR5In19fX19LHsidGl0bGUiOiJEYXRhdHlwZSIsInByb3BlcnRpZXMiOnsiRGF0YXR5cGUiOnsiZW51bSI6WyJpdiBRdWFsaXRhdGl2ZSBkYXRhIGFuZCBxdWFudGl0YXRpdmUgcXVlc3Rpb25uYWlyZXMiXX0sImRlcGVuZGVudF9vYmplY3RfNCI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJEYXRhdHlwZSBjaGlsZChyZW4pIiwicHJvcGVydGllcyI6eyJxdWVzdGlvbm5haXJlX25hbWVfdmVyc2lvbiI6eyJ0eXBlIjoic3RyaW5nIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvc3RyaW5nTm9ybWFsIiwidGl0bGUiOiJRdWVzdGlvbm5haXJlIG5hbWUgYW5kLCBpZiBhcHBsaWNhYmxlIHZlcnNpb24gbnVtYmVyIn19fX19LHsidGl0bGUiOiJEYXRhdHlwZSIsInByb3BlcnRpZXMiOnsiRGF0YXR5cGUiOnsiZW51bSI6WyJ2IFBoeXNpb2xvZ2ljYWwgZGF0YSJdfSwiZGVwZW5kZW50X29iamVjdF81Ijp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkRhdGF0eXBlIGNoaWxkKHJlbikiLCJwcm9wZXJ0aWVzIjp7InBoeXNpb2xvZ2ljYWxfZGF0YV90eXBlIjp7InR5cGUiOiJzdHJpbmciLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IlR5cGUgb2YgUGh5c2lvbG9naWNhbCBkYXRhIn19fX19XX0sInByaW1hcnlfZGF0YSI6eyJvbmVPZiI6W3sidGl0bGUiOiJwcmltYXJ5X2RhdGEiLCJwcm9wZXJ0aWVzIjp7InByaW1hcnlfZGF0YSI6eyJlbnVtIjpbIlllcyJdfSwiZGVwZW5kZW50X29iamVjdF82Ijp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6InByaW1hcnlfZGF0YSBjaGlsZChyZW4pIiwicHJvcGVydGllcyI6eyJwcmltYXJ5X2RhdGFfbG9jYXRpb24iOnsidHlwZSI6InN0cmluZyIsIiRyZWYiOiIjL2RlZmluaXRpb25zL3N0cmluZ05vcm1hbCIsInRpdGxlIjoiUHJpbWFyeSBkYXRhIGxvY2F0aW9uIn19fX19XX0sInNlY29uZGFyeV9kYXRhIjp7Im9uZU9mIjpbeyJ0aXRsZSI6InNlY29uZGFyeV9kYXRhIiwicHJvcGVydGllcyI6eyJzZWNvbmRhcnlfZGF0YSI6eyJlbnVtIjpbIlllcyJdfSwiZGVwZW5kZW50X29iamVjdF83Ijp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6InNlY29uZGFyeV9kYXRhIGNoaWxkKHJlbikiLCJwcm9wZXJ0aWVzIjp7InNlY29uZGFyeV9kYXRhX2xvY2F0aW9uIjp7InR5cGUiOiJzdHJpbmciLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9zdHJpbmdOb3JtYWwiLCJ0aXRsZSI6IlNlY29uZGFyeSBkYXRhIGxvY2F0aW9uIn19fX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Expected Behavior

The expected behavior is the former script without the $id and $schema parameter, [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOltdLCJUYWlsIjp7IlRhaWwgbmFtZSI6IkxvbmcifSwiRnVyIjoiYnJvd24iLCJCdXIiOiJicm93biIsImRlcGVuZGVudF9vYmplY3RfMSI6e30sImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiRmlyc3QgbmFtZSIsInVuaXF1ZUl0ZW1zIjp0cnVlLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJBIiwiQiIsIkMiLCJEIl19fX0sImRlcGVuZGVuY2llcyI6eyJmaXJzdE5hbWUiOnsiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiVGFpbCI6eyJwcm9wZXJ0aWVzIjp7IlRhaWwgbmFtZSI6eyJkZWZhdWx0IjoiTG9uZyIsImVudW0iOlsiTG9uZyIsIlNob3J0IiwiTm9uZSJdLCJ0aXRsZSI6IlRhaWwgbGVuZ3RoIiwidHlwZSI6InN0cmluZyJ9fX19LCJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJCIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJGdXIiOnsiZGVmYXVsdCI6ImJyb3duIiwiZW51bSI6WyJibGFjayIsImJyb3duIl0sInRpdGxlIjoiRnVyIiwidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiRnVyIl19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQyJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiQnVyIjp7ImRlZmF1bHQiOiJicm93biIsImVudW0iOlsiYmxhY2siLCJicm93biJdLCJ0aXRsZSI6IkJ1ciIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbIkZ1ciJdfX1dLCJyZXF1aXJlZCI6WyJUYWlsIl19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQiJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiVGFpbCI6eyJwcm9wZXJ0aWVzIjp7IlRhaWwgbmFtZSI6eyJkZWZhdWx0IjoiTG9uZyIsImVudW0iOlsiTG9uZyIsIlNob3J0IiwiTm9uZSJdLCJ0aXRsZSI6IkJhaWwgbGVuZ3RoIiwidHlwZSI6InN0cmluZyJ9fX19LCJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJGdXIiOnsiZGVmYXVsdCI6ImJyb3duIiwiZW51bSI6WyJibGFjayIsImJyb3duIl0sInRpdGxlIjoiQXVyIiwidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiRnVyIl19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQyJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiQnVyIjp7ImRlZmF1bHQiOiJicm93biIsImVudW0iOlsiYmxhY2siLCJicm93biJdLCJ0aXRsZSI6IkN1ciIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbIkZ1ciJdfX1dLCJyZXF1aXJlZCI6WyJUYWlsIl19fV19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTp3aWRnZXQiOiJjaGVja2JveGVzIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Steps To Reproduce

see playground link above

### Environment

```markdown
Unrelated to the environment, since it doesn't work in the playground either, see above.
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nickgros**
@rjsf/validator-ajv8
- BREAKING: No longer attempt to validate data against invalid schemas
- Use pre-compiled validator from Ajv if the schema has an $id
- isValid: Use rootSchema.$id over the default value if it exists (Ajv uses it anyway)
- isValid: Log warning on compilation error

### Reasons for making this change

Fixes #2821, fixes #3212

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/validator-ajv8/src/validator.ts [hunk 1]
```diff
@@ -245,22 +245,35 @@ export default class AJV8Validator<
...
+    let compiledValidator: ValidateFunction | undefined;
+    if (schema["$id"]) {
+      compiledValidator = this.ajv.getSchema(schema["$id"]);
+    }
     try {
-      this.ajv.validate(schema, formData);
+      if (compiledValidator === undefined) {
+        compiledValidator = this.ajv.compile(schema);
+      }
+      compiledValidator(formData);
```
Comment (nickgros) [inline packages/validator-ajv8/src/validator.ts:257]: `validate` throws an error if you try to compile a schema that you've already compiled (based on $id).

This may also improve performance.

File: packages/validator-ajv8/src/validator.ts [hunk 2]
```diff
@@ -366,25 +379,37 @@ export default class AJV8Validator<
...
+      const result = compiledValidator(formData);
       return result as boolean;
     } catch (e) {
+      console.warn("Error encountered compiling schema:", e);
       return false;
     } finally {
+      // TODO: A function should be called if the root schema changes so we don't have to remove and recompile the schema every run.
       // make sure we remove the rootSchema from the global ajv instance
-      this.ajv.removeSchema(ROOT_SCHEMA_PREFIX);
+      this.ajv.removeSchema(rootSchemaId);
```
Comment (nickgros) [inline packages/validator-ajv8/src/validator.ts:412]: I'd prefer if we had something like `validator.setRootSchema(...)`, which I think could help performance for complex if/then/else cases. But that's a bigger project for another day.

File: packages/validator-ajv8/src/validator.ts [hunk 3]
```diff
@@ -366,25 +379,37 @@ export default class AJV8Validator<
...
       // add the rootSchema ROOT_SCHEMA_PREFIX as id.
       // then rewrite the schema ref's to point to the rootSchema
       // this accounts for the case where schema have references to models
       // that lives in the rootSchema but not in the schema in question.
-      const result = this.ajv
-        .addSchema(rootSchema, ROOT_SCHEMA_PREFIX)
-        .validate(this.withIdRefPrefix(schema), formData);
+      if (this.ajv.getSchema(rootSchemaId) === undefined) {
+        this.ajv.addSchema(rootSchema, rootSchemaId);
+      }
```
Comment (nickgros) [inline packages/validator-ajv8/src/validator.ts:395]: Note that if `rootSchema` has an $id, the second parameter is ignored.

File: packages/validator-ajv8/test/validator.test.ts [hunk 4]
```diff
@@ -72,6 +72,34 @@ describe("AJV8Validator", () => {
...
+
+        // @ts-expect-error - accessing private Ajv instance to verify compilation happens once
+        const compileSpy = jest.spyOn(validator.ajv, "compile");
+        compileSpy.mockClear();
+
+        // Call isValid twice with the same schema
+        validator.isValid(schema, formData, rootSchema);
+        validator.isValid(schema, formData, rootSchema);
+
+        expect(compileSpy).toHaveBeenCalledTimes(1);
```
Comment (nickgros) [inline packages/validator-ajv8/test/validator.test.ts:101]: I hate doing this but I can't think of a better way to test this behavior

File: packages/validator-ajv8/test/validator.test.ts [hunk 5]
```diff
@@ -401,26 +452,19 @@ describe("AJV8Validator", () => {
...
-            "#/definitions/stringArray/type"
-          );
-          expect(errors[0].message).toEqual("must be array");
-
-          expect(errors[1].stack).toEqual(
+          expect(errors).toHaveLength(1);
+          expect(errors[0].stack).toEqual(
             "schema is invalid: data/properties/foo/required must be array"
           );
         });
```
Comment (nickgros) [inline packages/validator-ajv8/test/validator.test.ts:459]: Breaking change (need to document)--if the schema is invalid, don't attempt to validate the data.

I made this change because otherwise we would have to do something like

```js
try {
	compiledSchema = this.ajv.compile(schema)
	compiledSchema.validate(data)
} catch (e1) {
	try {
		this.ajv.validate(schema, data)
	} catch (e2) {
		compilationError = e2;
	}
}
```

IMO this was getting too complex to support a case that probably shouldn't be happening.

**Review by jacqueswho — APPROVED** [review]

File: packages/validator-ajv8/src/validator.ts (hunk 1 above)
Comment (heath-freenome) [reply packages/validator-ajv8/src/validator.ts:257]: Do we want to cache the compiled validator using a Map with the schema as a key? I'm not sure how much time it takes to compile it, but if it is a big schema it might save time on subsequent validations?

File: packages/validator-ajv8/src/validator.ts (hunk 2 above)
Comment (heath-freenome) [reply packages/validator-ajv8/src/validator.ts:412]: If I remember how it is used, isValid is used primarily for multi-schema use cases. Not sure if the rootSchema is always the same. We could also consider caching it in a Map in the future too.

**Comment by heath-freenome** [comment]
Does this fix https://github.com/rjsf-team/react-jsonschema-form/issues/3212 too?

**Comment by nickgros** [comment]
> Does this fix #3212 too?
Seems like it does. I'll link the issue and then merge.

File: packages/validator-ajv8/src/validator.ts (hunk 1 above)
Comment (nickgros) [reply packages/validator-ajv8/src/validator.ts:257]: I'd rather use the Ajv cache if possible, one less thing for us to get wrong. Though that might not work for conditional logic where we may create various subschemas that have no $id

File: packages/validator-ajv8/src/validator.ts (hunk 2 above)
Comment (nickgros) [reply packages/validator-ajv8/src/validator.ts:412]: I think the rootSchema is always the same, unless the Form schema prop changes. It's just provided here to resolve refs and definitions.
