### PR TITLE
fix: Fixed FileWidget to work across all themes

### LINKED ISSUE #2095: [bootstrap-4] File uploads result in error ".file should match format "data-url""
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using the `bootstrap-4` theme, submitting a file triggers an error:

```
.file should match format "data-url"
```

### Steps to Reproduce

1. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWxlIjoiQzpcXGZha2VwYXRoXFxXZWJTdG9ybS0yMDIwLjIuMy5leGUifSwic2NoZW1hIjp7InRpdGxlIjoiRmlsZXMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaWxlIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRhLXVybCIsInRpdGxlIjoiU2luZ2xlIGZpbGUifSwiZmlsZXMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJNdWx0aXBsZSBmaWxlcyIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRhLXVybCJ9fSwiZmlsZXNBY2NlcHQiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGEtdXJsIiwidGl0bGUiOiJTaW5nbGUgRmlsZSB3aXRoIEFjY2VwdCBhdHRyaWJ1dGUifX19LCJ1aVNjaGVtYSI6eyJmaWxlc0FjY2VwdCI6eyJ1aTpvcHRpb25zIjp7ImFjY2VwdCI6Ii5wZGYifX19LCJ0aGVtZSI6ImJvb3RzdHJhcC00IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
2. Click "Choose file" for the first file upload
3. Select any file from your computer
4. Click "Submit"

#### Expected behavior

No errors are displayed.

#### Actual behavior

The following error is displayed:

```
.file should match format "data-url"
```

### Version

`master`

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes #2095 by making `FileWidget` use the `BaseInputTemplate` for rendering the file input
- Updated `@rjsf/utils` to fix two small bugs found while fixing the issue:
  - `dataURItoBlob()` was updated to deal with parsing errors in `atob()` with malformed URL and to decode the name to a human-readable string - Added additional tests to verify the fixes
  - `replaceStringParameters()` was updated to split using a regex to deal with situations where the params themselves contain replaceable character identifiers
    - Added an additional test to verify the bug was fixed
- Updated `@rjsf/core` to switch `FileWidget` so that it uses the `BaseInputTemplate` to render the input, passing a new `onChangeOverride` function to deal with file events
  - Updated `BaseInputTemplate` to favor `onChangeOverride` rather than the default `onChange` handler it builds
- Updated the `BaseInputTemplate` in all of the themes to also favor `onChangeOverride` if specified over the default `onChange` handler
  - Updated the snapshots in all themes to reflect the improved `FileWidget` use of `BaseInputTemplate` in all themes
- Updated `@rjsf/bootstrap-4` to delete the `FileWidget` in favor of the improved `core` one
- Updated `@rjsf/material-ui` and `@rjsf/mui` to have the `BaseInputTemplate` support the automatic `shrink` of the label when the `type` of the input is `date`, `datetime-local` and `file`
  - Also removed the `DateWidget` and `DateTimeWidget` in both themes since they were only providing the `shrink` behavior which is now encapsulated in `BaseInputTemplate`
- Updated the `CHANGELOG.md` file accordingly
 
### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/widgets/FileWidget.tsx [hunk 1]
```diff
@@ -150,20 +147,14 @@ function FileWidget<
...
-          multiple={multiple}
-          accept={options.accept ? String(options.accept) : undefined}
-          aria-describedby={ariaDescribedByIds<T>(id)}
-        />
-      </p>
+      <BaseInputTemplate
+        {...props}
+        disabled={disabled || readonly}
+        type="file"
+        onChangeOverride={handleChange}
```
Comment (nickgros) [inline packages/core/src/components/widgets/FileWidget.tsx:154]: How were you able to supply this `onChangeOverride` prop without adding it to the `WidgetProps` type?

File: packages/antd/src/templates/BaseInputTemplate/index.tsx [hunk 2]
```diff
@@ -46,8 +47,10 @@ export default function BaseInputTemplate<
 
   const handleNumberChange = (nextValue: number | null) => onChange(nextValue);
 
-  const handleTextChange = ({ target }: React.ChangeEvent<HTMLInputElement>) =>
-    onChange(target.value === "" ? options.emptyValue : target.value);
+  const handleTextChange = onChangeOverride
+    ? onChangeOverride
+    : ({ target }: React.ChangeEvent<HTMLInputElement>) =>
+        onChange(target.value === "" ? options.emptyValue : target.value);
```
Comment (nickgros) [inline packages/antd/src/templates/BaseInputTemplate/index.tsx:53]: This default `onChange` behavior is duplicated across all themes. Might make more sense to refactor to utils, e.g.

```ts
// Is there a better name?
export default function useOnEventTargetStringChange<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any
>(
  options: WidgetProps<T, S, F>["options"],
  onChange: WidgetProps<T, S, F>["onChange"]
) {
  return useCallback(
    ({ target: { value } }: React.ChangeEvent<HTMLInputElement>) =>
      onChange(value === "" ? options.emptyValue : value),
    [onChange, options.emptyValue]
  );
}
```

I am leaning towards the idea that this logic should be extracted from `BaseInputTemplate` altogether, since it doesn't work for all cases. Then we wouldn't need an `onChangeOverrides` prop. The downside is that we would have to pass this in almost every time we use `BaseInputTemplate`:


```tsx
export default function CustomWidget() {
  const { onChange: _onChange, value, options, registry } = props;
  const BaseInputTemplate = getTemplate<"BaseInputTemplate", T, S, F>(
    "BaseInputTemplate",
    registry,
    options
  );
  const onChange = useOnEventTargetStringChange(options, _onChange)
  return (
    <BaseInputTemplate
      {...props}
      onChange={onChange}
    />
  );
}
```

I'm not sure if this verbosity + inversion is worth it for one (known) edge case...WDYT?

File: packages/core/src/components/widgets/FileWidget.tsx (hunk 1 above)
Comment (nickgros) [reply packages/core/src/components/widgets/FileWidget.tsx:154]: Is file upload the only case that would benefit from this style?

Having both `onChange` and `onChangeOverride` seems like a confusing API, but I'm not sure if it should be clarified with better prop names or if it should have a different design.

File: packages/material-ui/src/BaseInputTemplate/BaseInputTemplate.tsx [hunk 3]
```diff
@@ -66,6 +70,12 @@ export default function BaseInputTemplate<
 
   const { schemaUtils } = registry;
   const displayLabel = schemaUtils.getDisplayLabel(schema, uiSchema);
+  const DisplayInputLabelProps = TYPES_THAT_SHRINK_LABEL.includes(type)
+    ? {
+        ...InputLabelProps,
+        shrink: true,
+      }
+    : InputLabelProps;
```
Comment (nickgros) [inline packages/material-ui/src/BaseInputTemplate/BaseInputTemplate.tsx:78]: Nice simplification

File: packages/antd/src/templates/BaseInputTemplate/index.tsx (hunk 2 above)
Comment (nickgros) [reply packages/antd/src/templates/BaseInputTemplate/index.tsx:53]: A lower-lift option is to extend the default logic to also handle files (possibly being aware of the input type).

```ts
export default function useOnChangeEvent<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any
>(
  options: WidgetProps<T, S, F>["options"],
  onChange: WidgetProps<T, S, F>["onChange"],
  isFileInput?: boolean
) {
  return useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      if (isFileInput) {
	// ...
      } else {
        onChange(value === "" ? options.emptyValue : value)
      }
    },
    [onChange, options.emptyValue, isFileInput]
  );
}
```

**Review by nickgros — COMMENTED** [review]
Like the fix but not sure about the approach, have some suggestions but not sure if they are what we want either

**Review by nickgros — APPROVED** [review]
