### PR TITLE
Fix incorrect allOf merging (fix #2923) (Reimplement #3025)

### LINKED ISSUE #2923: Wrong allOf behaviour
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.0

### Expected Behavior

Should be valid

### Steps To Reproduce

Example
---
- [Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJkYXRhIjpbeyJ2YWx1ZSI6IjEyMyJ9LHsidmFsdWUiOiI0NTYifV19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZGF0YSI6eyJ0eXBlIjoiYXJyYXkiLCJhbGxPZiI6W3siY29udGFpbnMiOnsicmVxdWlyZWQiOlsidmFsdWUiXSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsicGF0dGVybiI6IjQ1NiJ9fX19LHsiY29udGFpbnMiOnsicmVxdWlyZWQiOlsidmFsdWUiXSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsicGF0dGVybiI6IjEyMyJ9fX19XSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInZhbHVlIl0sInByb3BlcnRpZXMiOnsidmFsdWUiOnsiZW51bSI6WyIxMjMiLCI0NTYiLCI3ODkiXSwidHlwZSI6InN0cmluZyJ9fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
- [AJV validator](https://www.jsonschemavalidator.net/s/Ys5pFYJg)

Schema
---
```JSON
{
  "type": "object",
  "properties": {
    "data": {
      "type": "array",
      "allOf": [
        {
          "contains": {
            "required": [
              "value"
            ],
            "type": "object",
            "properties": {
              "value": {
                "pattern": "456"
              }
            }
          }
        },
        {
          "contains": {
            "required": [
              "value"
            ],
            "type": "object",
            "properties": {
              "value": {
                "pattern": "123"
              }
            }
          }
        }
      ],
      "items": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "enum": [
              "123",
              "456",
              "789"
            ],
            "type": "string"
          }
        }
      }
    }
  }
}
```

Data
---
```JSON
{
  "data": [
    {
      "value": "123"
    },
    {
      "value": "456"
    }
  ]
}
```

### Environment

```markdown
- OS: any
- Node: any
- npm: any
```

### Anything else?

- The problem is caused by `jsonschema-merge-allof` that is merging allOf values into the schema:
```
      "contains": {
        "required": [
          "value"
        ],
        "type": "object",
        "properties": {
          "value": {
            "allOf": [
              {
                "pattern": "123"
              },
              {
                "pattern": "456"
              }
            ]
          }
        }
      }
```
- This example was workable before [this](https://github.com/rjsf-team/react-jsonschema-form/pull/2839) PR was merged. But I guess this PR just unmasked the issue.

### PR DESCRIPTION
**Pull request by nickgros**
See #3025 for more information.

It's currently hard to verify the issue in the playground because the examples seem to trigger an infinite loop of some sort that crash the page.

Fixes #2923

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/schema/getDefaultFormState.ts [hunk 1]
```diff
@@ -96,13 +96,14 @@ export function computeDefaults<
...
   validator: ValidatorType<T, S>,
-  schema: S,
+  rawSchema: S,
   parentDefaults?: T,
   rootSchema: S = {} as S,
   rawFormData?: T,
   includeUndefinedValues: boolean | "excludeObjectChildren" = false
 ): T | T[] | undefined {
   const formData = isObject(rawFormData) ? rawFormData : {};
+  let schema: S = isObject(rawSchema) ? rawSchema : ({} as S);
```
Comment (nickgros) [inline packages/utils/src/schema/getDefaultFormState.ts:106]: We have a test that passes an invalid schema and expects a specific error message. The test fails without this change because a string ends up getting passed here as `rawSchema`, and we don't get to the error case that the test does expect.

The best fix would be to actually validate the schema before we get this far, but that would be a large change that would require a lot of effort.

File: packages/utils/src/schema/toPathSchema.ts [hunk 2]
```diff
@@ -54,7 +54,7 @@ export default function toPathSchema<
 
   if (
     ADDITIONAL_PROPERTIES_KEY in schema &&
-    schema[ADDITIONAL_PROPERTIES_KEY] === true
+    schema[ADDITIONAL_PROPERTIES_KEY] !== false
```
Comment (nickgros) [inline packages/utils/src/schema/toPathSchema.ts:57]: We use the path schema to decide which objects to drop when we use `omitExtraData`. For some reason, a change here uncovered a case where the additionalProperty fields would be dropped by `omitExtraData` + `liveOmit` if the `additionalProperties` schema was an object. This fixes that regression.

**Review by heath-freenome — APPROVED** [review]

**Comment by heath-freenome** [comment]
@nickgros Can you list which actual issues this will fix in the description? Or do we just not know?

**Comment by nickgros** [comment]
> @nickgros Can you list which actual issues this will fix in the description? Or do we just not know? Or at least list the ones that we think this MIGHT fix and let them reopen if it doesn't?

I looked through and found that this fixes #2923. The gist is that the previous merge algorithm was incorrect, and @AlimovSV 's  reproduction in #2923 proves it by showing a case where incorrectly-merged subschemas returned errors when the raw AJV validation resulted in no errors. After this change, RJSF creates correct subschemas, and no errors are returned for valid data.

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,12 +17,13 @@ should change the heading of the (upcoming) version to include a major version b
...
 
-# @rjsf/core
+## @rjsf/core
 - Pass the `schema` along to the `ArrayFieldItemTemplate` as part of the fix for [#3253](https://github.com/rjsf-team/react-jsonschema-form/issues/3253)
 - Tweak Babel configuration to emit ES5-compatible output files, fixing [#3240](https://github.com/rjsf-team/react-jsonschema-form/issues/3240)
 
-# @rjsf/utils
+## @rjsf/utils
 - Update the `ArrayFieldItemTemplate` to add `schema` as part of the fix for [#3253](https://github.com/rjsf-team/react-jsonschema-form/issues/3253)
+- Fix improper merging of nested `allOf`s ([#3025](https://github.com/rjsf-team/react-jsonschema-form/pull/3025), [#3227](https://github.com/rjsf-team/react-jsonschema-form/pull/3227))
```
Comment (nickgros) [inline CHANGELOG.md:26]:
```suggestion
- Fix improper merging of nested `allOf`s ([#3025](https://github.com/rjsf-team/react-jsonschema-form/pull/3025), [#3227](https://github.com/rjsf-team/react-jsonschema-form/pull/3227)), fixing [#2923](https://github.com/rjsf-team/react-jsonschema-form/pull/2929)
```
