### PR TITLE
Bug: The oneOf selector can be modified in readonly mode

### LINKED ISSUE #4460: Values are modified in readonly mode when they are defined with oneOf
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

in readonly mode the dropdown for the oneOf is not disabled.
Changing the value there reset the fields.

### Expected Behavior

dropdown should be disabled or at least fields should not be reset.

### Steps To Reproduce

1. open this playground: 

[Playground readonly](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb250YWN0UHJlZmVyZW5jZSI6eyJjb250YWN0TWV0aG9kIjoicGhvbmUiLCJwaG9uZU51bWJlciI6IjEyMzEyMzEyMyJ9fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJ0aXRsZSI6IkV4YW1wbGUgU2NoZW1hIiwidHlwZSI6Im9iamVjdCIsInJlYWRPbmx5Ijp0cnVlLCJwcm9wZXJ0aWVzIjp7ImNvbnRhY3RQcmVmZXJlbmNlIjp7Im9uZU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9waG9uZUNvbnRhY3QifSx7IiRyZWYiOiIjL2RlZmluaXRpb25zL2VtYWlsQ29udGFjdCJ9XX19LCJyZXF1aXJlZCI6WyJjb250YWN0UHJlZmVyZW5jZSJdLCJkZWZpbml0aW9ucyI6eyJwaG9uZUNvbnRhY3QiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY29udGFjdE1ldGhvZCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJwaG9uZSJdfSwicGhvbmVOdW1iZXIiOnsidHlwZSI6InN0cmluZyIsInBhdHRlcm4iOiJeWzAtOV17MTB9JCJ9fSwicmVxdWlyZWQiOlsiY29udGFjdE1ldGhvZCIsInBob25lTnVtYmVyIl19LCJlbWFpbENvbnRhY3QiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY29udGFjdE1ldGhvZCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJlbWFpbCJdfSwiZW1haWxBZGRyZXNzIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJlbWFpbCJ9fSwicmVxdWlyZWQiOlsiY29udGFjdE1ldGhvZCIsImVtYWlsQWRkcmVzcyJdfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJ1aTplbXB0eVZhbHVlIGNhdXNlcyB0aGlzIGZpZWxkIHRvIGFsd2F5cyBiZSB2YWxpZCBkZXNwaXRlIGJlaW5nIHJlcXVpcmVkIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0ZXh0ICoqYm9sZCoqIG9yICppdGFsaWMqLiBUYWtlIGEgbG9vayBhdCBvdGhlciBvcHRpb25zIFtoZXJlXShodHRwczovL21hcmtkb3duLXRvLWpzeC5xdWFudGl6b3IuZGV2LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImNvbnN0QXNEZWZhdWx0cyI6ImFsd2F5cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyIsIm1lcmdlRGVmYXVsdHNJbnRvRm9ybURhdGEiOiJ1c2VGb3JtRGF0YUlmUHJlc2VudCJ9fSwidmFsaWRhdG9yIjoiQUpWOCJ9)

2. switch the value in the dropdown to Option 2
3. switch back to Option 1
4. Values are reset

### Environment

```markdown
- OS: ubuntu 22.04
- Node: 18
- npm:10.8.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abdalla-rko**
### Reasons for making this change

Fixes #4460 

### Checklist

- [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [X] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

**Review by nickgros — APPROVED** [review]

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 1]
```diff
@@ -237,6 +237,7 @@ class AnyOfField<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends For
             autofocus={autofocus}
             label={title ?? name}
             hideLabel={!displayLabel}
+            readonly={this.props.readonly}
```
Comment (heath-freenome) [inline packages/core/src/components/fields/MultiSchemaField.tsx:240]: Add the destructure of `readonly` from `props` above on line 155 and just use:
```suggestion
            readonly={readonly}
```

**Comment by heath-freenome** [comment]
Also resolve conflicts in the `CHANGELOG.md`
