### PR TITLE
Make fields with const pre-fiiled and readonly #3843

### LINKED ISSUE #2600: Prefilled, readonly text field for `const` string types
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- ~[ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.~
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsidXNlclR5cGUiLCJmaXJzdE5hbWUiXSwicHJvcGVydGllcyI6eyJ1c2VyVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiY29uc3QiOiJlbXBsb3llZSJ9LCJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Have a schema using `{ "type": "string", "const": "something" }`

#### Expected behavior

The `input` should have the `const` value already filled in, and have `readonly=true`

#### Actual behavior

The `input` is just a regular textbox, and the user has to type the exact value of `const` manually (without even a hint of what the value should be)

### Version

3.2.0

I'd be happy to open a PR to improve this if someone could point me in roughly the right direction.

### PR DESCRIPTION
**Pull request by abdalla-rko**
### Reasons for making this change

Continued the work from #3843. Fixes #2600.

If fields have const definition, make the value as pre-filled default and also make the fields readonly. (current logic will just ignore the const value and leave blank input for users.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/utils/src/schema/getDefaultFormState.ts [hunk 1]
```diff
@@ -190,7 +197,9 @@ export function computeDefaults<T = any, S extends StrictRJSFSchema = RJSFSchema
   let schemaToCompute: S | null = null;
   let updatedRecurseList = _recurseList;
 
-  if (isObject(defaults) && isObject(schema.default)) {
+  if (isConstant(schema)) {
+    defaults = schema.const as unknown as T;
```
Comment (heath-freenome) [inline packages/utils/src/schema/getDefaultFormState.ts:201]: Have you tested that we will always add const even when we turn off the auto-default feature?

Comment (abdalla-rko) [reply packages/utils/src/schema/getDefaultFormState.ts:201]: If you mean when the **emptyObjectFields** is set to **skipDefaults** then yes. I made a test which tests it with **skipDefaults** option.

File: packages/utils/test/schema/getDefaultFormStateTest.ts [hunk 2]
```diff
@@ -48,6 +48,20 @@ export default function getDefaultFormStateTest(testValidator: TestValidatorType
           foo: 42,
         });
       });
+      it('test computeDefaults that is passed a schema with a cont property', () => {
```
Comment (heath-freenome) [inline packages/utils/test/schema/getDefaultFormStateTest.ts:51]:
```suggestion
      it('test computeDefaults that is passed a schema with a const property', () => {
```

File: packages/utils/src/schema/getDefaultFormState.ts [hunk 3]
```diff
@@ -311,11 +320,16 @@ export function getObjectDefaults<T = any, S extends StrictRJSFSchema = RJSFSche
       experimental_defaultFormStateBehavior?.allOf === 'populateDefaults' && ALL_OF_KEY in schema
         ? retrieveSchema<T, S, F>(validator, schema, rootSchema, formData)
         : schema;
+    const parentConst = retrievedSchema[CONST_KEY];
     const objectDefaults = Object.keys(retrievedSchema.properties || {}).reduce(
       (acc: GenericObjectType, key: string) => {
+        const propertySchema = get(retrievedSchema, [PROPERTIES_KEY, key]);
+        // Check if the parent schema has a const property defined,  then we should always return the computedDefault since it's coming from the const.
```
Comment (heath-freenome) [inline packages/utils/src/schema/getDefaultFormState.ts:327]:
```suggestion
        // Check if the parent schema has a const property defined, then we should always return the computedDefault since it's coming from the const.
```

File: packages/utils/src/schema/getDefaultFormState.ts [hunk 4]
```diff
@@ -444,13 +459,17 @@ export function getArrayDefaults<T = any, S extends StrictRJSFSchema = RJSFSchem
...
   }
 
-  if (neverPopulate) {
-    return defaults ?? emptyDefault;
-  }
-  if (ignoreMinItemsFlagSet && !required) {
-    // If no form data exists or defaults are set leave the field empty/non-existent, otherwise
-    // return form data/defaults
-    return defaults ? defaults : undefined;
+  // Check if the schema has a const property defined,  then we should always return the computedDefault since it's coming from the const.
```
Comment (heath-freenome) [inline packages/utils/src/schema/getDefaultFormState.ts:462]:
```suggestion
  // Check if the schema has a const property defined, then we should always return the computedDefault since it's coming from the const.
```

File: packages/utils/test/schema/getDefaultFormStateTest.ts [hunk 5]
```diff
@@ -848,6 +862,52 @@ export default function getDefaultFormStateTest(testValidator: TestValidatorType
...
+            },
+          },
+          const: {
+            RootAndLocalConst: 'FromRoot',
+          },
+        };
+        expect(
+          getObjectDefaults(testValidator, schema, {
+            rootSchema: schema,
+            experimental_defaultFormStateBehavior: { emptyObjectFields: 'skipDefaults' },
```
Comment (heath-freenome) [inline packages/utils/test/schema/getDefaultFormStateTest.ts:900]: Can you add at least 1 default to this schema just to make sure that it isn't included?

File: packages/utils/src/schema/getDefaultFormState.ts (hunk 1 above)
Comment (heath-freenome) [reply packages/utils/src/schema/getDefaultFormState.ts:201]: I see it. Just one small change to the test and I'll be satisfied

**Review by heath-freenome — COMMENTED** [review]
Can you rebase and update the `CHANGELOG.md` pulling the `5.21.3` values into `5.22.0` instead?

File: packages/utils/test/schema/getDefaultFormStateTest.ts (hunk 5 above)
Comment (abdalla-rko) [reply packages/utils/test/schema/getDefaultFormStateTest.ts:959]: I added one default but it will not be merged with the const/default value since we're testing the **getObjectDefaults** method. I added an additional test for the **getDefaultFormState** method where we merge the **formData** and the default value.

File: packages/utils/test/schema/getDefaultFormStateTest.ts [hunk 6]
```diff
@@ -848,6 +918,58 @@ export default function getDefaultFormStateTest(testValidator: TestValidatorType
...
+                },
+              },
+              const: {
+                attr1: 1,
+                attr2: true,
+              },
+            },
+            fromFormData: {
+              type: 'string',
+            },
```
Comment (heath-freenome) [inline packages/utils/test/schema/getDefaultFormStateTest.ts:946]:
```suggestion
            fromFormData: {
              type: 'string',
              default: 'notUsed'
            },
```

File: packages/utils/test/schema/getDefaultFormStateTest.ts [hunk 7]
```diff
@@ -848,6 +918,59 @@ export default function getDefaultFormStateTest(testValidator: TestValidatorType
...
+                },
+              },
+              const: {
+                attr1: 1,
+                attr2: true,
+              },
+            },
+            fromFormData: {
+              type: 'string',
+              default: 'notUsed'
```
Comment (heath-freenome) [inline packages/utils/test/schema/getDefaultFormStateTest.ts:946]:
```suggestion
              default: 'notUsed',
```

**Review by heath-freenome — APPROVED** [review]
