### PR TITLE
fix omit field names with dot #2643

### LINKED ISSUE #2643: omitExtraData drops value of field whose identifier contains a dot "."
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[See playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXN0ZWRfcHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5IjoiYXNkZiJ9LCJsZXZlbC4xLnByb3BlcnR5IjoiYXNkZiJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjEucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4xLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifSwibmVzdGVkX3Byb3BlcnRpZXMiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjIucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=)

When `omitExtraData` is enabled, rjsf drops the value of a nested field for which the identifier contains a dot `.`, submit. This is unexpected behavior. In case the fields are also `required`, this leads to failure of form submission down the road. You can see this if you open the example and submit the form right away.

Note that the value of `level.1.property` seems to not be dropped, so there it works as expected.

Might be related to https://github.com/rjsf-team/react-jsonschema-form/issues/2036

### Steps to Reproduce

[See playground example (same as above)](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXN0ZWRfcHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5IjoiYXNkZiJ9LCJsZXZlbC4xLnByb3BlcnR5IjoiYXNkZiJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjEucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4xLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifSwibmVzdGVkX3Byb3BlcnRpZXMiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjIucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=)

1. Turn on "omit extra data"
2. Add an `object` to the schema and another `object` as child.
3. Add a `required` field with name `level.2.property` and type `string` to the lower-level `object` from before.
4. Fill in dummy values in the form.
5. Submit the form.

#### Expected behavior

Form is submitted without errors.

#### Actual behavior

Form submission fails, field `level.2.property` is marked as required indicating that its value is empty.

### Version

2.5.1

### PR DESCRIPTION
**Pull request by v1ack**
### Reasons for making this change

fixes #2643

If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).

If your PR is non-trivial and you'd like to schedule a synchronous review, please add it to the weekly meeting agenda: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/Form.tsx [hunk 1]
```diff
@@ -453,12 +453,14 @@ export default class Form<
...
-  getUsedFormData = (formData: T, fields: string[]): T => {
+  getUsedFormData = (formData: T, fields: string[][]): T => {
     // For the case of a single input form
     if (fields.length === 0 && typeof formData !== "object") {
       return formData;
     }
 
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore _pick has incorrect type definition, it works with string[][], because lodash/hasIn supports it
     const data: GenericObjectType = _pick(formData, fields);
```
Comment (heath-freenome) [inline packages/core/src/components/Form.tsx:464]: If you add the _pick<GenericObjectType>(formData, fields) does eliminate the need for the two comments above? or Perhaps a type cast?

**Review by heath-freenome — CHANGES_REQUESTED** [review]

File: packages/core/src/components/Form.tsx (hunk 1 above)
Comment (v1ack) [reply packages/core/src/components/Form.tsx:464]: Here is type casting
```typescript
const data: GenericObjectType = _pick(formData, fields as unknown as string[]);
```

Do you think it would be better this way?

Comment (heath-freenome) [reply packages/core/src/components/Form.tsx:464]: Yes, that works. Please make sure to comment about the cast, otherwise, looks good.

**Review by heath-freenome — APPROVED** [review]
