### PR TITLE
fix: Reimplement #2548 to fix #2262

### LINKED ISSUE #2262: Unable to input formData for oneOf while omitExtraData and liveOmit is set to true
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Unable to input formData for oneOf while omitExtraData and liveOmit is set to true
ex: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsibG9yZW0iXX0seyJwcm9wZXJ0aWVzIjp7Imlwc3VtIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImlwc3VtIl19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=

### Steps to Reproduce

1. Select oneOf schema example
2. Select omitExtraData and liveOmit
3. Attempt to input data

#### Expected behavior

Data is inputted 

#### Actual behavior

Nothing happens

### Version

2.4.2

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixes: #2262 by reimplementing #2548

- Updated `@rjsf/utils` to update the `toPathSchema()` method to pick the closest matching option for `oneOf`/`anyOf` choices to render a path schema for it
  - Updated test to maintain 100% coverage
- Updated `@rjsf/core` to cache retrieved options in state for use in the rest of the component
  - Also improved enumOptions to output better labels for options without them when a title is available in either the `schema` or `uiSchema`
  - Added tests to validate both fixes
- Updated the `CHANGELOG.md` accordingly

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 1]
```diff
@@ -14,11 +14,16 @@ import {
 } from "@rjsf/utils";
 
 /** Type used for the state of the `AnyOfField` component */
-type AnyOfFieldState = {
+type AnyOfFieldState<S extends StrictRJSFSchema = RJSFSchema> = {
   /** The currently selected option */
   selectedOption: number;
+  realOptions: S[];
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:20]: Not super clear what `real` means and kind of implies that `options` are fake, so just rename this

```suggestion
  /* The option schemas after retrieving all $refs */
  retrievedOptions: S[];
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 2]
```diff
@@ -28,22 +33,31 @@ class AnyOfField<
...
     super(props);
 
-    const { formData, options } = this.props;
+    const {
+      formData,
+      options,
+      registry: { schemaUtils },
+    } = this.props;
+    // cache the retrieved options in state in case they have $refs to save doing it later
+    const realOptions = options.map((opt: S) =>
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:50]:
```suggestion
    const retrievedOptions = options.map((opt: S) =>
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 3]
```diff
@@ -28,22 +33,31 @@ class AnyOfField<
...
+      schemaUtils.retrieveSchema(opt, formData)
+    );
 
     this.state = {
-      selectedOption: this.getMatchingOption(0, formData, options),
+      realOptions,
+      selectedOption: this.getMatchingOption(0, formData, realOptions),
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:56]:
```suggestion
      retrievedOptions,
      selectedOption: this.getMatchingOption(0, formData, retrievedOptions),
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 4]
```diff
@@ -55,23 +69,34 @@ class AnyOfField<
...
+    let newState = this.state;
+    if (!deepEquals(prevProps.options, options)) {
+      const {
+        registry: { schemaUtils },
+      } = this.props;
+      // re-cache the retrieved options in state in case they have $refs to save doing it later
+      const realOptions = options.map((opt: S) =>
+        schemaUtils.retrieveSchema(opt, formData)
+      );
+      newState = { selectedOption, realOptions };
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:81]:
```suggestion
      const retrievedOptions = options.map((opt: S) =>
        schemaUtils.retrieveSchema(opt, formData)
      );
      newState = { selectedOption, retrievedOptions };
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 5]
```diff
@@ -55,23 +69,34 @@ class AnyOfField<
...
+    }
     if (
       !deepEquals(formData, prevProps.formData) &&
       idSchema.$id === prevProps.idSchema.$id
     ) {
+      const { realOptions } = newState;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:87]:
```suggestion
      const { retrievedOptions } = newState;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 6]
```diff
@@ -55,23 +69,34 @@ class AnyOfField<
...
       const matchingOption = this.getMatchingOption(
         selectedOption,
         formData,
-        options
+        realOptions
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:91]:
```suggestion
        retrievedOptions
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 7]
```diff
@@ -55,23 +69,34 @@ class AnyOfField<
...
       );
 
-      if (!prevState || matchingOption === selectedOption) {
-        return;
+      if (prevState && matchingOption !== selectedOption) {
+        newState = { selectedOption: matchingOption, realOptions };
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:95]:
```suggestion
        newState = { selectedOption: matchingOption, retrievedOptions };
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 8]
```diff
@@ -105,24 +130,19 @@ class AnyOfField<
    * to remove properties that are not part of the newly selected option schema, and then the updated data is passed to
    * the `onChange` handler.
    *
-   * @param option -
+   * @param option - The new option value being selected
    */
   onOptionChange = (option?: string) => {
-    const { selectedOption } = this.state;
-    const { formData, onChange, options, registry } = this.props;
+    const { selectedOption, realOptions } = this.state;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:136]:
```suggestion
    const { selectedOption, retrievedOptions } = this.state;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 9]
```diff
@@ -105,24 +130,19 @@ class AnyOfField<
...
     const { schemaUtils } = registry;
     const intOption = option !== undefined ? parseInt(option, 10) : -1;
     if (intOption === selectedOption) {
       return;
     }
-    const newOption =
-      intOption >= 0
-        ? schemaUtils.retrieveSchema(options[intOption], formData)
-        : undefined;
+    const newOption = intOption >= 0 ? realOptions[intOption] : undefined;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:143]:
```suggestion
    const newOption = intOption >= 0 ? retrievedOptions[intOption] : undefined;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 10]
```diff
@@ -105,24 +130,19 @@ class AnyOfField<
...
     const oldOption =
-      selectedOption >= 0
-        ? schemaUtils.retrieveSchema(options[selectedOption], formData)
-        : undefined;
+      selectedOption >= 0 ? realOptions[selectedOption] : undefined;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:145]:
```suggestion
      selectedOption >= 0 ? retrievedOptions[selectedOption] : undefined;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 11]
```diff
@@ -160,27 +180,28 @@ class AnyOfField<
...
-      options,
       registry,
+      schema,
       uiSchema,
     } = this.props;
 
     const { widgets, fields } = registry;
     const { SchemaField: _SchemaField } = fields;
-    const { selectedOption } = this.state;
+    const { selectedOption, realOptions } = this.state;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:190]:
```suggestion
    const { selectedOption, retrievedOptions } = this.state;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 12]
```diff
@@ -160,27 +180,28 @@ class AnyOfField<
...
+      title = schema.title,
       ...uiOptions
     } = getUiOptions<T, S, F>(uiSchema);
     const Widget = getWidget<T, S, F>({ type: "number" }, widget, widgets);
     const rawErrors = get(errorSchema, ERRORS_KEY, []);
     const fieldErrorSchema = omit(errorSchema, [ERRORS_KEY]);
 
-    const option = options[selectedOption] || null;
-    let optionSchema;
+    const option = realOptions[selectedOption] || null;
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:203]:
```suggestion
    const option = retrievedOptions[selectedOption] || null;
```

File: packages/core/src/components/fields/MultiSchemaField.tsx [hunk 13]
```diff
@@ -190,10 +211,15 @@ class AnyOfField<
...
-    }));
+    const optionLabel = title
+      ? `${title} ${UNKNOWN_OPTION_PREFIX.toLowerCase()}`
+      : UNKNOWN_OPTION_PREFIX;
+    const enumOptions = realOptions.map(
+      (opt: { title?: string }, index: number) => ({
+        label: opt.title || `${optionLabel} ${index + 1}`,
+        value: index,
+      })
+    );
```
Comment (nickgros) [inline packages/core/src/components/fields/MultiSchemaField.tsx:222]:
```suggestion
    const enumOptions = retrievedOptions.map(
      (opt: { title?: string }, index: number) => ({
        label: opt.title || `${optionLabel} ${index + 1}`,
        value: index,
      })
    );
```

**Review by nickgros — APPROVED** [review]
