### PR TITLE
fix: remove defaultProps from function components

### LINKED ISSUE #4705: Replace `defaultProps` with ES6 default parameters in function components
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Anything else?

See https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

### PR DESCRIPTION
**Pull request by Suyog241005**
### Reasons for making this change

- This PR replaces defaultProps usage in function components with ES6 default parameters to ensure compatibility with React 19, where defaultProps on function components are removed.
- fixes #4705 

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: packages/antd/src/widgets/AltDateWidget/index.tsx [hunk 1]
```diff
@@ -59,12 +66,12 @@ export default function AltDateWidget<
...
-AltDateWidget.defaultProps = {
-  autofocus: false,
-  disabled: false,
-  options: {
-    yearsRange: [1900, new Date().getFullYear() + 2],
-  },
-  readonly: false,
-  time: false,
-};
+// AltDateWidget.defaultProps = {
```
Comment (heath-freenome) [inline packages/antd/src/widgets/AltDateWidget/index.tsx]: Just delete these lines

File: packages/antd/src/widgets/AltDateWidget/index.tsx [hunk 2]
```diff
@@ -14,11 +14,18 @@ export default function AltDateWidget<
   T = any,
   S extends StrictRJSFSchema = RJSFSchema,
   F extends FormContextType = any,
->(props: WidgetProps<T, S, F>) {
-  const { autofocus, disabled, id, name, onBlur, onFocus, options, readonly, registry } = props;
+>({
+  autofocus = false,
+  disabled = false,
+  options = { yearsRange: [1900, new Date().getFullYear() + 2] },
```
Comment (heath-freenome) [inline packages/antd/src/widgets/AltDateWidget/index.tsx]: Defaults can behave differently around `options` props than destructure initialization, due to the code that is in the `getWidget()` implementation in `@rjsf/utils`. You may want to deal with that too... See `mergeWidgetOptions()` in `getWidget.ts`

File: packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx [hunk 3]
```diff
@@ -59,14 +66,14 @@ function AltDateWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F exten
...
-AltDateWidget.defaultProps = {
-  autofocus: false,
-  disabled: false,
-  readonly: false,
-  time: false,
-  options: {
-    yearsRange: [1900, new Date().getFullYear() + 2],
-  },
-};
+// AltDateWidget.defaultProps = {
```
Comment (heath-freenome) [inline packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx]: Delete these lines

File: packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx [hunk 4]
```diff
@@ -11,12 +11,19 @@ import {
...
-  props: WidgetProps<T, S, F>,
-) {
-  const { autofocus, disabled, id, onBlur, onFocus, options, readonly, registry } = props;
+function AltDateWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any>({
+  autofocus = false,
+  disabled = false,
+  readonly = false,
+  time = false,
+  options = {
+    yearsRange: [1900, new Date().getFullYear() + 2],
```
Comment (heath-freenome) [inline packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx]: Defaults can behave differently around `options` props than destructure initialization, due to the code that is in the `getWidget()` implementation in `@rjsf/utils`. You may want to deal with that too... See `mergeWidgetOptions()` in `getWidget.ts`

File: packages/core/src/components/widgets/TextareaWidget.tsx [hunk 5]
```diff
@@ -54,9 +54,9 @@ function TextareaWidget<T = any, S extends StrictRJSFSchema = RJSFSchema, F exte
...
 }
 
-TextareaWidget.defaultProps = {
-  autofocus: false,
-  options: {},
-};
+// TextareaWidget.defaultProps = {
+//   autofocus: false,
+//   options: {},
+// };
```
Comment (heath-freenome) [inline packages/core/src/components/widgets/TextareaWidget.tsx]: Just delete these lines

**Comment by heath-freenome** [comment]
Also, can you update the CHANGELOG.md

File: packages/antd/src/widgets/AltDateWidget/index.tsx [hunk 6]
```diff
@@ -14,11 +14,18 @@ export default function AltDateWidget<
...
+  readonly = false,
+  time = false,
+  ...props
+}: WidgetProps<T, S, F>) {
+  const { id, name, onBlur, onFocus, registry } = props;
   const { formContext, translateString } = registry;
   const { rowGutter = 24 } = formContext as GenericObjectType;
-  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps(props);
+  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps({ ...props, autofocus, options });
```
Comment (heath-freenome) [inline packages/antd/src/widgets/AltDateWidget/index.tsx]: This code is equivalent to what the code in `getWidget()` does.  You will want to remove the default assignment above
```suggestion
  const realOptions = { yearsRange: [1900, new Date().getFullYear() + 2], ...options };
  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps({ ...props, autofocus, realOptions });
```

File: packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx [hunk 7]
```diff
@@ -11,12 +11,19 @@ import {
...
+  },
+  ...props
+}: WidgetProps<T, S, F>) {
+  const { id, onBlur, onFocus, registry } = props;
   const { translateString } = registry;
-  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps(props);
+  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps({ ...props, options });
```
Comment (heath-freenome) [inline packages/chakra-ui/src/AltDateWidget/AltDateWidget.tsx]: This code is equivalent to what the code in `getWidget()` does.  You will want to remove the default assignment above
```suggestion
  const realOptions = { yearsRange: [1900, new Date().getFullYear() + 2], ...options };
  const { elements, handleChange, handleClear, handleSetNow } = useAltDateWidgetProps({ ...props, realOptions });
```

File: packages/antd/src/widgets/AltDateWidget/index.tsx (hunk 6 above)
Comment (Suyog241005) [reply packages/antd/src/widgets/AltDateWidget/index.tsx]: image

- `realOptions` should be passed in `options` key as shown in screenshot right?

**Comment by heath-freenome** [comment]
One last thing... Please update the `CHANGELOG.md`

**Comment by Suyog241005** [comment]
> One last thing... Please update the `CHANGELOG.md`

@heath-freenome Updated `CHANGELOG.md`. Please have a look when you get a chance.

File: CHANGELOG.md [hunk 8]
```diff
@@ -18,6 +18,18 @@ should change the heading of the (upcoming) version to include a major version b
...
+
+- Removed deprecated `defaultProps` from `AltDateTimeWidget` and `AltDateWidget` components, preserving all existing behavior ([#4904](https://github.com/rjsf-team/react-jsonschema-form/pull/4904))
+
+## @rjsf/chakra-ui
+
+- Removed deprecated `defaultProps` from `AltDateTimeWidget` and `AltDateWidget` components, preserving all existing behavior ([#4904](https://github.com/rjsf-team/react-jsonschema-form/pull/4904))
+
+## @rjsf/core
+
+- Removed deprecated `defaultProps` from `TextareaWidget` component, preserving all existing behavior ([#4904](https://github.com/rjsf-team/react-jsonschema-form/pull/4904))
```
Comment (heath-freenome) [inline CHANGELOG.md]:
```suggestion
- Removed deprecated `defaultProps` from `AltDateTimeWidget` and `AltDateWidget` components, preserving all existing behavior

## @rjsf/chakra-ui

- Removed deprecated `defaultProps` from `AltDateTimeWidget` and `AltDateWidget` components, preserving all existing behavior

## @rjsf/core

- Removed deprecated `defaultProps` from `TextareaWidget` component, preserving all existing behavior
```
