### PR TITLE
Fix 4821 by no saving undefined values into an object for a null type field

### LINKED ISSUE #4821: Fields keep in form data while no needed anymore
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.24.13

### Current Behavior

I have a json schema which have some oneOf properties and when changing them from simple one to item with inner properties I get them rendered, but when I switched back to simple one without this properties this addtional properties is still rendered, but shouldn't anymore

### Expected Behavior

I expect to have when changing oneof selected property to simple and complex one the form data will be cleared

### Steps To Reproduce

1. Open sandbox
2. Change ssl_mode to verify_ca
3. You will see that some additional fields rendered, which were not presented before
4. When change this select from verify_ca back to disable you will still see this fields -> BUG

### Environment

```markdown
- OS: Mac OS 15.7.1
- Node: 22.14.0
- npm: 10.9.2
```

### Anything else?

Sanbox link [link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzc2xfbW9kZSI6eyJtb2RlIjoiZGlzYWJsZSJ9fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJ0aXRsZSI6IlBvc3RncmVzIFNvdXJjZSBTcGVjIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic3NsX21vZGUiOnsidGl0bGUiOiJTU0wgTW9kZXMiLCJkZXNjcmlwdGlvbiI6IlNTTCBjb25uZWN0aW9uIG1vZGVzLiBcbiAgUmVhZCBtb3JlIDxhIGhyZWY9XCJodHRwczovL2pkYmMucG9zdGdyZXNxbC5vcmcvZG9jdW1lbnRhdGlvbi9oZWFkL3NzbC1jbGllbnQuaHRtbFwiPiBpbiB0aGUgZG9jczwvYT4uIiwidHlwZSI6Im9iamVjdCIsIm9yZGVyIjo4LCJncm91cCI6InNlY3VyaXR5Iiwib25lT2YiOlt7InRpdGxlIjoiZGlzYWJsZSIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp0cnVlLCJkZXNjcmlwdGlvbiI6IkRpc2FibGVzIGVuY3J5cHRpb24gb2YgY29tbXVuaWNhdGlvbiBiZXR3ZWVuIEFpcmJ5dGUgYW5kIHNvdXJjZSBkYXRhYmFzZS4iLCJyZXF1aXJlZCI6WyJtb2RlIl0sInByb3BlcnRpZXMiOnsibW9kZSI6eyJ0eXBlIjoic3RyaW5nIiwiY29uc3QiOiJkaXNhYmxlIiwib3JkZXIiOjB9fX0seyJ0aXRsZSI6ImFsbG93IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnRydWUsImRlc2NyaXB0aW9uIjoiRW5hYmxlcyBlbmNyeXB0aW9uIG9ubHkgd2hlbiByZXF1aXJlZCBieSB0aGUgc291cmNlIGRhdGFiYXNlLiIsInJlcXVpcmVkIjpbIm1vZGUiXSwicHJvcGVydGllcyI6eyJtb2RlIjp7InR5cGUiOiJzdHJpbmciLCJjb25zdCI6ImFsbG93Iiwib3JkZXIiOjB9fX0seyJ0aXRsZSI6InByZWZlciIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp0cnVlLCJkZXNjcmlwdGlvbiI6IkFsbG93cyB1bmVuY3J5cHRlZCBjb25uZWN0aW9uIG9ubHkgaWYgdGhlIHNvdXJjZSBkYXRhYmFzZSBkb2VzIG5vdCBzdXBwb3J0IGVuY3J5cHRpb24uIiwicmVxdWlyZWQiOlsibW9kZSJdLCJwcm9wZXJ0aWVzIjp7Im1vZGUiOnsidHlwZSI6InN0cmluZyIsImNvbnN0IjoicHJlZmVyIiwib3JkZXIiOjB9fX0seyJ0aXRsZSI6InJlcXVpcmUiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6dHJ1ZSwiZGVzY3JpcHRpb24iOiJBbHdheXMgcmVxdWlyZSBlbmNyeXB0aW9uLiBJZiB0aGUgc291cmNlIGRhdGFiYXNlIHNlcnZlciBkb2VzIG5vdCBzdXBwb3J0IGVuY3J5cHRpb24sIGNvbm5lY3Rpb24gd2lsbCBmYWlsLiIsInJlcXVpcmVkIjpbIm1vZGUiXSwicHJvcGVydGllcyI6eyJtb2RlIjp7InR5cGUiOiJzdHJpbmciLCJjb25zdCI6InJlcXVpcmUiLCJvcmRlciI6MH19fSx7InRpdGxlIjoidmVyaWZ5LWNhIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnRydWUsImRlc2NyaXB0aW9uIjoiQWx3YXlzIHJlcXVpcmUgZW5jcnlwdGlvbiBhbmQgdmVyaWZpZXMgdGhhdCB0aGUgc291cmNlIGRhdGFiYXNlIHNlcnZlciBoYXMgYSB2YWxpZCBTU0wgY2VydGlmaWNhdGUuIiwicmVxdWlyZWQiOlsibW9kZSIsImNhX2NlcnRpZmljYXRlIl0sInByb3BlcnRpZXMiOnsibW9kZSI6eyJ0eXBlIjoic3RyaW5nIiwiY29uc3QiOiJ2ZXJpZnktY2EiLCJvcmRlciI6MH0sImNhX2NlcnRpZmljYXRlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNBIENlcnRpZmljYXRlIiwiZGVzY3JpcHRpb24iOiJDQSBjZXJ0aWZpY2F0ZSIsImFpcmJ5dGVfc2VjcmV0Ijp0cnVlLCJtdWx0aWxpbmUiOnRydWUsIm9yZGVyIjoxfSwiY2xpZW50X2NlcnRpZmljYXRlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNsaWVudCBDZXJ0aWZpY2F0ZSIsImRlc2NyaXB0aW9uIjoiQ2xpZW50IGNlcnRpZmljYXRlIiwiYWlyYnl0ZV9zZWNyZXQiOnRydWUsIm11bHRpbGluZSI6dHJ1ZSwib3JkZXIiOjIsImFsd2F5c19zaG93Ijp0cnVlfSwiY2xpZW50X2tleSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJDbGllbnQgS2V5IiwiZGVzY3JpcHRpb24iOiJDbGllbnQga2V5IiwiYWlyYnl0ZV9zZWNyZXQiOnRydWUsIm11bHRpbGluZSI6dHJ1ZSwib3JkZXIiOjMsImFsd2F5c19zaG93Ijp0cnVlfSwiY2xpZW50X2tleV9wYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJDbGllbnQga2V5IHBhc3N3b3JkIiwiZGVzY3JpcHRpb24iOiJQYXNzd29yZCBmb3Iga2V5c3RvcmFnZS4gSWYgeW91IGRvIG5vdCBhZGQgaXQgLSB0aGUgcGFzc3dvcmQgd2lsbCBiZSBnZW5lcmF0ZWQgYXV0b21hdGljYWxseS4iLCJhaXJieXRlX3NlY3JldCI6dHJ1ZSwib3JkZXIiOjR9fX0seyJ0aXRsZSI6InZlcmlmeS1mdWxsIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnRydWUsImRlc2NyaXB0aW9uIjoiVGhpcyBpcyB0aGUgbW9zdCBzZWN1cmUgbW9kZS4gQWx3YXlzIHJlcXVpcmUgZW5jcnlwdGlvbiBhbmQgdmVyaWZpZXMgdGhlIGlkZW50aXR5IG9mIHRoZSBzb3VyY2UgZGF0YWJhc2Ugc2VydmVyLiIsInJlcXVpcmVkIjpbIm1vZGUiLCJjYV9jZXJ0aWZpY2F0ZSJdLCJwcm9wZXJ0aWVzIjp7Im1vZGUiOnsidHlwZSI6InN0cmluZyIsImNvbnN0IjoidmVyaWZ5LWZ1bGwiLCJvcmRlciI6MH0sImNhX2NlcnRpZmljYXRlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNBIENlcnRpZmljYXRlIiwiZGVzY3JpcHRpb24iOiJDQSBjZXJ0aWZpY2F0ZSIsImFpcmJ5dGVfc2VjcmV0Ijp0cnVlLCJtdWx0aWxpbmUiOnRydWUsIm9yZGVyIjoxfSwiY2xpZW50X2NlcnRpZmljYXRlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNsaWVudCBDZXJ0aWZpY2F0ZSIsImRlc2NyaXB0aW9uIjoiQ2xpZW50IGNlcnRpZmljYXRlIiwiYWlyYnl0ZV9zZWNyZXQiOnRydWUsIm11bHRpbGluZSI6dHJ1ZSwib3JkZXIiOjIsImFsd2F5c19zaG93Ijp0cnVlfSwiY2xpZW50X2tleSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJDbGllbnQgS2V5IiwiZGVzY3JpcHRpb24iOiJDbGllbnQga2V5IiwiYWlyYnl0ZV9zZWNyZXQiOnRydWUsIm11bHRpbGluZSI6dHJ1ZSwib3JkZXIiOjMsImFsd2F5c19zaG93Ijp0cnVlfSwiY2xpZW50X2tleV9wYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJDbGllbnQga2V5IHBhc3N3b3JkIiwiZGVzY3JpcHRpb24iOiJQYXNzd29yZCBmb3Iga2V5c3RvcmFnZS4gSWYgeW91IGRvIG5vdCBhZGQgaXQgLSB0aGUgcGFzc3dvcmQgd2lsbCBiZSBnZW5lcmF0ZWQgYXV0b21hdGljYWxseS4iLCJhaXJieXRlX3NlY3JldCI6dHJ1ZSwib3JkZXIiOjR9fX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2NvbXBvbmVudFVwZGF0ZVN0cmF0ZWd5IjoiY3VzdG9tRGVlcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJjb25zdEFzRGVmYXVsdHMiOiJhbHdheXMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMiLCJtZXJnZURlZmF1bHRzSW50b0Zvcm1EYXRhIjoidXNlRm9ybURhdGFJZlByZXNlbnQifSwibGl2ZVZhbGlkYXRlIjpmYWxzZX0sInZhbGlkYXRvciI6IkFKVjgiLCJzYW1wbGVOYW1lIjoiU2ltcGxlIn0=)

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixed #4821 by not saving an undefined field value into an object when that field has the `null` type
- Updated `getDefaultFormState()` to not save an undefined field value into an object when the type is `null` and `excludeObjectChildren` is provided
  - Updated the tests to verify this new fix
- Updated the `CHANGELOG.md` accordingly

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

Before:

https://github.com/user-attachments/assets/9380a56f-285c-4a5e-9d9d-8df65385f8ea

After:

https://github.com/user-attachments/assets/fb86bd49-fde6-43dc-b13f-c53cd6a79e13

### CODE REVIEW

File: packages/utils/test/schema/getDefaultFormStateTest.ts [hunk 1]
```diff
@@ -376,6 +376,53 @@ export default function getDefaultFormStateTest(testValidator: TestValidatorType
         });
       });
 
+      describe("an object with an null-type property and includeUndefinedValues is 'excludeObjectChildren'", () => {
+        const schema: RJSFSchema = {
+          type: 'object',
+          properties: {
+            optionalNumberProperty: {
```
Comment (nickgros) [inline packages/utils/test/schema/getDefaultFormStateTest.ts]:
```suggestion
            optionalNullProperty: {
```
